// Bilingual puzzle content for "The Wheel".

export interface LocalizedString {
    en: string;
    pl: string;
}

export interface PuzzleContent {
    id: string;
    phrase: LocalizedString;
    category: LocalizedString;
}

export interface PuzzlePack {
    id: string;
    puzzles: PuzzleContent[];
}

const all: PuzzlePack = {
    id: 'all',
    puzzles: [
        { id: 'wheel-001', phrase: { en: 'BETTER LATE THAN NEVER', pl: 'LEPIEJ PÓŹNO NIŻ WCALE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-002', phrase: { en: 'THE EARLY BIRD', pl: 'RANNY PTASZEK' }, category: { en: 'Phrase', pl: 'Powiedzenie' } },
        { id: 'wheel-003', phrase: { en: 'PIECE OF CAKE', pl: 'BUŁKA Z MASŁEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-004', phrase: { en: 'BREAK A LEG', pl: 'POŁAMANIA NÓG' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-005', phrase: { en: 'HOME SWEET HOME', pl: 'WSZĘDZIE DOBRZE ALE W DOMU NAJLEPIEJ' }, category: { en: 'Phrase', pl: 'Powiedzenie' } },
        { id: 'wheel-006', phrase: { en: 'TIME IS MONEY', pl: 'CZAS TO PIENIĄDZ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-007', phrase: { en: 'ACTIONS SPEAK LOUDER THAN WORDS', pl: 'CZYNY NIE SŁOWA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-008', phrase: { en: 'ONCE IN A BLUE MOON', pl: 'RAZ NA RUSKI ROK' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-009', phrase: { en: 'KNOWLEDGE IS POWER', pl: 'WIEDZA TO POTĘGA' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-010', phrase: { en: 'EVERY CLOUD HAS A SILVER LINING', pl: 'NIE MA TEGO ZŁEGO CO BY NA DOBRE NIE WYSZŁO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-011', phrase: { en: 'THE APPLES NEVER FALL FAR FROM THE TREE', pl: 'NIEDALEKO PADA JABŁKO OD JABŁONI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-012', phrase: { en: 'BITING OFF MORE THAN YOU CAN CHEW', pl: 'PORWAĆ SIĘ Z MOTYKĄ NA SŁOŃCE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-013', phrase: { en: 'DONT JUDGE A BOOK BY ITS COVER', pl: 'NIE OCENIAJ KSIĄŻKI PO OKŁADCE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-014', phrase: { en: 'PRACTICE MAKES PERFECT', pl: 'TRENING CZYNI MISTRZA' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-015', phrase: { en: 'OUT OF SIGHT OUT OF MIND', pl: 'CO Z OCZU TO Z SERCA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-016', phrase: { en: 'A PICTURE IS WORTH A THOUSAND WORDS', pl: 'JEDEN OBRAZ WART WIĘCEJ NIŻ TYSIĄC SŁÓW' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-017', phrase: { en: 'LET THE CAT OUT OF THE BAG', pl: 'WYGADAĆ SEKRET' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-018', phrase: { en: 'BEAT AROUND THE BUSH', pl: 'OWIJAĆ W BAWEŁNĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-019', phrase: { en: 'CURIOSITY KILLED THE CAT', pl: 'CIEKAWOŚĆ TO PIERWSZY STOPIEŃ DO PIEKŁA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-020', phrase: { en: 'NO PAIN NO GAIN', pl: 'BEZ PRACY NIE MA KOŁACZY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-021', phrase: { en: 'BIRDS OF A FEATHER FLOCK TOGETHER', pl: 'CIĄGNIE SWÓJ DO SWEGO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-022', phrase: { en: 'ROME WASNT BUILT IN A DAY', pl: 'NIE OD RAZU KRAKÓW ZBUDOWANO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-023', phrase: { en: 'EASY COME EASY GO', pl: 'ŁATWO PRZYSZŁO ŁATWO POSZŁO' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-024', phrase: { en: 'THROUGH THICK AND THIN', pl: 'NA DOBRE I NA ZŁE' }, category: { en: 'Phrase', pl: 'Powiedzenie' } },
        { id: 'wheel-025', phrase: { en: 'HIT THE NAIL ON THE HEAD', pl: 'TRAFIĆ W SEDNO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-026', phrase: { en: 'BETTER SAFE THAN SORRY', pl: 'STRZEŻONEGO PAN BÓG STRZEŻE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-027', phrase: { en: 'OUT OF THE BLUE', pl: 'Z NIENACKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-028', phrase: { en: 'BREAK THE ICE', pl: 'PRZEŁAMAĆ LODY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-029', phrase: { en: 'A DIAMOND IN THE ROUGH', pl: 'NIEOSZLIFOWANY DIAMENT' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-030', phrase: { en: 'BITE THE BULLET', pl: 'ZACISNĄĆ ZĘBY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-031', phrase: { en: 'BLOOD IS THICKER THAN WATER', pl: 'KREW NIE WODA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-032', phrase: { en: 'ALL THAT GLITTERS IS NOT GOLD', pl: 'NIE WSZYSTKO ZŁOTO CO SIĘ ŚWIECI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-033', phrase: { en: 'BETWEEN A ROCK AND A HARD PLACE', pl: 'MIĘDZY MŁOTEM A KOWADŁEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-034', phrase: { en: 'EVERYTHING COMES TO AN END', pl: 'WSZYSTKO CO DOBRE SZYBKO SIĘ KOŃCZY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-035', phrase: { en: 'FORGET AND FORGIVE', pl: 'PUŚCIĆ W NIEPAMIĘĆ' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-036', phrase: { en: 'GET COLD FEET', pl: 'STCHÓRZYĆ W OSTATNIEJ CHWILI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-037', phrase: { en: 'IN THE LONG RUN', pl: 'NA DŁUŻSZĄ METĘ' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-038', phrase: { en: 'KEEP AN EYE ON', pl: 'MIEĆ NA OKU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-039', phrase: { en: 'LAST BUT NOT LEAST', pl: 'OSTATNI LECZ NIE MNIEJ WAŻNY' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-040', phrase: { en: 'MAKE A LONG STORY SHORT', pl: 'MÓWIĄC W SKRÓCIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-041', phrase: { en: 'NEVER SAY NEVER', pl: 'NIGDY NIE MÓW NIGDY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-042', phrase: { en: 'ON TOP OF THE WORLD', pl: 'W SIÓDMYM NIEBIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-043', phrase: { en: 'POINT OF VIEW', pl: 'PUNKT WIDZENIA' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-044', phrase: { en: 'RAIN OR SHINE', pl: 'BEZ WZGLĘDU NA POGODĘ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-045', phrase: { en: 'SO FAR SO GOOD', pl: 'JAK NA RAZIE JEST DOBRZE' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-046', phrase: { en: 'THE SKY IS THE LIMIT', pl: 'WSZYSTKO JEST MOŻLIWE' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-047', phrase: { en: 'UNDER YOUR NOSE', pl: 'POD NOSEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-048', phrase: { en: 'UP TO DATE', pl: 'NA BIEŻĄCO' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-049', phrase: { en: 'WORK IN PROGRESS', pl: 'PRACA W TOKU' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-050', phrase: { en: 'ZIP YOUR LIP', pl: 'TRZYMAJ JĘZYK ZA ZĘBAMI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-051', phrase: { en: 'ADD INSULT TO INJURY', pl: 'DOLEWAĆ OLIWY DO OGNIA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-052', phrase: { en: 'BACK TO THE DRAWING BOARD', pl: 'ZACZYNAĆ OD ZERA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-053', phrase: { en: 'CALL IT A DAY', pl: 'SKOŃCZYĆ NA DZIŚ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-054', phrase: { en: 'CUT TO THE CHASE', pl: 'PRZEJŚĆ DO RZECZY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-055', phrase: { en: 'GET OUT OF HAND', pl: 'WYMKNĄĆ SIĘ SPOD KONTROLI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-056', phrase: { en: 'HANG IN THERE', pl: 'TRZYMAJ SIĘ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-057', phrase: { en: 'IT IS NOT ROCKET SCIENCE', pl: 'TO NIE ŻADNA FILOZOFIA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-058', phrase: { en: 'LET SOMEONE OFF THE HOOK', pl: 'UPIEC SIĘ KOMUŚ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-059', phrase: { en: 'MISS THE BOAT', pl: 'PRZEGAPIĆ OKAZJĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-060', phrase: { en: 'ON THE BALL', pl: 'TRZYMAĆ RĘKĘ NA PULSIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-061', phrase: { en: 'PULL SOMEONES LEG', pl: 'ROBIĆ KOGOŚ W BALONA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-062', phrase: { en: 'SEE EYE TO EYE', pl: 'MIEĆ TAKIE SAMO ZDANIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-063', phrase: { en: 'SPEAK OF THE DEVIL', pl: 'O WILKU MOWA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-064', phrase: { en: 'TAKE IT WITH A GRAIN OF SALT', pl: 'PRZYJMOWAĆ Z PRZYMRUŻENIEM OKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-065', phrase: { en: 'THE LAST STRAW', pl: 'KROPLA KTÓRA PRZEPEŁNIŁA CZARĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-066', phrase: { en: 'UNDER THE WEATHER', pl: 'CZUĆ SIĘ NIEWYRAŹNIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-067', phrase: { en: 'WE WILL CROSS THAT BRIDGE', pl: 'NIE MARTWMY SIĘ NA ZAPAS' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-068', phrase: { en: 'WRAP YOUR HEAD AROUND IT', pl: 'OGARNĄĆ COŚ ROZUMEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-069', phrase: { en: 'YOU CAN SAY THAT AGAIN', pl: 'ŚWIĘTA RACJA' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-070', phrase: { en: 'YOUR GUESS IS AS GOOD AS MINE', pl: 'WIEM TYLE SAMO CO TY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-071', phrase: { en: 'A BIRD IN THE HAND', pl: 'LEPSZY WRÓBEL W GARŚCI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-072', phrase: { en: 'A PENNY FOR YOUR THOUGHTS', pl: 'O CZYM TAK MYŚLISZ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-073', phrase: { en: 'A PERFECT STORM', pl: 'KUMULACJA NIESZCZĘŚĆ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-074', phrase: { en: 'A TASTE OF YOUR OWN MEDICINE', pl: 'ODPŁACIĆ PIĘKNYM ZA NADOBNE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-075', phrase: { en: 'BEATING A DEAD HORSE', pl: 'WAŁKOWAĆ TEMAT BEZ KOŃCA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-076', phrase: { en: 'BREAK THE BANK', pl: 'ROZBIĆ BANK' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-077', phrase: { en: 'BURN BRIDGES', pl: 'PALIĆ MOSTY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-078', phrase: { en: 'BY THE SKIN OF YOUR TEETH', pl: 'O MAŁY WŁOS' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-079', phrase: { en: 'COMPARING APPLES TO ORANGES', pl: 'PORÓWNYWAĆ RZECZY NIEPORÓWNYWALNE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-080', phrase: { en: 'CUT SOMEONE SOME SLACK', pl: 'PRZYMRUŻYĆ NA COŚ OKO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-081', phrase: { en: 'DOING SOMETHING AT THE DROP OF A HAT', pl: 'ROBIĆ COŚ NA ZAWOŁANIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-082', phrase: { en: 'DONT COUNT YOUR CHICKENS', pl: 'NIE CHWAL DNIA PRZED ZACHODEM SŁOŃCA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-083', phrase: { en: 'DONT GIVE UP THE DAY JOB', pl: 'NIE MASZ DO TEGO TALENTU' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-084', phrase: { en: 'DONT PUT ALL YOUR EGGS IN ONE BASKET', pl: 'NIE STAWIAJ WSZYSTKIEGO NA JEDNĄ KARTĘ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-085', phrase: { en: 'EVERY DOG HAS ITS DAY', pl: 'KAŻDY MA SWOJE PIĘĆ MINUT' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-086', phrase: { en: 'FAMILIARITY BREEDS CONTEMPT', pl: 'ZBYTNIA ZAŻYŁOŚĆ RODZI POGARDĘ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-087', phrase: { en: 'GET A TASTE OF YOUR OWN MEDICINE', pl: 'POCZUĆ WŁASNĄ BROŃ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-088', phrase: { en: 'GET SOMETHING OUT OF YOUR SYSTEM', pl: 'WYRZUCIĆ COŚ Z SIEBIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-089', phrase: { en: 'GIVE SOMEONE THE BENEFIT OF THE DOUBT', pl: 'DAĆ KOMUŚ KREDYT ZAUFANIA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-090', phrase: { en: 'GIVE SOMEONE THE COLD SHOULDER', pl: 'POTRAKTOWAĆ KOGOŚ CHŁODNO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-091', phrase: { en: 'GOOD THINGS COME TO THOSE WHO WAIT', pl: 'CIERPLIWOŚĆ JEST CNOTĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-092', phrase: { en: 'HE HAS BIGGER FISH TO FRY', pl: 'MA WAŻNIEJSZE SPRAWY NA GŁOWIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-093', phrase: { en: 'HIT THE SACK', pl: 'UDAĆ SIĘ NA SPOCZYNEK' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-094', phrase: { en: 'IGNORANCE IS BLISS', pl: 'NIEWIEDZA JEST BŁOGOSŁAWIEŃSTWEM' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-095', phrase: { en: 'IT TAKES TWO TO TANGO', pl: 'DO TANGA TRZEBA DWOJGA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-096', phrase: { en: 'JUMP ON THE BANDWAGON', pl: 'PŁYNĄĆ Z PRĄDEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-097', phrase: { en: 'KEEP YOUR CHIN UP', pl: 'GŁOWA DO GÓRY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-098', phrase: { en: 'LEAVE NO STONE UNTURNED', pl: 'PORUSZYĆ NIEBO I ZIEMIĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-099', phrase: { en: 'LET SLEEPING DOGS LIE', pl: 'NIE WYWOŁUJ WILKA Z LASU' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-100', phrase: { en: 'LIVE AND LEARN', pl: 'CZŁOWIEK UCZY SIĘ CAŁE ŻYCIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-101', phrase: { en: 'METHOD TO MY MADNESS', pl: 'W TYM SZALEŃSTWIE JEST METODA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-102', phrase: { en: 'NOT MY CUP OF TEA', pl: 'TO NIE MOJA BAJKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-103', phrase: { en: 'OFF THE TOP OF MY HEAD', pl: 'Z PAMIĘCI' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-104', phrase: { en: 'ON THE TIP OF MY TONGUE', pl: 'NA KOŃCU JĘZYKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-105', phrase: { en: 'PRACTICE WHAT YOU PREACH', pl: 'DAWAJ PRZYKŁAD WŁASNYM POSTĘPOWANIEM' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-106', phrase: { en: 'SIT ON THE FENCE', pl: 'NIE ZAJMOWAĆ STANOWISKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-107', phrase: { en: 'SKELETON IN THE CLOSET', pl: 'TRUP W SZAFIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-108', phrase: { en: 'THE BEST OF BOTH WORLDS', pl: 'TO CO NAJLEPSZE Z OBU ŚWIATÓW' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-109', phrase: { en: 'THE WHOLE NINE YARDS', pl: 'NA CAŁEGO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-110', phrase: { en: 'TO BE IN THE SAME BOAT', pl: 'JECHAĆ NA TYM SAMYM WÓZKU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-111', phrase: { en: 'TO KILL TIME', pl: 'ZABIJAĆ CZAS' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-112', phrase: { en: 'WHEN PIGS FLY', pl: 'JAK MI KAKTUS NA DŁONI WYROŚNIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-113', phrase: { en: 'A CHIP ON THE SHOULDER', pl: 'MIEĆ ŻAL DO ŚWIATA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-114', phrase: { en: 'A LEOPARD CANT CHANGE ITS SPOTS', pl: 'NATURY NIE OSZUKASZ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-115', phrase: { en: 'BURN THE MIDNIGHT OIL', pl: 'ŚLĘCZEĆ PO NOCACH' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-116', phrase: { en: 'DO UNTO OTHERS', pl: 'NIE CZYŃ DRUGIEMU CO TOBIE NIEMIŁE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-117', phrase: { en: 'DRIVE SOMEONE UP THE WALL', pl: 'DOPROWADZAĆ KOGOŚ DO SZAŁU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-118', phrase: { en: 'KEEP YOUR FINGERS CROSSED', pl: 'TRZYMAĆ KCIUKI' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-119', phrase: { en: 'STEAL SOMEONES THUNDER', pl: 'SKRAŚĆ KOMUŚ SHOW' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-120', phrase: { en: 'THE BALL IS IN YOUR COURT', pl: 'PIŁECZKA JEST PO TWOJEJ STRONIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-121', phrase: { en: 'ABSENCE MAKES THE HEART GROW FONDER', pl: 'ROZŁĄKA SPRAWIA ŻE KOCHAMY MOCNIEJ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-122', phrase: { en: 'BEAUTY IS IN THE EYE OF THE BEHOLDER', pl: 'PIĘKNO JEST RZECZĄ WZGLĘDNĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-123', phrase: { en: 'CLEANLINESS IS NEXT TO GODLINESS', pl: 'CZYSTOŚĆ TO ZDROWIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-124', phrase: { en: 'DON\'T BITE THE HAND THAT FEEDS YOU', pl: 'NIE GRYŹ RĘKI KTÓRA CIĘ KARMI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-125', phrase: { en: 'GOOD THINGS COME IN SMALL PACKAGES', pl: 'MAŁE JEST PIĘKNE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-126', phrase: { en: 'IF THE SHOE FITS WEAR IT', pl: 'UDERZ W STÓŁ A NOŻYCE SIĘ ODEZWĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-127', phrase: { en: 'NO NEWS IS GOOD NEWS', pl: 'BRAK WIADOMOŚCI TO DOBRA WIADOMOŚĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-128', phrase: { en: 'OUT OF THE FRYING PAN INTO THE FIRE', pl: 'Z DESZCZU POD RYNNĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-129', phrase: { en: 'SLOW AND STEADY WINS THE RACE', pl: 'SPIESZ SIĘ POWOLI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-130', phrase: { en: 'TWO HEADS ARE BETTER THAN ONE', pl: 'CO DWIE GŁOWY TO NIE JEDNA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-131', phrase: { en: 'WHEN IN ROME DO AS THE ROMANS DO', pl: 'JEŚLI WEJDZIESZ MIĘDZY WRONY MUSISZ KRAKAĆ JAK I ONE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-132', phrase: { en: 'WHERE THERE IS SMOKE THERE IS FIRE', pl: 'NIE MA DYMU BEZ OGNIA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-133', phrase: { en: 'YOU REAP WHAT YOU SOW', pl: 'CO ZASIEJESZ TO ZBIERZESZ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-134', phrase: { en: 'A STITCH IN TIME SAVES NINE', pl: 'LEPIEJ ZAPOBIEGAĆ NIŻ LECZYĆ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-135', phrase: { en: 'ALL GOOD THINGS COME TO AN END', pl: 'WSZYSTKO CO DOBRE SZYBKO SIĘ KOŃCZY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-136', phrase: { en: 'A PENNY SAVED IS A PENNY EARNED', pl: 'GROSZ DO GROSZA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-140', phrase: { en: 'FORTUNE FAVORS THE BOLD', pl: 'DO ODWAŻNYCH ŚWIAT NALEŻY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-141', phrase: { en: 'HONESTY IS THE BEST POLICY', pl: 'UCZCIWOŚĆ POPŁACA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-142', phrase: { en: 'IF AT FIRST YOU DONT SUCCEED', pl: 'DO TRZECH RAZY SZTUKA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-143', phrase: { en: 'LOOK BEFORE YOU LEAP', pl: 'NAJPIERW POMYŚL POTEM DZIAŁAJ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-144', phrase: { en: 'WHERE THERE IS A WILL THERE IS A WAY', pl: 'DLA CHCĄCEGO NIC TRUDNEGO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-146', phrase: { en: 'LOVE IS BLIND', pl: 'MIŁOŚĆ JEST ŚLEPA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-147', phrase: { en: 'GREAT MINDS THINK ALIKE', pl: 'WIELKIE UMYSŁY MYŚLĄ PODOBNIE' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-148', phrase: { en: 'A HOUSE IS NOT A HOME', pl: 'DOM TO NIE TYLKO ŚCIANY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-149', phrase: { en: 'TIME IS A GREAT HEALER', pl: 'CZAS LECZY RANY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-150', phrase: { en: 'STRIKE WHILE THE IRON IS HOT', pl: 'KUJ ŻELAZO PÓKI GORĄCE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-151', phrase: { en: 'KEEP YOUR EYES ON THE PRIZE', pl: 'SKUP SIĘ NA CELU' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-152', phrase: { en: 'DONT CRY OVER SPILLED MILK', pl: 'NIE PŁACZ NAD ROZLANYM MLEKIEM' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-153', phrase: { en: 'OUT OF THE FRYING PAN', pl: 'Z DESZCZU POD RYNNĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-154', phrase: { en: 'PEOPLE WHO LIVE IN GLASS HOUSES', pl: 'PRZYGANIAŁ KOCIOŁ GARNKOWI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-155', phrase: { en: 'ROME WAS NOT BUILT IN A DAY', pl: 'NIE OD RAZU KRAKÓW ZBUDOWANO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-156', phrase: { en: 'KNOWLEDGE IS WEALTH', pl: 'WIEDZA TO SKARB' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-157', phrase: { en: 'THE BEST THINGS IN LIFE ARE FREE', pl: 'NAJLEPSZE RZECZY SĄ ZA DARMO' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-158', phrase: { en: 'THE EARLY BIRD CATCHES THE WORM', pl: 'KTO RANO WSTAJE TEMU PAN BÓG DAJE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-159', phrase: { en: 'THE GRASS IS ALWAYS GREENER', pl: 'WSZĘDZIE DOBRZE GDZIE NAS NIE MA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-160', phrase: { en: 'THE PEN IS MIGHTIER THAN THE SWORD', pl: 'PIÓRO JEST SILNIEJSZE OD MIECZA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-161', phrase: { en: 'THE SHOW MUST GO ON', pl: 'PRZEDSTAWIENIE MUSI TRWAĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-162', phrase: { en: 'THERE IS NO PLACE LIKE HOME', pl: 'NIE MA JAK W DOMU' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-163', phrase: { en: 'TIME FLIES WHEN YOU ARE HAVING FUN', pl: 'SZCZĘŚLIWI CZASU NIE LICZĄ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-164', phrase: { en: 'TO ERR IS HUMAN', pl: 'BŁĄDZIĆ JEST RZECZĄ LUDZKĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-165', phrase: { en: 'TOO MANY COOKS SPOIL THE BROTH', pl: 'GDZIE KUCHAREK SZEŚĆ TAM NIE MA CO JEŚĆ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-166', phrase: { en: 'TWO WRONGS DO NOT MAKE A RIGHT', pl: 'ZŁO DOBREM ZWYCIĘŻAJ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-167', phrase: { en: 'SILENCE IS GOLDEN', pl: 'MILCZENIE JEST ZŁOTEM' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-168', phrase: { en: 'WASTE NOT WANT NOT', pl: 'OSZCZĘDNOŚCIĄ I PRACĄ LUDZIE SIĘ BOGACĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-169', phrase: { en: 'WHAT GOES AROUND COMES AROUND', pl: 'KARMA WRACA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-170', phrase: { en: 'WHEN IN ROME', pl: 'MIĘDZY WRONAMI KRAKAJ JAK I ONE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-171', phrase: { en: 'WAKE UP AND SMELL THE COFFEE', pl: 'PRZEJRZYJ NA OCZY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-172', phrase: { en: 'BACK TO SQUARE ONE', pl: 'WRÓCIĆ DO PUNKTU WYJŚCIA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-173', phrase: { en: 'BITE THE HAND THAT FEEDS YOU', pl: 'GRYŹĆ RĘKĘ KTÓRA CIĘ KARMI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-174', phrase: { en: 'BURN THE CANDLE AT BOTH ENDS', pl: 'ZAHAROWYWAĆ SIĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-175', phrase: { en: 'CATCH SOMEONE RED HANDED', pl: 'ZŁAPAĆ KOGOŚ NA GORĄCYM UCZYNKU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-177', phrase: { en: 'HAVE A CHIP ON YOUR SHOULDER', pl: 'MIEĆ ŻAL DO CAŁEGO ŚWIATA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-178', phrase: { en: 'JUMP THE GUN', pl: 'WYRWAĆ SIĘ PRZED SZEREG' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-179', phrase: { en: 'KEEP YOUR HAIR ON', pl: 'NIE GORĄCZKUJ SIĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-180', phrase: { en: 'LET OFF STEAM', pl: 'WYŁADOWAĆ SIĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-181', phrase: { en: 'ONCE BITTEN TWICE SHY', pl: 'KTO SIĘ RAZ SPARZY TEN NA ZIMNE DMUCHA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-182', phrase: { en: 'PULL YOURSELF TOGETHER', pl: 'WEŹ SIĘ W GARŚĆ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-183', phrase: { en: 'PUT YOUR FOOT IN IT', pl: 'PALNĄĆ GŁUPSTWO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-184', phrase: { en: 'SPILL THE BEANS', pl: 'WYPUŚCIĆ FARBĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-185', phrase: { en: 'TAKE THE BULL BY THE HORNS', pl: 'ZŁAPAĆ BYKA ZA ROGI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-186', phrase: { en: 'THROUGH THE GRAPEVINE', pl: 'POCZTĄ PANTOFLOWĄ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-187', phrase: { en: 'UNDER THE THUMB', pl: 'POD PANTOFLEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-188', phrase: { en: 'UP IN THE AIR', pl: 'SPRAWA JEST OTWARTA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-189', phrase: { en: 'WATER UNDER THE BRIDGE', pl: 'BYŁO MINĘŁO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-190', phrase: { en: 'WHEN THE CATS AWAY', pl: 'GDY KOTA NIE MA MYSZY HARCUJĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-191', phrase: { en: 'A FISH OUT OF WATER', pl: 'CZUĆ SIĘ NIESWOJO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-194', phrase: { en: 'BURNING THE MIDNIGHT OIL', pl: 'ŚLĘCZEĆ PO NOCACH' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-195', phrase: { en: 'CRYING OVER SPILLED MILK', pl: 'PŁAKAĆ NAD ROZLANYM MLEKIEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-197', phrase: { en: 'DRIVING ME UP THE WALL', pl: 'DOPROWADZAĆ DO SZAŁU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-199', phrase: { en: 'GETTING A TASTE OF YOUR OWN MEDICINE', pl: 'ODPŁACIĆ PIĘKNYM ZA NADOBNE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-200', phrase: { en: 'HITTING THE NAIL ON THE HEAD', pl: 'TRAFIĆ W DZIESIĄTKĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
    ],
};

export const PACKS: Record<string, PuzzlePack> = { all };

export function getPack(id: string = 'all'): PuzzlePack {
    return PACKS[id] ?? all;
}
