// Bilingual puzzle content for "The Wheel".

export interface LocalizedString {
    en: string;
    pl: string;
}

export interface PuzzleContent {
    id: string;
    phrase: LocalizedString;
    category: LocalizedString;
}

export interface PuzzlePack {
    id: string;
    puzzles: PuzzleContent[];
}

const all: PuzzlePack = {
    id: 'all',
    puzzles: [
        { id: 'wheel-001', phrase: { en: 'BETTER LATE THAN NEVER', pl: 'LEPIEJ PÓŹNO NIŻ WCALE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-002', phrase: { en: 'THE EARLY BIRD', pl: 'RANNY PTASZEK' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-003', phrase: { en: 'PIECE OF CAKE', pl: 'BUŁKA Z MASŁEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-004', phrase: { en: 'BREAK A LEG', pl: 'POŁAMANIA NÓG' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-005', phrase: { en: 'OLD HABITS DIE HARD', pl: 'STARE NAWYKI TRUDNO WYKORZENIĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-006', phrase: { en: 'TIME IS MONEY', pl: 'CZAS TO PIENIĄDZ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-007', phrase: { en: 'ACTIONS SPEAK LOUDER THAN WORDS', pl: 'PO CZYNACH ICH POZNACIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-008', phrase: { en: 'ONCE IN A BLUE MOON', pl: 'RAZ NA RUSKI ROK' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-009', phrase: { en: 'KNOWLEDGE IS POWER', pl: 'WIEDZA TO POTĘGA' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-010', phrase: { en: 'EVERY CLOUD HAS A SILVER LINING', pl: 'NIE MA TEGO ZŁEGO, CO BY NA DOBRE NIE WYSZŁO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-011', phrase: { en: 'THE APPLE DOES NOT FALL FAR FROM THE TREE', pl: 'NIEDALEKO PADA JABŁKO OD JABŁONI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-012', phrase: { en: 'BITING OFF MORE THAN YOU CAN CHEW', pl: 'PORWAĆ SIĘ Z MOTYKĄ NA SŁOŃCE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-013', phrase: { en: 'DON\'T JUDGE A BOOK BY ITS COVER', pl: 'NIE OCENIAJ KSIĄŻKI PO OKŁADCE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-014', phrase: { en: 'PRACTICE MAKES PERFECT', pl: 'TRENING CZYNI MISTRZA' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-015', phrase: { en: 'OUT OF SIGHT OUT OF MIND', pl: 'CO Z OCZU, TO Z SERCA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-016', phrase: { en: 'A PICTURE IS WORTH A THOUSAND WORDS', pl: 'JEDEN OBRAZ WART WIĘCEJ NIŻ TYSIĄC SŁÓW' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-017', phrase: { en: 'LET THE CAT OUT OF THE BAG', pl: 'WYGADAĆ SEKRET' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-018', phrase: { en: 'BEAT AROUND THE BUSH', pl: 'OWIJAĆ W BAWEŁNĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-019', phrase: { en: 'CURIOSITY KILLED THE CAT', pl: 'CIEKAWOŚĆ TO PIERWSZY STOPIEŃ DO PIEKŁA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-020', phrase: { en: 'NO PAIN NO GAIN', pl: 'BEZ PRACY NIE MA KOŁACZY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-021', phrase: { en: 'BIRDS OF A FEATHER FLOCK TOGETHER', pl: 'CIĄGNIE SWÓJ DO SWEGO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-022', phrase: { en: 'ROME WASN\'T BUILT IN A DAY', pl: 'NIE OD RAZU KRAKÓW ZBUDOWANO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-023', phrase: { en: 'EASY COME EASY GO', pl: 'ŁATWO PRZYSZŁO, ŁATWO POSZŁO' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-024', phrase: { en: 'THROUGH THICK AND THIN', pl: 'NA DOBRE I NA ZŁE' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-025', phrase: { en: 'HIT THE NAIL ON THE HEAD', pl: 'TRAFIĆ W SEDNO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-026', phrase: { en: 'BETTER SAFE THAN SORRY', pl: 'STRZEŻONEGO PAN BÓG STRZEŻE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-027', phrase: { en: 'OUT OF THE BLUE', pl: 'Z NIENACKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-028', phrase: { en: 'BREAK THE ICE', pl: 'PRZEŁAMAĆ LODY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-029', phrase: { en: 'A DIAMOND IN THE ROUGH', pl: 'NIEOSZLIFOWANY DIAMENT' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-030', phrase: { en: 'BITE THE BULLET', pl: 'ZACISNĄĆ ZĘBY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-031', phrase: { en: 'BLOOD IS THICKER THAN WATER', pl: 'KREW NIE WODA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-032', phrase: { en: 'ALL THAT GLITTERS IS NOT GOLD', pl: 'NIE WSZYSTKO ZŁOTO, CO SIĘ ŚWIECI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-033', phrase: { en: 'BETWEEN A ROCK AND A HARD PLACE', pl: 'MIĘDZY MŁOTEM A KOWADŁEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-034', phrase: { en: 'EVERYTHING COMES TO AN END', pl: 'WSZYSTKO KIEDYŚ SIĘ KOŃCZY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-035', phrase: { en: 'FORGIVE AND FORGET', pl: 'WYBACZYĆ I ZAPOMNIEĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-036', phrase: { en: 'GET COLD FEET', pl: 'STCHÓRZYĆ W OSTATNIEJ CHWILI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-037', phrase: { en: 'IN THE LONG RUN', pl: 'NA DŁUŻSZĄ METĘ' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-038', phrase: { en: 'KEEP AN EYE ON', pl: 'MIEĆ NA OKU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-039', phrase: { en: 'LAST BUT NOT LEAST', pl: 'OSTATNI, ALE NIE MNIEJ WAŻNY' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-040', phrase: { en: 'MAKE A LONG STORY SHORT', pl: 'MÓWIĄC W SKRÓCIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-041', phrase: { en: 'NEVER SAY NEVER', pl: 'NIGDY NIE MÓW NIGDY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-042', phrase: { en: 'ON TOP OF THE WORLD', pl: 'W SIÓDMYM NIEBIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-043', phrase: { en: 'POINT OF VIEW', pl: 'PUNKT WIDZENIA' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-044', phrase: { en: 'RAIN OR SHINE', pl: 'BEZ WZGLĘDU NA POGODĘ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-045', phrase: { en: 'SO FAR SO GOOD', pl: 'JAK NA RAZIE JEST DOBRZE' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-046', phrase: { en: 'THE SKY IS THE LIMIT', pl: 'WSZYSTKO JEST MOŻLIWE' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-047', phrase: { en: 'UNDER YOUR NOSE', pl: 'POD NOSEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-048', phrase: { en: 'UP TO DATE', pl: 'NA BIEŻĄCO' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-049', phrase: { en: 'WORK IN PROGRESS', pl: 'PRACA W TOKU' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-050', phrase: { en: 'ZIP YOUR LIP', pl: 'TRZYMAJ JĘZYK ZA ZĘBAMI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-051', phrase: { en: 'ADD FUEL TO THE FIRE', pl: 'DOLEWAĆ OLIWY DO OGNIA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-052', phrase: { en: 'DRAW A BLANK', pl: 'MIEĆ PUSTKĘ W GŁOWIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-053', phrase: { en: 'CALL IT A DAY', pl: 'SKOŃCZYĆ NA DZIŚ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-054', phrase: { en: 'CUT TO THE CHASE', pl: 'PRZEJŚĆ DO RZECZY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-055', phrase: { en: 'GET OUT OF HAND', pl: 'WYMKNĄĆ SIĘ SPOD KONTROLI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-056', phrase: { en: 'HANG IN THERE', pl: 'TRZYMAJ SIĘ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-057', phrase: { en: 'IT IS NOT ROCKET SCIENCE', pl: 'TO NIE ŻADNA FILOZOFIA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-058', phrase: { en: 'LET SOMEONE OFF THE HOOK', pl: 'PUŚCIĆ KOMUŚ PŁAZEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-059', phrase: { en: 'MISS THE BOAT', pl: 'PRZEGAPIĆ OKAZJĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-060', phrase: { en: 'ON THE BALL', pl: 'TRZYMAĆ RĘKĘ NA PULSIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-061', phrase: { en: 'PULL SOMEONE\'S LEG', pl: 'ROBIĆ KOGOŚ W BALONA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-062', phrase: { en: 'SEE EYE TO EYE', pl: 'MIEĆ TAKIE SAMO ZDANIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-063', phrase: { en: 'SPEAK OF THE DEVIL', pl: 'O WILKU MOWA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-064', phrase: { en: 'TAKE IT WITH A GRAIN OF SALT', pl: 'TRAKTOWAĆ COŚ Z PRZYMRUŻENIEM OKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-065', phrase: { en: 'THE LAST STRAW', pl: 'KROPLA, KTÓRA PRZELAŁA CZARĘ GORYCZY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-066', phrase: { en: 'UNDER THE WEATHER', pl: 'CZUĆ SIĘ NIEWYRAŹNIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-067', phrase: { en: 'WE WILL CROSS THAT BRIDGE WHEN WE COME TO IT', pl: 'NIE MARTWMY SIĘ NA ZAPAS' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-068', phrase: { en: 'WRAP YOUR HEAD AROUND IT', pl: 'OGARNĄĆ COŚ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-069', phrase: { en: 'YOU CAN SAY THAT AGAIN', pl: 'ŚWIĘTA RACJA' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-070', phrase: { en: 'YOUR GUESS IS AS GOOD AS MINE', pl: 'WIEM TYLE SAMO CO TY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-071', phrase: { en: 'A BIRD IN THE HAND IS WORTH TWO IN THE BUSH', pl: 'LEPSZY WRÓBEL W GARŚCI NIŻ GOŁĄB NA DACHU' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-072', phrase: { en: 'READ SOMEONE\'S MIND', pl: 'CZYTAĆ KOMUŚ W MYŚLACH' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-073', phrase: { en: 'A PERFECT STORM', pl: 'KUMULACJA NIESZCZĘŚĆ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-074', phrase: { en: 'A TASTE OF YOUR OWN MEDICINE', pl: 'ODPŁACIĆ PIĘKNYM ZA NADOBNE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-075', phrase: { en: 'BEATING A DEAD HORSE', pl: 'WAŁKOWAĆ TEMAT BEZ KOŃCA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-076', phrase: { en: 'HIT THE JACKPOT', pl: 'ROZBIĆ BANK' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-077', phrase: { en: 'BURN BRIDGES', pl: 'PALIĆ MOSTY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-078', phrase: { en: 'BY THE SKIN OF YOUR TEETH', pl: 'O MAŁY WŁOS' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-079', phrase: { en: 'COMPARING APPLES TO ORANGES', pl: 'PORÓWNYWAĆ JABŁKA Z GRUSZKAMI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-080', phrase: { en: 'CUT SOMEONE SOME SLACK', pl: 'DAĆ KOMUŚ TARYFĘ ULGOWĄ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-081', phrase: { en: 'AT THE DROP OF A HAT', pl: 'BEZ CHWILI NAMYSŁU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-082', phrase: { en: 'DON\'T COUNT YOUR CHICKENS BEFORE THEY HATCH', pl: 'NIE CHWAL DNIA PRZED ZACHODEM SŁOŃCA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-083', phrase: { en: 'DON\'T GET YOUR HOPES UP', pl: 'NIE RÓB SOBIE NADZIEI' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-084', phrase: { en: 'DON\'T PUT ALL YOUR EGGS IN ONE BASKET', pl: 'NIE STAWIAJ WSZYSTKIEGO NA JEDNĄ KARTĘ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-085', phrase: { en: 'EVERY DOG HAS ITS DAY', pl: 'KAŻDY MA SWOJE PIĘĆ MINUT' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-086', phrase: { en: 'NOTHING VENTURED NOTHING GAINED', pl: 'KTO NIE RYZYKUJE, TEN NIE PIJE SZAMPANA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-087', phrase: { en: 'EASIER SAID THAN DONE', pl: 'ŁATWIEJ POWIEDZIEĆ NIŻ ZROBIĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-088', phrase: { en: 'GET SOMETHING OUT OF YOUR SYSTEM', pl: 'WYRZUCIĆ COŚ Z SIEBIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-089', phrase: { en: 'GIVE SOMEONE THE BENEFIT OF THE DOUBT', pl: 'DAĆ KOMUŚ KREDYT ZAUFANIA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-090', phrase: { en: 'GIVE SOMEONE THE COLD SHOULDER', pl: 'POTRAKTOWAĆ KOGOŚ CHŁODNO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-091', phrase: { en: 'GOOD THINGS COME TO THOSE WHO WAIT', pl: 'CIERPLIWOŚĆ JEST CNOTĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-092', phrase: { en: 'HE HAS BIGGER FISH TO FRY', pl: 'MA WAŻNIEJSZE SPRAWY NA GŁOWIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-093', phrase: { en: 'HIT THE SACK', pl: 'UDAĆ SIĘ NA SPOCZYNEK' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-094', phrase: { en: 'IGNORANCE IS BLISS', pl: 'NIEWIEDZA JEST BŁOGOSŁAWIEŃSTWEM' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-095', phrase: { en: 'IT TAKES TWO TO TANGO', pl: 'DO TANGA TRZEBA DWOJGA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-096', phrase: { en: 'JUMP ON THE BANDWAGON', pl: 'PŁYNĄĆ Z PRĄDEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-097', phrase: { en: 'KEEP YOUR CHIN UP', pl: 'GŁOWA DO GÓRY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-098', phrase: { en: 'LEAVE NO STONE UNTURNED', pl: 'PORUSZYĆ NIEBO I ZIEMIĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-099', phrase: { en: 'LET SLEEPING DOGS LIE', pl: 'NIE WYWOŁUJ WILKA Z LASU' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-100', phrase: { en: 'LIVE AND LEARN', pl: 'CZŁOWIEK UCZY SIĘ CAŁE ŻYCIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-101', phrase: { en: 'METHOD TO MY MADNESS', pl: 'W TYM SZALEŃSTWIE JEST METODA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-102', phrase: { en: 'NOT MY CUP OF TEA', pl: 'TO NIE MOJA BAJKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-103', phrase: { en: 'OFF THE TOP OF MY HEAD', pl: 'PIERWSZE, CO PRZYCHODZI MI DO GŁOWY' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-104', phrase: { en: 'ON THE TIP OF MY TONGUE', pl: 'NA KOŃCU JĘZYKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-105', phrase: { en: 'PRACTICE WHAT YOU PREACH', pl: 'POSTĘPUJ ZGODNIE Z TYM, CO GŁOSISZ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-106', phrase: { en: 'SIT ON THE FENCE', pl: 'NIE ZAJMOWAĆ STANOWISKA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-107', phrase: { en: 'SKELETON IN THE CLOSET', pl: 'TRUP W SZAFIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-108', phrase: { en: 'MIX BUSINESS WITH PLEASURE', pl: 'ŁĄCZYĆ PRZYJEMNE Z POŻYTECZNYM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-109', phrase: { en: 'THE WHOLE NINE YARDS', pl: 'NA CAŁEGO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-110', phrase: { en: 'TO BE IN THE SAME BOAT', pl: 'JECHAĆ NA TYM SAMYM WÓZKU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-111', phrase: { en: 'TO KILL TIME', pl: 'ZABIJAĆ CZAS' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-112', phrase: { en: 'WHEN PIGS FLY', pl: 'JAK MI KAKTUS NA DŁONI WYROŚNIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-113', phrase: { en: 'A CHIP ON THE SHOULDER', pl: 'MIEĆ ŻAL DO ŚWIATA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-114', phrase: { en: 'A LEOPARD CAN\'T CHANGE ITS SPOTS', pl: 'NATURY NIE OSZUKASZ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-115', phrase: { en: 'BURN THE MIDNIGHT OIL', pl: 'ŚLĘCZEĆ PO NOCACH' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-116', phrase: { en: 'DO UNTO OTHERS AS YOU WOULD HAVE THEM DO UNTO YOU', pl: 'NIE CZYŃ DRUGIEMU, CO TOBIE NIEMIŁE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-117', phrase: { en: 'DRIVE SOMEONE UP THE WALL', pl: 'DOPROWADZAĆ KOGOŚ DO SZAŁU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-118', phrase: { en: 'KEEP YOUR FINGERS CROSSED', pl: 'TRZYMAĆ KCIUKI' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-119', phrase: { en: 'STEAL SOMEONE\'S THUNDER', pl: 'PRZYĆMIĆ CZYJŚ SUKCES' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-120', phrase: { en: 'THE BALL IS IN YOUR COURT', pl: 'PIŁECZKA JEST PO TWOJEJ STRONIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-121', phrase: { en: 'OLD LOVE NEVER DIES', pl: 'STARA MIŁOŚĆ NIE RDZEWIEJE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-122', phrase: { en: 'BEAUTY IS IN THE EYE OF THE BEHOLDER', pl: 'PIĘKNO JEST RZECZĄ WZGLĘDNĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-123', phrase: { en: 'EVERY ROSE HAS ITS THORN', pl: 'NIE MA RÓŻY BEZ KOLCÓW' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-124', phrase: { en: 'DON\'T BITE THE HAND THAT FEEDS YOU', pl: 'NIE GRYŹ RĘKI, KTÓRA CIĘ KARMI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-125', phrase: { en: 'GOOD THINGS COME IN SMALL PACKAGES', pl: 'MAŁE JEST PIĘKNE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-126', phrase: { en: 'CLOTHES DO NOT MAKE THE MAN', pl: 'NIE SZATA ZDOBI CZŁOWIEKA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-127', phrase: { en: 'NO NEWS IS GOOD NEWS', pl: 'BRAK WIADOMOŚCI TO DOBRA WIADOMOŚĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-128', phrase: { en: 'OUT OF THE FRYING PAN INTO THE FIRE', pl: 'Z DESZCZU POD RYNNĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-129', phrase: { en: 'SLOW AND STEADY WINS THE RACE', pl: 'SPIESZ SIĘ POWOLI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-130', phrase: { en: 'TWO HEADS ARE BETTER THAN ONE', pl: 'CO DWIE GŁOWY, TO NIE JEDNA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-131', phrase: { en: 'WHEN IN ROME DO AS THE ROMANS DO', pl: 'JEŚLI WEJDZIESZ MIĘDZY WRONY, MUSISZ KRAKAĆ JAK I ONE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-132', phrase: { en: 'WHERE THERE IS SMOKE THERE IS FIRE', pl: 'NIE MA DYMU BEZ OGNIA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-133', phrase: { en: 'YOU REAP WHAT YOU SOW', pl: 'CO ZASIEJESZ, TO ZBIERZESZ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-134', phrase: { en: 'A STITCH IN TIME SAVES NINE', pl: 'LEPIEJ ZAPOBIEGAĆ NIŻ LECZYĆ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-135', phrase: { en: 'THE MORE THE MERRIER', pl: 'IM WIĘCEJ, TYM WESELEJ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-136', phrase: { en: 'A PENNY SAVED IS A PENNY EARNED', pl: 'GROSZ DO GROSZA, A BĘDZIE KOKOSZA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-140', phrase: { en: 'FORTUNE FAVORS THE BOLD', pl: 'DO ODWAŻNYCH ŚWIAT NALEŻY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-141', phrase: { en: 'HONESTY IS THE BEST POLICY', pl: 'UCZCIWOŚĆ POPŁACA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-142', phrase: { en: 'IF AT FIRST YOU DON\'T SUCCEED TRY TRY AGAIN', pl: 'DO TRZECH RAZY SZTUKA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-143', phrase: { en: 'LOOK BEFORE YOU LEAP', pl: 'NAJPIERW POMYŚL, POTEM DZIAŁAJ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-144', phrase: { en: 'WHERE THERE IS A WILL THERE IS A WAY', pl: 'DLA CHCĄCEGO NIC TRUDNEGO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-146', phrase: { en: 'LOVE IS BLIND', pl: 'MIŁOŚĆ JEST ŚLEPA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-147', phrase: { en: 'GREAT MINDS THINK ALIKE', pl: 'WIELKIE UMYSŁY MYŚLĄ PODOBNIE' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-148', phrase: { en: 'A HOUSE IS NOT A HOME', pl: 'DOM TO NIE TYLKO ŚCIANY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-149', phrase: { en: 'TIME IS A GREAT HEALER', pl: 'CZAS LECZY RANY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-150', phrase: { en: 'STRIKE WHILE THE IRON IS HOT', pl: 'KUJ ŻELAZO, PÓKI GORĄCE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-151', phrase: { en: 'KEEP YOUR EYES ON THE PRIZE', pl: 'SKUP SIĘ NA CELU' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-152', phrase: { en: 'DON\'T CRY OVER SPILLED MILK', pl: 'NIE PŁACZ NAD ROZLANYM MLEKIEM' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-153', phrase: { en: 'THE DEVIL IS IN THE DETAILS', pl: 'DIABEŁ TKWI W SZCZEGÓŁACH' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-154', phrase: { en: 'PEOPLE WHO LIVE IN GLASS HOUSES SHOULD NOT THROW STONES', pl: 'PRZYGANIAŁ KOCIOŁ GARNKOWI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-155', phrase: { en: 'YOU CAN\'T HAVE YOUR CAKE AND EAT IT TOO', pl: 'NIE MOŻNA MIEĆ CIASTKA I ZJEŚĆ CIASTKA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-156', phrase: { en: 'EVERY COIN HAS TWO SIDES', pl: 'KAŻDY MEDAL MA DWIE STRONY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-157', phrase: { en: 'THE BEST THINGS IN LIFE ARE FREE', pl: 'NAJLEPSZE RZECZY SĄ ZA DARMO' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-158', phrase: { en: 'WHAT DOESN\'T KILL YOU MAKES YOU STRONGER', pl: 'CO CIĘ NIE ZABIJE, TO CIĘ WZMOCNI' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-159', phrase: { en: 'THE GRASS IS ALWAYS GREENER ON THE OTHER SIDE', pl: 'WSZĘDZIE DOBRZE, GDZIE NAS NIE MA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-160', phrase: { en: 'THE PEN IS MIGHTIER THAN THE SWORD', pl: 'PIÓRO JEST SILNIEJSZE OD MIECZA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-161', phrase: { en: 'THE SHOW MUST GO ON', pl: 'PRZEDSTAWIENIE MUSI TRWAĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-162', phrase: { en: 'THERE IS NO PLACE LIKE HOME', pl: 'NIE MA JAK W DOMU' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-163', phrase: { en: 'TIME FLIES WHEN YOU ARE HAVING FUN', pl: 'SZCZĘŚLIWI CZASU NIE LICZĄ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-164', phrase: { en: 'TO ERR IS HUMAN', pl: 'BŁĄDZIĆ JEST RZECZĄ LUDZKĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-165', phrase: { en: 'TOO MANY COOKS SPOIL THE BROTH', pl: 'GDZIE KUCHAREK SZEŚĆ, TAM NIE MA CO JEŚĆ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-166', phrase: { en: 'TWO WRONGS DO NOT MAKE A RIGHT', pl: 'ZŁA NIE NAPRAWIA SIĘ ZŁEM' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-167', phrase: { en: 'SILENCE IS GOLDEN', pl: 'MILCZENIE JEST ZŁOTEM' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-168', phrase: { en: 'WASTE NOT WANT NOT', pl: 'KTO OSZCZĘDZA, TEN NIE BIEDUJE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-169', phrase: { en: 'ON THE SAME WAVELENGTH', pl: 'NADAWAĆ NA TYCH SAMYCH FALACH' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-170', phrase: { en: 'ALL ROADS LEAD TO ROME', pl: 'WSZYSTKIE DROGI PROWADZĄ DO RZYMU' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-171', phrase: { en: 'WAKE UP AND SMELL THE COFFEE', pl: 'PRZEJRZYJ NA OCZY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-172', phrase: { en: 'BACK TO SQUARE ONE', pl: 'WRÓCIĆ DO PUNKTU WYJŚCIA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-173', phrase: { en: 'A DROWNING MAN WILL CLUTCH AT A STRAW', pl: 'TONĄCY BRZYTWY SIĘ CHWYTA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-174', phrase: { en: 'BURN THE CANDLE AT BOTH ENDS', pl: 'ZAHAROWYWAĆ SIĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-175', phrase: { en: 'CATCH SOMEONE RED HANDED', pl: 'ZŁAPAĆ KOGOŚ NA GORĄCYM UCZYNKU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-177', phrase: { en: 'EVERY MAN IS THE ARCHITECT OF HIS OWN FORTUNE', pl: 'KAŻDY JEST KOWALEM SWOJEGO LOSU' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-178', phrase: { en: 'JUMP THE GUN', pl: 'WYRWAĆ SIĘ PRZED SZEREG' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-179', phrase: { en: 'KEEP YOUR HAIR ON', pl: 'NIE GORĄCZKUJ SIĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-180', phrase: { en: 'PLAY IT BY EAR', pl: 'DZIAŁAĆ NA WYCZUCIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-181', phrase: { en: 'ONCE BITTEN TWICE SHY', pl: 'KTO SIĘ RAZ SPARZY, TEN NA ZIMNE DMUCHA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-182', phrase: { en: 'PULL YOURSELF TOGETHER', pl: 'WEŹ SIĘ W GARŚĆ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-183', phrase: { en: 'PUT YOUR FOOT IN IT', pl: 'PALNĄĆ GŁUPSTWO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-184', phrase: { en: 'CALL THE SHOTS', pl: 'ROZDAWAĆ KARTY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-185', phrase: { en: 'TAKE THE BULL BY THE HORNS', pl: 'ZŁAPAĆ BYKA ZA ROGI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-186', phrase: { en: 'THROUGH THE GRAPEVINE', pl: 'POCZTĄ PANTOFLOWĄ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-187', phrase: { en: 'UNDER THE THUMB', pl: 'POD PANTOFLEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-188', phrase: { en: 'UP IN THE AIR', pl: 'SPRAWA JEST OTWARTA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-189', phrase: { en: 'WATER UNDER THE BRIDGE', pl: 'BYŁO, MINĘŁO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-190', phrase: { en: 'WHEN THE CAT\'S AWAY THE MICE WILL PLAY', pl: 'GDY KOTA NIE MA, MYSZY HARCUJĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-191', phrase: { en: 'A FISH OUT OF WATER', pl: 'CZUĆ SIĘ NIESWOJO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-194', phrase: { en: 'A CHAIN IS ONLY AS STRONG AS ITS WEAKEST LINK', pl: 'ŁAŃCUCH JEST TAK SILNY JAK JEGO NAJSŁABSZE OGNIWO' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-195', phrase: { en: 'THE EXCEPTION PROVES THE RULE', pl: 'WYJĄTEK POTWIERDZA REGUŁĘ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-197', phrase: { en: 'THE CUSTOMER IS ALWAYS RIGHT', pl: 'KLIENT MA ZAWSZE RACJĘ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-199', phrase: { en: 'A BAD WORKMAN BLAMES HIS TOOLS', pl: 'ZŁEJ BALETNICY PRZESZKADZA RĄBEK U SPÓDNICY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-200', phrase: { en: 'LESS IS MORE', pl: 'MNIEJ ZNACZY WIĘCEJ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-201', phrase: { en: 'THE END JUSTIFIES THE MEANS', pl: 'CEL UŚWIĘCA ŚRODKI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-202', phrase: { en: 'NECESSITY IS THE MOTHER OF INVENTION', pl: 'POTRZEBA JEST MATKĄ WYNALAZKÓW' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-203', phrase: { en: 'A FRIEND IN NEED IS A FRIEND INDEED', pl: 'PRAWDZIWYCH PRZYJACIÓŁ POZNAJE SIĘ W BIEDZIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-204', phrase: { en: 'STILL WATERS RUN DEEP', pl: 'CICHA WODA BRZEGI RWIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-205', phrase: { en: 'AN EYE FOR AN EYE', pl: 'OKO ZA OKO' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-206', phrase: { en: 'EYES ARE THE MIRROR OF THE SOUL', pl: 'OCZY SĄ ZWIERCIADŁEM DUSZY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-207', phrase: { en: 'FIRST COME FIRST SERVED', pl: 'KTO PIERWSZY, TEN LEPSZY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-208', phrase: { en: 'HASTE MAKES WASTE', pl: 'CO NAGLE, TO PO DIABLE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-209', phrase: { en: 'EVERYTHING IN MODERATION', pl: 'CO ZA DUŻO, TO NIEZDROWO' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-210', phrase: { en: 'MONEY DOES NOT GROW ON TREES', pl: 'PIENIĄDZE NIE SPADAJĄ Z NIEBA' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-211', phrase: { en: 'BARKING DOGS SELDOM BITE', pl: 'PIES, KTÓRY SZCZEKA, NIE GRYZIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-212', phrase: { en: 'ONE SWALLOW DOES NOT MAKE A SUMMER', pl: 'JEDNA JASKÓŁKA WIOSNY NIE CZYNI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-213', phrase: { en: 'A LIE HAS SHORT LEGS', pl: 'KŁAMSTWO MA KRÓTKIE NOGI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-214', phrase: { en: 'EVERYTHING HAS ITS PRICE', pl: 'WSZYSTKO MA SWOJĄ CENĘ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-215', phrase: { en: 'HOPE DIES LAST', pl: 'NADZIEJA UMIERA OSTATNIA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-216', phrase: { en: 'THE WALLS HAVE EARS', pl: 'ŚCIANY MAJĄ USZY' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-217', phrase: { en: 'THERE IS NO ACCOUNTING FOR TASTE', pl: 'O GUSTACH SIĘ NIE DYSKUTUJE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-218', phrase: { en: 'AS YOU MAKE YOUR BED SO YOU MUST LIE IN IT', pl: 'JAK SOBIE POŚCIELESZ, TAK SIĘ WYŚPISZ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-219', phrase: { en: 'FIGHT FIRE WITH FIRE', pl: 'KLIN KLINEM WYBIJAĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-220', phrase: { en: 'LAUGHTER IS THE BEST MEDICINE', pl: 'ŚMIECH TO ZDROWIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-221', phrase: { en: 'NEVER PUT OFF UNTIL TOMORROW WHAT YOU CAN DO TODAY', pl: 'CO MASZ ZROBIĆ JUTRO, ZRÓB DZIŚ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-222', phrase: { en: 'DO NOT BUY A PIG IN A POKE', pl: 'NIE KUPUJ KOTA W WORKU' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-223', phrase: { en: 'THE FIRST STEP IS THE HARDEST', pl: 'NAJTRUDNIEJSZY JEST PIERWSZY KROK' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-224', phrase: { en: 'THERE IS NO SUCH THING AS A FREE LUNCH', pl: 'NIE MA NIC ZA DARMO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-225', phrase: { en: 'HE WHO LAUGHS LAST LAUGHS BEST', pl: 'TEN SIĘ ŚMIEJE, KTO SIĘ ŚMIEJE OSTATNI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-226', phrase: { en: 'LIGHTNING NEVER STRIKES THE SAME PLACE TWICE', pl: 'PIORUN NIE UDERZA DWA RAZY W TO SAMO MIEJSCE' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-227', phrase: { en: 'MANY HANDS MAKE LIGHT WORK', pl: 'W GRUPIE SIŁA' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-228', phrase: { en: 'MEASURE TWICE CUT ONCE', pl: 'DWA RAZY MIERZ, RAZ TNIJ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-229', phrase: { en: 'TIME WILL TELL', pl: 'CZAS POKAŻE' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-230', phrase: { en: 'KILL TWO BIRDS WITH ONE STONE', pl: 'UPIEC DWIE PIECZENIE NA JEDNYM OGNIU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-231', phrase: { en: 'NOT MY CIRCUS NOT MY MONKEYS', pl: 'NIE MÓJ CYRK, NIE MOJE MAŁPY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-232', phrase: { en: 'NEVER LOOK A GIFT HORSE IN THE MOUTH', pl: 'DAROWANEMU KONIOWI NIE ZAGLĄDA SIĘ W ZĘBY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-233', phrase: { en: 'FORBIDDEN FRUIT TASTES THE SWEETEST', pl: 'ZAKAZANY OWOC SMAKUJE NAJLEPIEJ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-234', phrase: { en: 'THE ROAD TO HELL IS PAVED WITH GOOD INTENTIONS', pl: 'DOBRYMI CHĘCIAMI PIEKŁO JEST WYBRUKOWANE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-235', phrase: { en: 'AN EMPTY VESSEL MAKES THE MOST NOISE', pl: 'PUSTA BECZKA NAJGŁOŚNIEJ BRZĘCZY' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-236', phrase: { en: 'IT NEVER RAINS BUT IT POURS', pl: 'NIESZCZĘŚCIA CHODZĄ PARAMI' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-237', phrase: { en: 'YOU CANNOT PLEASE EVERYONE', pl: 'JESZCZE SIĘ TAKI NIE URODZIŁ, CO BY WSZYSTKIM DOGODZIŁ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-238', phrase: { en: 'A GOOD NAME IS BETTER THAN RICHES', pl: 'CENNIEJSZE JEST DOBRE IMIĘ NIŻ WIELKIE BOGACTWO' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-239', phrase: { en: 'HE WHO SEEKS SHALL FIND', pl: 'KTO SZUKA, TEN ZNAJDZIE' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-240', phrase: { en: 'A CAT HAS NINE LIVES', pl: 'KOT MA SIEDEM ŻYĆ' }, category: { en: 'Saying', pl: 'Powiedzenie' } },
        { id: 'wheel-241', phrase: { en: 'THROW IN THE TOWEL', pl: 'RZUCIĆ RĘCZNIK' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-242', phrase: { en: 'COST AN ARM AND A LEG', pl: 'KOSZTOWAĆ MAJĄTEK' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-243', phrase: { en: 'A BLESSING IN DISGUISE', pl: 'SZCZĘŚCIE W NIESZCZĘŚCIU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-244', phrase: { en: 'GO THE EXTRA MILE', pl: 'ZROBIĆ WIĘCEJ NIŻ TRZEBA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-245', phrase: { en: 'HIT THE ROAD', pl: 'RUSZAĆ W DROGĘ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-246', phrase: { en: 'IN THE NICK OF TIME', pl: 'W SAM CZAS' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-247', phrase: { en: 'MONEY CAN\'T BUY HAPPINESS', pl: 'PIENIĄDZE SZCZĘŚCIA NIE DAJĄ' }, category: { en: 'Proverb', pl: 'Przysłowie' } },
        { id: 'wheel-248', phrase: { en: 'RAINING CATS AND DOGS', pl: 'LEJE JAK Z CEBRA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-249', phrase: { en: 'READ BETWEEN THE LINES', pl: 'CZYTAĆ MIĘDZY WIERSZAMI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-250', phrase: { en: 'A DROP IN THE OCEAN', pl: 'KROPLA W MORZU POTRZEB' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-251', phrase: { en: 'THE TIP OF THE ICEBERG', pl: 'WIERZCHOŁEK GÓRY LODOWEJ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-252', phrase: { en: 'TIGHTEN YOUR BELT', pl: 'ZACISNĄĆ PASA' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-253', phrase: { en: 'TURN A BLIND EYE', pl: 'PRZYMYKAĆ OKO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-254', phrase: { en: 'WALKING ON THIN ICE', pl: 'STĄPAĆ PO CIENKIM LODZIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-255', phrase: { en: 'A STORM IN A TEACUP', pl: 'BURZA W SZKLANCE WODY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-256', phrase: { en: 'HAVE YOUR HEAD IN THE CLOUDS', pl: 'BUJAĆ W OBŁOKACH' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-257', phrase: { en: 'LIKE TWO PEAS IN A POD', pl: 'PODOBNI JAK DWIE KROPLE WODY' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-258', phrase: { en: 'MAKE ENDS MEET', pl: 'WIĄZAĆ KONIEC Z KOŃCEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-259', phrase: { en: 'NIP IT IN THE BUD', pl: 'ZDUSIĆ W ZARODKU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-260', phrase: { en: 'PLAY WITH FIRE', pl: 'IGRAĆ Z OGNIEM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-261', phrase: { en: 'SLEEP ON IT', pl: 'PRZESPAĆ SIĘ Z TYM' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-262', phrase: { en: 'THE CALM BEFORE THE STORM', pl: 'CISZA PRZED BURZĄ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-263', phrase: { en: 'GO BACK TO YOUR ROOTS', pl: 'WRÓCIĆ DO KORZENI' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-264', phrase: { en: 'TAKE A RAIN CHECK', pl: 'ODŁOŻYĆ COŚ NA PÓŹNIEJ' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-265', phrase: { en: 'ONCE AND FOR ALL', pl: 'RAZ NA ZAWSZE' }, category: { en: 'Phrase', pl: 'Zwrot' } },
        { id: 'wheel-266', phrase: { en: 'PROMISE THE MOON', pl: 'OBIECYWAĆ GRUSZKI NA WIERZBIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-267', phrase: { en: 'FISH IN TROUBLED WATERS', pl: 'ŁOWIĆ RYBY W MĘTNEJ WODZIE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-268', phrase: { en: 'CALL A SPADE A SPADE', pl: 'NAZYWAĆ RZECZY PO IMIENIU' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-269', phrase: { en: 'HAVE A HEART OF GOLD', pl: 'MIEĆ ZŁOTE SERCE' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-270', phrase: { en: 'THROW MONEY DOWN THE DRAIN', pl: 'WYRZUCAĆ PIENIĄDZE W BŁOTO' }, category: { en: 'Idiom', pl: 'Idiom' } },
        { id: 'wheel-271', phrase: { en: 'GREEN AURORA RIPPLING OVER A FROZEN LAKE', pl: 'ZIELONA ZORZA FALUJĄCA NAD ZAMARZNIĘTYM JEZIOREM' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-272', phrase: { en: 'A CUP OF COFFEE AT SUNRISE', pl: 'FILIŻANKA KAWY O WSCHODZIE SŁOŃCA' }, category: { en: 'Thing', pl: 'Rzecz' } },
        { id: 'wheel-273', phrase: { en: 'FRESH BREAD STRAIGHT FROM THE OVEN', pl: 'ŚWIEŻY CHLEB PROSTO Z PIECA' }, category: { en: 'Food', pl: 'Jedzenie' } },
        { id: 'wheel-274', phrase: { en: 'BOOT TRACKS ACROSS FRESH SNOW', pl: 'ŚLADY BUTÓW NA ŚWIEŻYM ŚNIEGU' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-275', phrase: { en: 'HEAVY RAIN DRUMMING ON A TIN ROOF', pl: 'ULEWA BĘBNIĄCA O BLASZANY DACH' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-276', phrase: { en: 'WET SAND BETWEEN YOUR TOES AT LOW TIDE', pl: 'MOKRY PIASEK MIĘDZY PALCAMI PODCZAS ODPŁYWU' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-277', phrase: { en: 'THE SMELL OF FRESHLY CUT GRASS', pl: 'ZAPACH ŚWIEŻO SKOSZONEJ TRAWY' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-278', phrase: { en: 'AN OLD BOOK ON A DUSTY SHELF', pl: 'STARA KSIĄŻKA NA ZAKURZONEJ PÓŁCE' }, category: { en: 'Thing', pl: 'Rzecz' } },
        { id: 'wheel-279', phrase: { en: 'A DELAYED TRAIN AT AN EMPTY PLATFORM', pl: 'OPÓŹNIONY POCIĄG PRZY PUSTYM PERONIE' }, category: { en: 'Thing', pl: 'Rzecz' } },
        { id: 'wheel-280', phrase: { en: 'WARM SOUP ON A COLD DAY', pl: 'CIEPŁA ZUPA W ZIMNY DZIEŃ' }, category: { en: 'Food', pl: 'Jedzenie' } },
        { id: 'wheel-281', phrase: { en: 'A FULL MOON OVER THE LAKE', pl: 'PEŁNIA KSIĘŻYCA NAD JEZIOREM' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-282', phrase: { en: 'A NOISY CLASSROOM ON THE LAST DAY OF SCHOOL', pl: 'GWARNA KLASA W OSTATNI DZIEŃ SZKOŁY' }, category: { en: 'Place', pl: 'Miejsce' } },
        { id: 'wheel-283', phrase: { en: 'A WORN LEATHER ARMCHAIR BY THE BOOKSHELF', pl: 'WYTARTY SKÓRZANY FOTEL PRZY REGALE' }, category: { en: 'Thing', pl: 'Rzecz' } },
        { id: 'wheel-284', phrase: { en: 'A CROWDED MARKET SQUARE ON SATURDAY MORNING', pl: 'ZATŁOCZONY RYNEK W SOBOTNI PORANEK' }, category: { en: 'Place', pl: 'Miejsce' } },
        { id: 'wheel-285', phrase: { en: 'SKIPPING STONES ACROSS A CALM LAKE', pl: 'PUSZCZANIE KACZEK NA SPOKOJNYM JEZIORZE' }, category: { en: 'Activity', pl: 'Czynność' } },
        { id: 'wheel-286', phrase: { en: 'AN OLD CLOCK TICKING IN A QUIET HALL', pl: 'STARY ZEGAR TYKAJĄCY W CICHYM HOLU' }, category: { en: 'Thing', pl: 'Rzecz' } },
        { id: 'wheel-287', phrase: { en: 'A PEACEFUL ROOM WITH A GLOWING HEARTH', pl: 'SPOKOJNY POKÓJ Z ROZPALONYM KOMINKIEM' }, category: { en: 'Place', pl: 'Miejsce' } },
        { id: 'wheel-288', phrase: { en: 'A MOSSY FOOTBRIDGE ABOVE A STREAM', pl: 'OMSZAŁA KŁADKA NAD STRUMIENIEM' }, category: { en: 'Place', pl: 'Miejsce' } },
        { id: 'wheel-289', phrase: { en: 'A WIDE VALLEY SEEN FROM A ROCKY SUMMIT', pl: 'SZEROKA DOLINA WIDZIANA ZE SKALISTEGO SZCZYTU' }, category: { en: 'Place', pl: 'Miejsce' } },
        { id: 'wheel-290', phrase: { en: 'RIPE CHERRIES IN A BLUE BOWL', pl: 'DOJRZAŁE CZEREŚNIE W NIEBIESKIEJ MISCE' }, category: { en: 'Food', pl: 'Jedzenie' } },
        { id: 'wheel-291', phrase: { en: 'SUNLIGHT FILTERING THROUGH FERN LEAVES AFTER RAIN', pl: 'PROMIENIE SŁOŃCA PRZENIKAJĄCE PRZEZ LIŚCIE PAPROCI PO DESZCZU' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-292', phrase: { en: 'STEAM RISING FROM A KETTLE ON A FROSTY MORNING', pl: 'PARA UNOSZĄCA SIĘ Z CZAJNIKA W MROŹNY PORANEK' }, category: { en: 'At Home', pl: 'W domu' } },
        { id: 'wheel-293', phrase: { en: 'BEES HOVERING ABOVE LAVENDER ROWS ON A BRIGHT AFTERNOON', pl: 'PSZCZOŁY UNOSZĄCE SIĘ NAD RZĘDAMI LAWENDY W SŁONECZNE POPOŁUDNIE' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-294', phrase: { en: 'A RAINBOW REFLECTED IN PUDDLES BESIDE A COUNTRY ROAD', pl: 'TĘCZA ODBITA W KAŁUŻACH PRZY WIEJSKIEJ DRODZE' }, category: { en: 'Weather', pl: 'Pogoda' } },
        { id: 'wheel-295', phrase: { en: 'A HEDGEHOG RUSTLING UNDER AUTUMN LEAVES AT DUSK', pl: 'JEŻ SZELESZCZĄCY POD JESIENNYMI LIŚĆMI O ZMIERZCHU' }, category: { en: 'Animal', pl: 'Zwierzę' } },
        { id: 'wheel-296', phrase: { en: 'THREE COLORFUL UMBRELLAS LEFT OPEN TO DRY ON A PORCH', pl: 'TRZY KOLOROWE PARASOLE ZOSTAWIONE OTWARTE DO WYSCHNIĘCIA NA WERANDZIE' }, category: { en: 'At Home', pl: 'W domu' } },
        { id: 'wheel-297', phrase: { en: 'A WOODEN ROWBOAT TIED TO A DOCK AMONG TALL REEDS', pl: 'DREWNIANA ŁÓDŹ WIOSŁOWA PRZYWIĄZANA DO POMOSTU WŚRÓD WYSOKICH TRZCIN' }, category: { en: 'By the Water', pl: 'Nad wodą' } },
        { id: 'wheel-298', phrase: { en: 'SOAP BUBBLES FLOATING ACROSS A SUNNY PLAYGROUND', pl: 'BAŃKI MYDLANE UNOSZĄCE SIĘ NAD SŁONECZNYM PLACEM ZABAW' }, category: { en: 'Playtime', pl: 'Zabawa' } },
        { id: 'wheel-299', phrase: { en: 'A SLEEPY CAT CURLED UP ON FOLDED BLANKETS', pl: 'SENNY KOT ZWINIĘTY W KŁĘBEK NA ZŁOŻONYCH KOCACH' }, category: { en: 'Animal', pl: 'Zwierzę' } },
        { id: 'wheel-300', phrase: { en: 'FIREFLIES GLOWING ABOVE TALL GRASS ON A WARM EVENING', pl: 'ŚWIETLIKI MIGOCZĄCE NAD WYSOKĄ TRAWĄ W CIEPŁY WIECZÓR' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-301', phrase: { en: 'SEA WAVES WASHING SMOOTH PEBBLES ALONG A QUIET SHORE', pl: 'MORSKIE FALE OBMYWAJĄCE GŁADKIE KAMYKI NA SPOKOJNYM BRZEGU' }, category: { en: 'Seaside', pl: 'Nad morzem' } },
        { id: 'wheel-302', phrase: { en: 'A BLUE BICYCLE LEANING AGAINST A BRICK GARDEN WALL', pl: 'NIEBIESKI ROWER OPARTY O CEGLANY MUR W OGRODZIE' }, category: { en: 'Garden', pl: 'Ogród' } },
        { id: 'wheel-303', phrase: { en: 'RAINDROPS ON A SPIDER WEB STRETCHED BETWEEN TWO BRANCHES', pl: 'KROPLE DESZCZU NA PAJĘCZYNIE ROZPIĘTEJ MIĘDZY DWIEMA GAŁĘZIAMI' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-304', phrase: { en: 'PAPER LANTERNS GLOWING ABOVE A LONG TABLE IN THE GARDEN', pl: 'PAPIEROWE LAMPIONY ŚWIECĄCE NAD DŁUGIM STOŁEM W OGRODZIE' }, category: { en: 'Garden', pl: 'Ogród' } },
        { id: 'wheel-305', phrase: { en: 'A FOX PAUSING BESIDE A MISTY FOREST PATH', pl: 'LIS ZATRZYMUJĄCY SIĘ PRZY MGLISTEJ LEŚNEJ ŚCIEŻCE' }, category: { en: 'Animal', pl: 'Zwierzę' } },
        { id: 'wheel-306', phrase: { en: 'FRESH LAUNDRY FLAPPING ON A LINE BEFORE THE STORM', pl: 'ŚWIEŻE PRANIE ŁOPOCZĄCE NA SZNURZE PRZED BURZĄ' }, category: { en: 'Everyday Life', pl: 'Codzienność' } },
        { id: 'wheel-307', phrase: { en: 'A TINY FROG RESTING ON A WATER LILY LEAF', pl: 'MAŁA ŻABKA ODPOCZYWAJĄCA NA LIŚCIU LILII WODNEJ' }, category: { en: 'Animal', pl: 'Zwierzę' } },
        { id: 'wheel-308', phrase: { en: 'PALE BIRCH TRUNKS EMERGING FROM THICK MIST IN A GROVE', pl: 'JASNE PNIE BRZÓZ WYŁANIAJĄCE SIĘ Z GĘSTEJ MGŁY W ZAGAJNIKU' }, category: { en: 'Nature', pl: 'Przyroda' } },
        { id: 'wheel-309', phrase: { en: 'A SMALL COMPASS LYING ON A CREASED HIKING MAP', pl: 'MAŁY KOMPAS LEŻĄCY NA POMIĘTEJ MAPIE SZLAKÓW' }, category: { en: 'Travel', pl: 'Podróże' } },
    ],
};

export const PACKS: Record<string, PuzzlePack> = { all };

export function getPack(id: string = 'all'): PuzzlePack {
    return PACKS[id] ?? all;
}
