"""Provision ShowDown's Game Center config via the App Store Connect API.

Creates (idempotently — GET-first, skip existing):
  - the app's gameCenterDetail
  - 34 achievements + en-US/pl localizations + 512x512 badge images
  - 3 best-score leaderboards + localizations

Run:  .venv-agents/bin/python .agents/game-services/create_game_center.py
Requires: AuthKey_TYBAQ9XDGV.p8 in repo root, images generated by gen_images.py.
"""

import hashlib
import os
import sys
import time

import jwt
import requests

sys.path.insert(0, os.path.dirname(__file__))
from definitions import LEADERBOARDS, achievements  # noqa: E402

KEY_ID = "TYBAQ9XDGV"
ISSUER_ID = "2d8516f5-a643-4741-88a9-28bfe52778fd"
KEY_FILE = "AuthKey_TYBAQ9XDGV.p8"
APP_ID = "6774886649"
BASE = "https://api.appstoreconnect.apple.com"
IMAGES_DIR = os.path.join(os.path.dirname(__file__), "images")
LOCALES = ["en-US", "pl"]  # Apple GC locale ids


def headers():
    now = int(time.time())
    tok = jwt.encode(
        {"iss": ISSUER_ID, "iat": now, "exp": now + 1100, "aud": "appstoreconnect-v1"},
        open(KEY_FILE).read(),
        algorithm="ES256",
        headers={"kid": KEY_ID},
    )
    return {"Authorization": f"Bearer {tok}", "Content-Type": "application/json"}


def die(msg, resp):
    print(f"FATAL: {msg}: {resp.status_code} {resp.text[:500]}")
    sys.exit(1)


def get_all(url, params=None):
    """Follow pagination, return all data items."""
    items = []
    while url:
        r = requests.get(url, headers=headers(), params=params)
        params = None
        if r.status_code != 200:
            die(f"GET {url}", r)
        body = r.json()
        items += body.get("data") or []
        url = (body.get("links") or {}).get("next")
    return items


def ensure_detail():
    r = requests.get(f"{BASE}/v1/apps/{APP_ID}/gameCenterDetail", headers=headers())
    if r.status_code == 200 and r.json().get("data"):
        detail = r.json()["data"]["id"]
        print(f"gameCenterDetail exists: {detail}")
        return detail
    body = {
        "data": {
            "type": "gameCenterDetails",
            "relationships": {"app": {"data": {"type": "apps", "id": APP_ID}}},
        }
    }
    r = requests.post(f"{BASE}/v1/gameCenterDetails", headers=headers(), json=body)
    if r.status_code != 201:
        die("create gameCenterDetail", r)
    detail = r.json()["data"]["id"]
    print(f"created gameCenterDetail: {detail}")
    return detail


def upload_image(localization_id, png_path):
    """Reserve, upload, and commit one achievement image."""
    size = os.path.getsize(png_path)
    body = {
        "data": {
            "type": "gameCenterAchievementImages",
            "attributes": {"fileName": os.path.basename(png_path), "fileSize": size},
            "relationships": {
                "gameCenterAchievementLocalization": {
                    "data": {"type": "gameCenterAchievementLocalizations", "id": localization_id}
                }
            },
        }
    }
    r = requests.post(f"{BASE}/v1/gameCenterAchievementImages", headers=headers(), json=body)
    if r.status_code != 201:
        print(f"  ! image reserve failed: {r.status_code} {r.text[:200]}")
        return False
    asset = r.json()["data"]
    data = open(png_path, "rb").read()
    for op in asset["attributes"]["uploadOperations"]:
        chunk = data[op["offset"] : op["offset"] + op["length"]]
        up_headers = {h["name"]: h["value"] for h in op.get("requestHeaders") or []}
        ur = requests.request(op["method"], op["url"], headers=up_headers, data=chunk)
        if ur.status_code not in (200, 201, 204):
            print(f"  ! image upload failed: {ur.status_code}")
            return False
    # NOTE: only `uploaded` is patchable — sourceFileChecksum is rejected with
    # ENTITY_ERROR.ATTRIBUTE.UNKNOWN on this resource.
    commit = {
        "data": {
            "type": "gameCenterAchievementImages",
            "id": asset["id"],
            "attributes": {"uploaded": True},
        }
    }
    r = requests.patch(
        f"{BASE}/v1/gameCenterAchievementImages/{asset['id']}", headers=headers(), json=commit
    )
    if r.status_code != 200:
        print(f"  ! image commit failed: {r.status_code} {r.text[:200]}")
        return False
    return True


def localization_has_image(localization_id):
    """True when a COMPLETE image is attached; deletes stuck/failed assets."""
    r = requests.get(
        f"{BASE}/v1/gameCenterAchievementLocalizations/{localization_id}/gameCenterAchievementImage",
        headers=headers(),
    )
    if r.status_code != 200 or not r.json().get("data"):
        return False
    asset = r.json()["data"]
    state = ((asset["attributes"] or {}).get("assetDeliveryState") or {}).get("state")
    if state in ("COMPLETE", "UPLOAD_COMPLETE"):
        return True
    # Reserved-but-never-committed (or failed) asset: clear it so we can retry.
    requests.delete(f"{BASE}/v1/gameCenterAchievementImages/{asset['id']}", headers=headers())
    return False


def provision_achievements(detail):
    existing = {
        a["attributes"]["vendorIdentifier"]: a["id"]
        for a in get_all(f"{BASE}/v1/gameCenterDetails/{detail}/gameCenterAchievements", {"limit": 200})
    }
    created = skipped = 0
    for spec in achievements():
        ach_id = existing.get(spec["apple_id"])
        if ach_id:
            skipped += 1
        else:
            body = {
                "data": {
                    "type": "gameCenterAchievements",
                    "attributes": {
                        "referenceName": spec["en"]["name"],
                        "vendorIdentifier": spec["apple_id"],
                        "points": spec["points"],
                        "showBeforeEarned": True,
                        "repeatable": False,
                    },
                    "relationships": {
                        "gameCenterDetail": {"data": {"type": "gameCenterDetails", "id": detail}}
                    },
                }
            }
            r = requests.post(f"{BASE}/v1/gameCenterAchievements", headers=headers(), json=body)
            if r.status_code != 201:
                die(f"create achievement {spec['id']}", r)
            ach_id = r.json()["data"]["id"]
            created += 1
            print(f"created achievement {spec['id']} -> {ach_id}")

        locs = {
            l["attributes"]["locale"]: l["id"]
            for l in get_all(f"{BASE}/v1/gameCenterAchievements/{ach_id}/localizations", {"limit": 200})
        }
        for locale, key in (("en-US", "en"), ("pl", "pl")):
            loc_id = locs.get(locale)
            if not loc_id:
                body = {
                    "data": {
                        "type": "gameCenterAchievementLocalizations",
                        "attributes": {
                            "locale": locale,
                            "name": spec[key]["name"],
                            "beforeEarnedDescription": spec[key]["desc"],
                            "afterEarnedDescription": spec[key]["desc"],
                        },
                        "relationships": {
                            "gameCenterAchievement": {
                                "data": {"type": "gameCenterAchievements", "id": ach_id}
                            }
                        },
                    }
                }
                r = requests.post(
                    f"{BASE}/v1/gameCenterAchievementLocalizations", headers=headers(), json=body
                )
                if r.status_code != 201:
                    die(f"localize {spec['id']} {locale}", r)
                loc_id = r.json()["data"]["id"]
                print(f"  localized {locale}")
            if not localization_has_image(loc_id):
                png = os.path.join(IMAGES_DIR, f"{spec['id']}.png")
                ok = upload_image(loc_id, png)
                print(f"  image {locale}: {'ok' if ok else 'FAILED'}")
    print(f"achievements: {created} created, {skipped} already existed")


def provision_leaderboards(detail):
    existing = {
        b["attributes"]["vendorIdentifier"]: b["id"]
        for b in get_all(f"{BASE}/v1/gameCenterDetails/{detail}/gameCenterLeaderboards", {"limit": 200})
    }
    for spec in LEADERBOARDS:
        lb_id = existing.get(spec["apple_id"])
        if not lb_id:
            body = {
                "data": {
                    "type": "gameCenterLeaderboards",
                    "attributes": {
                        "referenceName": spec["en"],
                        "vendorIdentifier": spec["apple_id"],
                        "defaultFormatter": "INTEGER",
                        "scoreSortType": "DESC",
                        "scoreRangeStart": "0",
                        "scoreRangeEnd": "100000000",
                        "submissionType": "BEST_SCORE",
                    },
                    "relationships": {
                        "gameCenterDetail": {"data": {"type": "gameCenterDetails", "id": detail}}
                    },
                }
            }
            r = requests.post(f"{BASE}/v1/gameCenterLeaderboards", headers=headers(), json=body)
            if r.status_code != 201:
                die(f"create leaderboard {spec['id']}", r)
            lb_id = r.json()["data"]["id"]
            print(f"created leaderboard {spec['id']} -> {lb_id}")

        locs = {
            l["attributes"]["locale"]: l["id"]
            for l in get_all(f"{BASE}/v1/gameCenterLeaderboards/{lb_id}/localizations", {"limit": 200})
        }
        for locale, key in (("en-US", "en"), ("pl", "pl")):
            if locale in locs:
                continue
            body = {
                "data": {
                    "type": "gameCenterLeaderboardLocalizations",
                    "attributes": {"locale": locale, "name": spec[key]},
                    "relationships": {
                        "gameCenterLeaderboard": {
                            "data": {"type": "gameCenterLeaderboards", "id": lb_id}
                        }
                    },
                }
            }
            r = requests.post(
                f"{BASE}/v1/gameCenterLeaderboardLocalizations", headers=headers(), json=body
            )
            if r.status_code != 201:
                die(f"localize leaderboard {spec['id']} {locale}", r)
            print(f"  localized {spec['id']} {locale}")
    print("leaderboards done")


def provision_releases(detail):
    """Attach every achievement/leaderboard to the editable app version.

    Creating the resources is not enough: until a release record exists, GameKit
    rejects every report and the dashboard shows nothing. Apple only accepts
    releases while an editable (not yet released) Game Center enabled version
    exists, so this step has to be re-run for the version that ships them.
    """
    targets = [
        ("gameCenterAchievementReleases", "gameCenterAchievement", "gameCenterAchievements",
         f"{BASE}/v1/gameCenterDetails/{detail}/gameCenterAchievements"),
        ("gameCenterLeaderboardReleases", "gameCenterLeaderboard", "gameCenterLeaderboards",
         f"{BASE}/v1/gameCenterDetails/{detail}/gameCenterLeaderboards"),
    ]
    created = skipped = 0
    for release_type, relationship, resource_type, list_url in targets:
        for item in get_all(list_url, {"limit": 200}):
            vendor = item["attributes"]["vendorIdentifier"]
            releases = get_all(f"{BASE}/v1/{resource_type}/{item['id']}/releases", {"limit": 200})
            if releases:
                skipped += 1
                continue
            body = {
                "data": {
                    "type": release_type,
                    "relationships": {
                        relationship: {"data": {"type": resource_type, "id": item["id"]}},
                        "gameCenterDetail": {"data": {"type": "gameCenterDetails", "id": detail}},
                    },
                }
            }
            r = requests.post(f"{BASE}/v1/{release_type}", headers=headers(), json=body)
            if r.status_code != 201:
                if "NO_VERSIONS_ELIGIBLE_FOR_GAME_CENTER_RELEASE" in r.text:
                    print(
                        "\n! No editable Game Center enabled version in App Store Connect.\n"
                        "  Releases can only be attached to a version that has not shipped yet.\n"
                        "  Create the next version (with Game Center enabled), then re-run."
                    )
                    return
                die(f"release {vendor}", r)
            created += 1
            print(f"released {vendor}")
    print(f"releases: {created} created, {skipped} already released")


if __name__ == "__main__":
    detail = ensure_detail()
    provision_achievements(detail)
    provision_leaderboards(detail)
    provision_releases(detail)
    print("Game Center provisioning complete.")
