"""Provision ShowDown's Play Games Services config (achievements + leaderboards).

Uses the Games Configuration API (service account from google-play-key.json).
Idempotent: lists existing configs first and skips already-created ones (matched
by the en-US draft name). Captures Google's generated ids into:
  - src/services/gameServices/playIds.generated.ts
  - modules/game-services/android/src/main/res/values/games-ids.xml

Run:  .venv-agents/bin/python .agents/game-services/create_play_games.py
NOTE: configs are created as drafts — publish in Play Console ("Sprawdź i opublikuj").
"""

import os
import sys
import time

from google.oauth2 import service_account
from googleapiclient.discovery import build

sys.path.insert(0, os.path.dirname(__file__))
from definitions import LEADERBOARDS, achievements  # noqa: E402

APPLICATION_ID = "381435458877"
KEY_FILE = "google-play-key.json"
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TS_OUT = os.path.join(REPO_ROOT, "src/services/gameServices/playIds.generated.ts")
XML_OUT = os.path.join(REPO_ROOT, "modules/game-services/android/src/main/res/values/games-ids.xml")


def bundle(en, pl):
    return {"translations": [{"locale": "en-US", "value": en}, {"locale": "pl-PL", "value": pl}]}


def svc():
    creds = service_account.Credentials.from_service_account_file(
        KEY_FILE, scopes=["https://www.googleapis.com/auth/androidpublisher"]
    )
    return build("gamesConfiguration", "v1configuration", credentials=creds)


def list_all(collection, **kwargs):
    items, token = [], None
    while True:
        r = collection.list(applicationId=APPLICATION_ID, maxResults=200, pageToken=token, **kwargs).execute()
        items += r.get("items", [])
        token = r.get("nextPageToken")
        if not token:
            return items


def en_name(cfg):
    for t in ((cfg.get("draft") or {}).get("name") or {}).get("translations", []):
        if t["locale"].startswith("en"):
            return t["value"]
    return None


# NOTE: achievement icons cannot be uploaded via this API anymore (the discovery
# document exposes no imageConfigurations resource). Add icons manually in Play
# Console if desired — Play Games shows a default placeholder otherwise.


def provision_achievements(games):
    coll = games.achievementConfigurations()
    existing = {en_name(a): a for a in list_all(coll)}
    ids = {}
    for rank, spec in enumerate(achievements(), start=1):
        item = existing.get(spec["en"]["name"])
        if item:
            ids[spec["id"]] = item["id"]
            print(f"skip {spec['id']} (exists: {item['id']})")
            continue
        body = {
            "achievementType": "STANDARD",
            "initialState": "REVEALED",
            "draft": {
                "name": bundle(spec["en"]["name"], spec["pl"]["name"]),
                "description": bundle(spec["en"]["desc"], spec["pl"]["desc"]),
                "pointValue": spec["points"],
                "sortRank": rank,
            },
        }
        r = coll.insert(applicationId=APPLICATION_ID, body=body).execute()
        ids[spec["id"]] = r["id"]
        print(f"created {spec['id']} -> {r['id']}")
        time.sleep(0.4)
    return ids


def provision_leaderboards(games):
    coll = games.leaderboardConfigurations()
    existing = {en_name(b): b["id"] for b in list_all(coll)}
    ids = {}
    for spec in LEADERBOARDS:
        if spec["en"] in existing:
            ids[spec["id"]] = existing[spec["en"]]
            print(f"skip leaderboard {spec['id']} (exists)")
            continue
        body = {
            "scoreOrder": "LARGER_IS_BETTER",
            "draft": {
                "name": bundle(spec["en"], spec["pl"]),
                "scoreFormat": {"numberFormatType": "NUMERIC", "numDecimalPlaces": 0},
            },
        }
        r = coll.insert(applicationId=APPLICATION_ID, body=body).execute()
        ids[spec["id"]] = r["id"]
        print(f"created leaderboard {spec['id']} -> {r['id']}")
        time.sleep(0.4)
    return ids


def write_outputs(ach_ids, lb_ids):
    lines = [
        "// GENERATED by .agents/game-services/create_play_games.py — do not edit by hand.",
        "// Maps local achievement / game ids to the opaque ids Google assigns when the",
        "// Play Games Services configuration is created.",
        "",
        f"export const PLAY_GAMES_PROJECT_ID = '{APPLICATION_ID}';",
        "",
        "export const PLAY_GAMES_ACHIEVEMENT_IDS: Record<string, string> = {",
    ]
    lines += [f"    '{k}': '{v}'," for k, v in ach_ids.items()]
    lines += ["};", "", "export const PLAY_GAMES_LEADERBOARD_IDS: Record<string, string> = {"]
    lines += [f"    '{k}': '{v}'," for k, v in lb_ids.items()]
    lines += ["};", ""]
    open(TS_OUT, "w").write("\n".join(lines))
    print(f"wrote {TS_OUT}")

    xml = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<resources>\n"
        "    <!-- Play Games Services project id. Written by\n"
        "         .agents/game-services/create_play_games.py — do not translate. -->\n"
        f'    <string name="game_services_project_id" translatable="false">{APPLICATION_ID}</string>\n'
        "</resources>\n"
    )
    open(XML_OUT, "w").write(xml)
    print(f"wrote {XML_OUT}")


if __name__ == "__main__":
    games = svc()
    ach_ids = provision_achievements(games)
    lb_ids = provision_leaderboards(games)
    assert len(ach_ids) == 31, f"expected 31 achievement ids, got {len(ach_ids)}"
    assert len(lb_ids) == 3, f"expected 3 leaderboard ids, got {len(lb_ids)}"
    write_outputs(ach_ids, lb_ids)
    print("Play Games provisioning complete (drafts — publish in Play Console).")
