import { createTheme } from '../createTheme';

export const minimalTheme = createTheme({
    id: 'minimal',
    name: 'Minimal',
    colors: {
        background: '#FAFAFA',
        surface: '#FFFFFF',
        surfaceVariant: '#F0F0F0',
        primary: '#1A1A1A',
        onPrimary: '#FFFFFF',
        secondary: '#6B6B6B',
        onSecondary: '#FFFFFF',
        error: '#DC3545',
        success: '#28A745',
        text: '#1A1A1A',
        textSecondary: '#6B6B6B',
        textMuted: '#A0A0A0',
        border: '#E0E0E0',
        borderLight: '#F0F0F0',
        overlay: 'rgba(0, 0, 0, 0.3)',
        shadow: '#000000',
        onError: '#FFFFFF',
        onSuccess: '#FFFFFF',
        warning: '#E8960A',
        onWarning: '#FFFFFF',
    },
    animation: {
        press: { scale: 0.98, duration: 100 },
        springBouncy: { damping: 24, stiffness: 220 },
        springGentle: { damping: 28, stiffness: 100 },
    },
    radii: {
        sm: 8,
        md: 14,
        lg: 20,
        xl: 28,
        full: 9999,
    },
    shadows: {
        sm: {
            shadowColor: '#00000010',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.05,
            shadowRadius: 2,
            elevation: 1,
        },
        md: {
            shadowColor: '#00000010',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.08,
            shadowRadius: 8,
            elevation: 2,
        },
        lg: {
            shadowColor: '#00000010',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.1,
            shadowRadius: 16,
            elevation: 4,
        },
        none: null,
    },
});
