import { createTheme } from '../createTheme';

export const pastelTheme = createTheme({
    id: 'pastel',
    name: 'Pastel',
    colors: {
        background: '#FEF4F6',
        surface: '#FFFFFF',
        surfaceVariant: '#FFF0F2',
        primary: '#F06292',
        onPrimary: '#FFFFFF',
        secondary: '#64B5F6',
        onSecondary: '#1A1A2E',
        error: '#EF5350',
        success: '#81C784',
        text: '#2D2D3A',
        textSecondary: '#6B6B80',
        textMuted: '#A0A0B0',
        border: '#F0DDE2',
        borderLight: '#F8ECF0',
        overlay: 'rgba(255, 255, 255, 0.7)',
        shadow: '#000000',
        onError: '#FFFFFF',
        onSuccess: '#1A1A2E',
        warning: '#FFB74D',
        onWarning: '#1A1A2E',
    },
    radii: {
        sm: 8,
        md: 14,
        lg: 20,
        xl: 28,
        full: 9999,
    },
    animation: {
        springBouncy: { damping: 16, stiffness: 200 },
        springGentle: { damping: 24, stiffness: 100 },
        press: { scale: 0.97, duration: 200 },
    },
    shadows: {
        sm: {
            shadowColor: '#00000015',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.08,
            shadowRadius: 4,
            elevation: 1,
        },
        md: {
            shadowColor: '#00000015',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.1,
            shadowRadius: 10,
            elevation: 3,
        },
        lg: {
            shadowColor: '#00000015',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.12,
            shadowRadius: 20,
            elevation: 6,
        },
        none: null,
    },
});
