// GENERATED by .agents/game-services/create_play_games.py — do not edit by hand.
// Maps local achievement / game ids to the opaque ids Google assigns when the
// Play Games Services configuration is created. Empty until provisioning runs.

export const PLAY_GAMES_PROJECT_ID = '0';

export const PLAY_GAMES_ACHIEVEMENT_IDS: Record<string, string> = {};

export const PLAY_GAMES_LEADERBOARD_IDS: Record<string, string> = {};
