// GENERATED by .agents/game-services/create_play_games.py — do not edit by hand.
// Maps local achievement / game ids to the opaque ids Google assigns when the
// Play Games Services configuration is created.

export const PLAY_GAMES_PROJECT_ID = '381435458877';

export const PLAY_GAMES_ACHIEVEMENT_IDS: Record<string, string> = {
    'contestant-bronze': 'CgkIverM-owLEAIQAA',
    'contestant-silver': 'CgkIverM-owLEAIQAQ',
    'contestant-gold': 'CgkIverM-owLEAIQAg',
    'on-a-roll-bronze': 'CgkIverM-owLEAIQAw',
    'on-a-roll-silver': 'CgkIverM-owLEAIQBA',
    'on-a-roll-gold': 'CgkIverM-owLEAIQBQ',
    'regular-bronze': 'CgkIverM-owLEAIQBg',
    'regular-silver': 'CgkIverM-owLEAIQBw',
    'regular-gold': 'CgkIverM-owLEAIQCA',
    'winner-bronze': 'CgkIverM-owLEAIQCQ',
    'winner-silver': 'CgkIverM-owLEAIQCg',
    'winner-gold': 'CgkIverM-owLEAIQCw',
    'ladder-scorer-bronze': 'CgkIverM-owLEAIQDA',
    'ladder-scorer-silver': 'CgkIverM-owLEAIQDQ',
    'ladder-scorer-gold': 'CgkIverM-owLEAIQDg',
    'drop-scorer-bronze': 'CgkIverM-owLEAIQDw',
    'drop-scorer-silver': 'CgkIverM-owLEAIQEA',
    'drop-scorer-gold': 'CgkIverM-owLEAIQEQ',
    'wheel-scorer-bronze': 'CgkIverM-owLEAIQEg',
    'wheel-scorer-silver': 'CgkIverM-owLEAIQEw',
    'wheel-scorer-gold': 'CgkIverM-owLEAIQFA',
    'well-rounded': 'CgkIverM-owLEAIQFQ',
    'triple-threat': 'CgkIverM-owLEAIQFg',
    'to-the-top': 'CgkIverM-owLEAIQFw',
    spotless: 'CgkIverM-owLEAIQGA',
    survivor: 'CgkIverM-owLEAIQGQ',
    'iron-bank': 'CgkIverM-owLEAIQGg',
    'vowel-free': 'CgkIverM-owLEAIQGw',
    'clean-sweep': 'CgkIverM-owLEAIQHA',
    'quick-wit': 'CgkIverM-owLEAIQHQ',
    comeback: 'CgkIverM-owLEAIQHg',
};

export const PLAY_GAMES_LEADERBOARD_IDS: Record<string, string> = {
    'the-ladder': 'CgkIverM-owLEAIQHw',
    'the-drop': 'CgkIverM-owLEAIQIA',
    'the-wheel': 'CgkIverM-owLEAIQIQ',
};
