const cards: { id: string; phrase: { en: string; pl: string }; category: { en: string; pl: string } }[] = [
    { id: 'wheel-world-landmarks-001', phrase: { en: 'EIFFEL TOWER', pl: 'WIEŻA EIFFLA' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-002', phrase: { en: 'GREAT WALL OF CHINA', pl: 'WIELKI MUR CHIŃSKI' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-003', phrase: { en: 'STATUE OF LIBERTY', pl: 'STATUA WOLNOŚCI' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-004', phrase: { en: 'MACHU PICCHU', pl: 'MACHU PICCHU' }, category: { en: 'HISTORIC SITE', pl: 'MIEJSCE HISTORYCZNE' } },
    { id: 'wheel-world-landmarks-005', phrase: { en: 'GREAT PYRAMID OF GIZA', pl: 'WIELKA PIRAMIDA W GIZIE' }, category: { en: 'ANCIENT WONDER', pl: 'STAROŻYTNY CUD' } },
    { id: 'wheel-world-landmarks-006', phrase: { en: 'COLOSSEUM', pl: 'KOLOSEUM' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-007', phrase: { en: 'TAJ MAHAL', pl: 'TADŻ MAHAL' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-008', phrase: { en: 'PETRA', pl: 'PETRA' }, category: { en: 'ANCIENT CITY', pl: 'STAROŻYTNE MIASTO' } },
    { id: 'wheel-world-landmarks-009', phrase: { en: 'CHRIST THE REDEEMER', pl: 'CHRYSTUS ODKUPICIEL' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-010', phrase: { en: 'CHICHEN ITZA', pl: 'CHICHEN ITZA' }, category: { en: 'ANCIENT CITY', pl: 'STAROŻYTNE MIASTO' } },
    { id: 'wheel-world-landmarks-011', phrase: { en: 'ACROPOLIS OF ATHENS', pl: 'AKROPOL ATEŃSKI' }, category: { en: 'HISTORIC SITE', pl: 'MIEJSCE HISTORYCZNE' } },
    { id: 'wheel-world-landmarks-012', phrase: { en: 'STONEHENGE', pl: 'STONEHENGE' }, category: { en: 'ANCIENT MONUMENT', pl: 'PREHISTORYCZNY ZABYTEK' } },
    { id: 'wheel-world-landmarks-013', phrase: { en: 'ANGKOR WAT', pl: 'ANGKOR WAT' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-014', phrase: { en: 'EASTER ISLAND MOAI', pl: 'MOAI Z WYSPY WIELKANOCNEJ' }, category: { en: 'HISTORIC SITE', pl: 'MIEJSCE HISTORYCZNE' } },
    { id: 'wheel-world-landmarks-015', phrase: { en: 'SYDNEY OPERA HOUSE', pl: 'OPERA W SYDNEY' }, category: { en: 'MODERN WONDER', pl: 'WSPÓŁCZESNY CUD' } },
    { id: 'wheel-world-landmarks-016', phrase: { en: 'GRAND CANYON', pl: 'WIELKI KANION' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-017', phrase: { en: 'MOUNT EVEREST', pl: 'MOUNT EVEREST' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-018', phrase: { en: 'NIAGARA FALLS', pl: 'WODOSPAD NIAGARA' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-019', phrase: { en: 'VICTORIA FALLS', pl: 'WODOSPADY WIKTORII' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-020', phrase: { en: 'GREAT BARRIER REEF', pl: 'WIELKA RAFA KORALOWA' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-021', phrase: { en: 'MIDNIGHT SUN', pl: 'SŁOŃCE O PÓŁNOCY' }, category: { en: 'NATURAL PHENOMENON', pl: 'ZJAWISKO PRZYRODNICZE' } },
    { id: 'wheel-world-landmarks-022', phrase: { en: 'AMAZON RAINFOREST', pl: 'LASY DESZCZOWE AMAZONII' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-023', phrase: { en: 'GALAPAGOS ISLANDS', pl: 'WYSPY GALAPAGOS' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-024', phrase: { en: 'DEAD SEA', pl: 'MORZE MARTWE' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-025', phrase: { en: 'TABLE MOUNTAIN', pl: 'GÓRA STOŁOWA' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-026', phrase: { en: 'MOUNT FUJI', pl: 'GÓRA FUDŻI' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-027', phrase: { en: 'KILIMANJARO', pl: 'KILIMANDŻARO' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-028', phrase: { en: 'ULURU', pl: 'ULURU' }, category: { en: 'NATURAL WONDER', pl: 'CUD NATURY' } },
    { id: 'wheel-world-landmarks-029', phrase: { en: 'SANTORINI', pl: 'SANTORINI' }, category: { en: 'PLACE', pl: 'MIEJSCE' } },
    { id: 'wheel-world-landmarks-030', phrase: { en: 'VENICE CANALS', pl: 'KANAŁY WENECJI' }, category: { en: 'PLACE', pl: 'MIEJSCE' } },
    { id: 'wheel-world-landmarks-031', phrase: { en: 'BIG BEN', pl: 'BIG BEN' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-032', phrase: { en: 'TOWER BRIDGE', pl: 'TOWER BRIDGE' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-033', phrase: { en: 'BUCKINGHAM PALACE', pl: 'PAŁAC BUCKINGHAM' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-034', phrase: { en: 'WESTMINSTER ABBEY', pl: 'OPACTWO WESTMINSTERSKIE' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-035', phrase: { en: 'NOTRE DAME DE PARIS', pl: 'KATEDRA NOTRE DAME W PARYŻU' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-036', phrase: { en: 'LOUVRE MUSEUM', pl: 'LUWR' }, category: { en: 'MUSEUM', pl: 'MUZEUM' } },
    { id: 'wheel-world-landmarks-037', phrase: { en: 'ARC DE TRIOMPHE IN PARIS', pl: 'ŁUK TRIUMFALNY W PARYŻU' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-038', phrase: { en: 'SAGRADA FAMILIA', pl: 'SAGRADA FAMILIA' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-039', phrase: { en: 'ALHAMBRA', pl: 'ALHAMBRA' }, category: { en: 'HISTORIC SITE', pl: 'MIEJSCE HISTORYCZNE' } },
    { id: 'wheel-world-landmarks-040', phrase: { en: 'PARK GÜELL', pl: 'PARK GÜELL' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-041', phrase: { en: 'BRANDENBURG GATE', pl: 'BRAMA BRANDENBURSKA' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-042', phrase: { en: 'NEUSCHWANSTEIN CASTLE', pl: 'ZAMEK NEUSCHWANSTEIN' }, category: { en: 'CASTLE', pl: 'ZAMEK' } },
    { id: 'wheel-world-landmarks-043', phrase: { en: 'SAINT PETER\'S BASILICA', pl: 'BAZYLIKA ŚWIĘTEGO PIOTRA' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-044', phrase: { en: 'SISTINE CHAPEL', pl: 'KAPLICA SYKSTYŃSKA' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-045', phrase: { en: 'TREVI FOUNTAIN', pl: 'FONTANNA DI TREVI' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-046', phrase: { en: 'PANTHEON IN ROME', pl: 'PANTEON W RZYMIE' }, category: { en: 'HISTORIC SITE', pl: 'MIEJSCE HISTORYCZNE' } },
    { id: 'wheel-world-landmarks-047', phrase: { en: 'LEANING TOWER OF PISA', pl: 'KRZYWA WIEŻA W PIZIE' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-048', phrase: { en: 'POMPEII', pl: 'POMPEJE' }, category: { en: 'ANCIENT CITY', pl: 'STAROŻYTNE MIASTO' } },
    { id: 'wheel-world-landmarks-049', phrase: { en: 'HAGIA SOPHIA', pl: 'HAGIA SOPHIA' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-050', phrase: { en: 'BLUE MOSQUE', pl: 'BŁĘKITNY MECZET' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-051', phrase: { en: 'BURJ KHALIFA', pl: 'BURDŻ CHALIFA' }, category: { en: 'MODERN WONDER', pl: 'WSPÓŁCZESNY CUD' } },
    { id: 'wheel-world-landmarks-052', phrase: { en: 'ABU SIMBEL TEMPLES', pl: 'ŚWIĄTYNIE ABU SIMBEL' }, category: { en: 'HISTORIC SITE', pl: 'MIEJSCE HISTORYCZNE' } },
    { id: 'wheel-world-landmarks-053', phrase: { en: 'FORBIDDEN CITY', pl: 'ZAKAZANE MIASTO' }, category: { en: 'HISTORIC SITE', pl: 'MIEJSCE HISTORYCZNE' } },
    { id: 'wheel-world-landmarks-054', phrase: { en: 'TERRACOTTA ARMY', pl: 'TERAKOTOWA ARMIA' }, category: { en: 'HISTORIC SITE', pl: 'MIEJSCE HISTORYCZNE' } },
    { id: 'wheel-world-landmarks-055', phrase: { en: 'KINKAKU-JI', pl: 'ZŁOTY PAWILON' }, category: { en: 'RELIGIOUS SITE', pl: 'OBIEKT SAKRALNY' } },
    { id: 'wheel-world-landmarks-056', phrase: { en: 'GOLDEN GATE BRIDGE', pl: 'MOST GOLDEN GATE' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-057', phrase: { en: 'HOLLYWOOD SIGN', pl: 'NAPIS HOLLYWOOD' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-058', phrase: { en: 'MOUNT RUSHMORE', pl: 'MOUNT RUSHMORE' }, category: { en: 'LANDMARK', pl: 'ZABYTEK' } },
    { id: 'wheel-world-landmarks-059', phrase: { en: 'EMPIRE STATE BUILDING', pl: 'EMPIRE STATE BUILDING' }, category: { en: 'MODERN WONDER', pl: 'WSPÓŁCZESNY CUD' } },
    { id: 'wheel-world-landmarks-060', phrase: { en: 'TIMES SQUARE', pl: 'TIMES SQUARE' }, category: { en: 'PLACE', pl: 'MIEJSCE' } },
];

const toLocale = (lang: 'en' | 'pl') => (c: typeof cards[0]): any => ({
    id: c.id,
    phrase: c.phrase[lang],
    category: c.category[lang],
});

export const en = cards.map(toLocale('en'));
export const pl = cards.map(toLocale('pl'));
