import type { DropPackCard } from '../content';

export const en: DropPackCard[] = [

    { id: 'drop-our-changing-planet-001', prompt: 'How many trees are currently on Earth (roughly)?', options: ['300 billion', '1 trillion', '3 trillion', '7 trillion'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-002', prompt: 'How many people could live on Earth if everyone lived like Americans?', options: ['1.5 billion', '2.5 billion', '4 billion', '7 billion'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-003', prompt: 'What is the average depth of the world\'s oceans (meters)?', options: ['1,200', '3,682', '5,400', '8,200'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-004', prompt: 'How much of Earth\'s surface is covered by water?', options: ['55%', '61%', '71%', '82%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-005', prompt: 'What percentage of the world\'s water is stored in the oceans?', options: ['85.2%', '91.4%', '96.5%', '99.1%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-006', prompt: 'How many years does it take for a plastic bottle to decompose in the ocean?', options: ['50', '150', '450', '1,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-007', prompt: 'What percentage of Earth\'s land is covered by forests?', options: ['21%', '31%', '41%', '51%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-008', prompt: 'How many tons of plastic enter the ocean every year (millions)?', options: ['2', '8', '15', '30'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-009', prompt: 'What is the current concentration of CO2 in the atmosphere (ppm)?', options: ['320', '380', '421', '495'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-010', prompt: 'How many meters has the global sea level risen since 1880?', options: ['0.05', '0.12', '0.23', '0.45'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-011', prompt: 'What percentage of global greenhouse gas emissions come from agriculture?', options: ['8%', '18%', '28%', '38%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-012', prompt: 'How many species are estimated to go extinct every year?', options: ['2,000', '10,000', '50,000', '100,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-013', prompt: 'What is the average global temperature increase since 1880 (°C)?', options: ['0.5', '1.1', '1.8', '2.5'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-014', prompt: 'What percentage of Earth\'s fresh water is found in glaciers and ice caps?', options: ['45%', '58%', '69%', '82%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-015', prompt: 'How many people currently lack access to safely managed drinking water (billions)?', options: ['0.8', '1.4', '2.2', '3.5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-016', prompt: 'What percentage of the world\'s energy comes from renewable sources?', options: ['12%', '19%', '29%', '42%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-017', prompt: 'How many square kilometers of rainforest are lost every minute?', options: ['15', '27', '35', '50'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-018', prompt: 'What percentage of the ocean remains unexplored?', options: ['50%', '65%', '80%', '95%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-019', prompt: 'How many active volcanoes are there on Earth?', options: ['500', '1,350', '2,500', '4,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-020', prompt: 'What is the maximum depth of the Mariana Trench (meters)?', options: ['8,848', '10,935', '12,500', '14,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-021', prompt: 'How many lightning strikes occur on Earth per day?', options: ['1 million', '3 million', '8 million', '15 million'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-022', prompt: 'What is the average salinity of the ocean (grams per liter)?', options: ['25', '35', '45', '55'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-023', prompt: 'How many years ago did the last ice age end?', options: ['8,000', '11,500', '15,000', '25,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-024', prompt: 'What percentage of Earth\'s land is classified as desert?', options: ['15%', '25%', '33%', '45%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-025', prompt: 'How many tons of e-waste are generated globally each year (millions)?', options: ['25', '40', '62', '85'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-026', prompt: 'What is the thickness of the ozone layer (Dobson Units, average)?', options: ['150', '300', '450', '600'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-027', prompt: 'How many cubic kilometers of water are in the atmosphere?', options: ['8,500', '12,900', '15,000', '20,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-028', prompt: 'What percentage of the Amazon rainforest has been lost in the last 50 years?', options: ['10%', '17%', '25%', '35%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-029', prompt: 'How many megatons of methane are emitted by livestock annually?', options: ['50', '80', '115', '150'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-030', prompt: 'What percentage of global electricity is used by the internet?', options: ['2%', '5%', '10%', '15%'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-031', prompt: 'How many pounds of garbage does the average person produce daily?', options: ['2.1', '4.5', '7.2', '10.5'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-032', prompt: 'What percentage of coral reefs have already been lost?', options: ['25%', '50%', '75%', '90%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-033', prompt: 'How many kilometers across is the Great Pacific Garbage Patch?', options: ['500,000', '1,000,000', '1,600,000', '2,500,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-034', prompt: 'What is the average age of a wild forest tree?', options: ['50', '100', '150', '200'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-035', prompt: 'How many people are predicted to be climate refugees by 2050 (millions)?', options: ['50', '140', '216', '500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-036', prompt: 'What percentage of global food produced is wasted?', options: ['15%', '33%', '50%', '65%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-037', prompt: 'How many wild tigers are left in the world?', options: ['2,500', '4,500', '5,574', '10,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-038', prompt: 'What percentage of the Earth\'s population lives in coastal areas?', options: ['25%', '40%', '55%', '70%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-039', prompt: 'How many millions of barrels of oil are consumed globally per day?', options: ['50', '75', '102', '130'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-040', prompt: 'What is the diameter of Earth at the equator (km)?', options: ['6,371', '10,500', '12,756', '15,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-041', prompt: 'How many minutes does it take for Earth to complete one rotation (sidereal)?', options: ['1,400', '1,436', '1,440', '1,452'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-042', prompt: 'What is the weight of Earth\'s atmosphere (quadrillion tons)?', options: ['1.5', '5.1', '10.2', '25.5'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-043', prompt: 'What percentage of Earth\'s biomass is made up of humans?', options: ['0.01%', '0.1%', '1%', '5%'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-044', prompt: 'How many earthquakes happen globally every day?', options: ['50', '100', '150', '200'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-045', prompt: 'What is the speed of Earth\'s orbit around the Sun (km/h)?', options: ['50,000', '85,000', '107,000', '150,000'], correctIndex: 2 }
,

    { id: 'drop-our-changing-planet-046', prompt: 'What percentage of the world\'s fresh water is used for agriculture?', options: ['40%', '55%', '70%', '85%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-047', prompt: 'How many tons of ice does Antarctica lose every year (billions)?', options: ['50', '150', '250', '350'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-048', prompt: 'What is the highest recorded wind speed in a tornado (km/h)?', options: ['350', '484', '550', '620'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-049', prompt: 'How many people globally rely on the ocean for their primary source of protein (billions)?', options: ['1', '2', '3', '4'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-050', prompt: 'What percentage of global greenhouse gases comes from transportation?', options: ['10%', '15%', '24%', '35%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-051', prompt: 'How many megacities (over 10 million people) are there in the world today?', options: ['15', '25', '33', '45'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-052', prompt: 'What percentage of Earth\'s surface is permanently covered by ice?', options: ['5%', '10%', '15%', '20%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-053', prompt: 'How many liters of water does it take to produce one kilogram of beef?', options: ['2,500', '5,000', '10,000', '15,400'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-054', prompt: 'What is the coldest temperature ever recorded on Earth (°C)?', options: ['-75.2', '-89.2', '-98.6', '-105.4'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-055', prompt: 'How many tons of meteoritic dust fall on Earth each day?', options: ['10', '60', '150', '300'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-056', prompt: 'What percentage of the world\'s population lives in the Northern Hemisphere?', options: ['60%', '75%', '90%', '98%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-057', prompt: 'How many gallons of water are used globally per day (billions)?', options: ['500', '1,000', '2,500', '4,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-058', prompt: 'What is the average depth of the ice sheet covering Antarctica (meters)?', options: ['1,000', '1,500', '2,160', '3,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-059', prompt: 'How many days does a drop of water stay in the ocean before evaporating?', options: ['100', '500', '1,500', '3,000'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-060', prompt: 'What percentage of the world\'s coral reefs are in the Great Barrier Reef?', options: ['5%', '10%', '15%', '25%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-061', prompt: 'How many metric tons of CO2 does the average human emit per year?', options: ['2.5', '4.7', '7.2', '10.5'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-062', prompt: 'What is the total mass of all the plastic in the ocean (million tons)?', options: ['25', '75', '150', '300'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-063', prompt: 'How many people die prematurely every year due to air pollution (millions)?', options: ['2', '4', '7', '10'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-064', prompt: 'What percentage of the world\'s forests have been destroyed since human civilization began?', options: ['25%', '35%', '46%', '60%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-065', prompt: 'How many species of plants are estimated to exist on Earth?', options: ['150,000', '300,000', '400,000', '600,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-066', prompt: 'What is the average thickness of the Earth\'s crust (km)?', options: ['15', '30', '50', '75'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-067', prompt: 'How many times per year does lightning strike the Empire State Building?', options: ['5', '10', '25', '50'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-068', prompt: 'What percentage of Earth\'s volcanic activity occurs in the oceans?', options: ['50%', '65%', '80%', '95%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-069', prompt: 'How many millimeters does the Moon move away from Earth each year?', options: ['15', '25', '38', '50'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-070', prompt: 'What is the total volume of water on Earth (million cubic kilometers)?', options: ['500', '1,000', '1,386', '2,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-071', prompt: 'How many days of food supply does a typical large city have on hand?', options: ['3', '7', '14', '30'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-072', prompt: 'What percentage of the world\'s agricultural land is used for livestock?', options: ['45%', '55%', '65%', '77%'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-073', prompt: 'How many tons of gold are estimated to be dissolved in the world\'s oceans?', options: ['1,000', '5,000', '10,000', '20,000'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-074', prompt: 'What is the highest recorded wave ever surfed (meters)?', options: ['18', '24', '31', '40'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-075', prompt: 'How many kilometers of blood vessels are in a human body?', options: ['50,000', '80,000', '100,000', '150,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-076', prompt: 'What percentage of the world\'s energy comes from nuclear power?', options: ['5%', '10%', '15%', '20%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-077', prompt: 'How many liters of water are needed to produce a single cotton t-shirt?', options: ['500', '1,200', '2,700', '5,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-078', prompt: 'What is the average lifespan of a modern solar panel (years)?', options: ['15', '25', '35', '50'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-079', prompt: 'How many people globally do not have access to electricity (millions)?', options: ['250', '500', '770', '1,200'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-080', prompt: 'What percentage of the world\'s oxygen is produced by the Amazon rainforest?', options: ['10%', '20%', '30%', '40%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-081', prompt: 'How many active satellites are currently orbiting Earth?', options: ['2,500', '5,000', '7,500', '10,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-082', prompt: 'What is the deepest point reached by a human in the ocean (meters)?', options: ['8,500', '9,800', '10,928', '11,500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-083', prompt: 'How many tons of food are wasted globally every second?', options: ['20', '40', '65', '100'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-084', prompt: 'What percentage of the world\'s population lives in extreme poverty?', options: ['5%', '9%', '15%', '22%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-085', prompt: 'How many liters of air does a person breathe in a day?', options: ['5,000', '8,000', '11,000', '15,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-086', prompt: 'What is the fastest animal on Earth (km/h)?', options: ['150', '250', '320', '389'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-087', prompt: 'How many species of ants are there on Earth?', options: ['5,000', '10,000', '14,000', '20,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-088', prompt: 'What percentage of the human body is made of stardust?', options: ['50%', '75%', '97%', '100%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-089', prompt: 'How many miles of coastline does the Earth have?', options: ['200,000', '350,000', '500,000', '750,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-090', prompt: 'What is the largest living structure on Earth (km)?', options: ['1,000', '2,300', '3,500', '5,000'], correctIndex: 1 }
,

    { id: 'drop-our-changing-planet-091', prompt: 'What percentage of the world\'s fresh water is in Lake Baikal?', options: ['5%', '10%', '20%', '30%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-092', prompt: 'How many times could the Earth fit inside the Sun?', options: ['10,000', '100,000', '1,000,000', '1,300,000'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-093', prompt: 'What is the average global life expectancy (years)?', options: ['65', '68', '73', '78'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-094', prompt: 'How many tons of water does a large hurricane drop (billions)?', options: ['1', '5', '10', '20'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-095', prompt: 'What percentage of Earth\'s surface is used for agriculture?', options: ['15%', '25%', '38%', '50%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-096', prompt: 'How many active volcanoes are located in the Ring of Fire?', options: ['250', '452', '600', '800'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-097', prompt: 'What is the highest temperature ever recorded in the ocean (°C)?', options: ['150', '250', '350', '464'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-098', prompt: 'How many metric tons of fish are caught globally each year (millions)?', options: ['50', '90', '130', '200'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-099', prompt: 'What percentage of global waste is currently recycled?', options: ['9%', '19%', '29%', '39%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-100', prompt: 'How many new species are discovered every year?', options: ['1,000', '5,000', '18,000', '50,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-101', prompt: 'What is the average thickness of the Antarctic ice sheet (meters)?', options: ['1,000', '2,100', '3,500', '4,800'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-102', prompt: 'How many people live without basic sanitation facilities (billions)?', options: ['1.5', '2.5', '3.6', '5.0'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-103', prompt: 'What percentage of Earth\'s species live in the ocean?', options: ['30%', '50%', '70%', '90%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-104', prompt: 'How many kilometers of roads exist globally (millions)?', options: ['25', '45', '64', '85'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-105', prompt: 'What percentage of the world\'s population lives in cities?', options: ['40%', '56%', '65%', '75%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-106', prompt: 'How many trees are cut down each year globally (billions)?', options: ['5', '10', '15', '25'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-107', prompt: 'What is the maximum wind speed recorded inside a hurricane (km/h)?', options: ['250', '305', '345', '400'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-108', prompt: 'How many pounds of plastic are produced globally every year (billions)?', options: ['200', '500', '850', '1,200'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-109', prompt: 'What percentage of the Amazon is currently deforested?', options: ['10%', '17%', '25%', '35%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-110', prompt: 'How many days would it take to walk around the Earth at the equator?', options: ['500', '850', '1,050', '1,500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-111', prompt: 'What percentage of the world\'s electricity is generated from coal?', options: ['20%', '36%', '45%', '55%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-112', prompt: 'How many tons of clothing are thrown away every year (millions)?', options: ['20', '45', '92', '150'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-113', prompt: 'What is the average depth of the Mediterranean Sea (meters)?', options: ['500', '1,000', '1,500', '2,500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-114', prompt: 'How many metric tons of steel are produced globally each year (millions)?', options: ['500', '1,000', '1,800', '2,500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-115', prompt: 'What percentage of Earth\'s atmospheric mass is in the troposphere?', options: ['50%', '65%', '80%', '95%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-116', prompt: 'How many people die from heatwaves globally each year?', options: ['100,000', '250,000', '489,000', '1,000,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-117', prompt: 'What percentage of global fresh water is contained in the Great Lakes?', options: ['5%', '10%', '21%', '35%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-118', prompt: 'How many tons of food does a human eat in a lifetime?', options: ['15', '25', '35', '50'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-119', prompt: 'What is the highest recorded amount of rainfall in 24 hours (meters)?', options: ['0.8', '1.2', '1.8', '2.5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-120', prompt: 'How many millions of tons of concrete are produced annually?', options: ['1,000', '2,000', '4,100', '6,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-121', prompt: 'What percentage of Earth\'s species have gone extinct over its history?', options: ['80%', '90%', '95%', '99%'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-122', prompt: 'How many commercial flights take off every day globally?', options: ['50,000', '100,000', '150,000', '200,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-123', prompt: 'What is the average lifespan of a disposable coffee cup (minutes)?', options: ['5', '10', '15', '30'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-124', prompt: 'How many tons of sand are used globally each year (billions)?', options: ['10', '25', '50', '80'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-125', prompt: 'What percentage of the world\'s fresh water is in the Amazon Basin?', options: ['5%', '10%', '20%', '30%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-126', prompt: 'How many days per year does the Sun not set at the North Pole?', options: ['90', '120', '150', '186'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-127', prompt: 'What is the lowest temperature ever recorded in the ocean (°C)?', options: ['-1', '-2', '-5', '-10'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-128', prompt: 'How many gigatons of ice is Greenland losing every year?', options: ['50', '150', '280', '500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-129', prompt: 'What percentage of global land area is covered by cities?', options: ['1%', '3%', '5%', '10%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-130', prompt: 'How many metric tons of fertilizer are used globally each year (millions)?', options: ['50', '100', '200', '350'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-131', prompt: 'What percentage of the world\'s birds are facing extinction?', options: ['5%', '13%', '25%', '40%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-132', prompt: 'How many liters of water are needed to produce a smartphone?', options: ['1,000', '5,000', '12,000', '25,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-133', prompt: 'What is the average thickness of the ocean\'s photic (sunlit) zone (meters)?', options: ['50', '100', '200', '500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-134', prompt: 'How many millions of barrels of oil are spilled into oceans annually?', options: ['0.5', '1.3', '2.5', '5.0'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-135', prompt: 'What percentage of Earth\'s history has the planet had ice caps?', options: ['10%', '20%', '30%', '50%'], correctIndex: 1 }
,

    { id: 'drop-our-changing-planet-136', prompt: 'How many pieces of microplastic are estimated to be in the ocean (trillions)?', options: ['5', '15', '51', '100'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-137', prompt: 'What is the average global sea surface temperature (°C)?', options: ['12.5', '16.1', '20.1', '25.0'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-138', prompt: 'How many tons of copper are estimated to be in the ocean?', options: ['1 million', '10 million', '50 million', '100 million'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-139', prompt: 'What percentage of the world\'s oxygen comes from the Amazon?', options: ['6%', '12%', '20%', '35%'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-140', prompt: 'How many degrees has the Arctic warmed since 1979 (°C)?', options: ['1.0', '2.0', '3.0', '4.5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-141', prompt: 'What percentage of the world\'s crops rely on animal pollination?', options: ['35%', '50%', '75%', '90%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-142', prompt: 'How many millions of tons of glass are produced globally each year?', options: ['50', '130', '250', '400'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-143', prompt: 'What is the longest mountain range on Earth (km)?', options: ['7,000', '15,000', '40,000', '65,000'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-144', prompt: 'How many people live in areas with water scarcity (billions)?', options: ['1.0', '2.0', '3.2', '4.5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-145', prompt: 'What percentage of global emissions are caused by deforestation?', options: ['5%', '11%', '20%', '30%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-146', prompt: 'How many species of mammals are there on Earth (roughly)?', options: ['3,000', '6,400', '10,000', '15,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-147', prompt: 'What is the highest recorded barometric pressure on Earth (hPa)?', options: ['1030', '1054', '1084', '1100'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-148', prompt: 'How many lightning strikes hit an airplane on average per year?', options: ['1', '5', '10', '20'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-149', prompt: 'What percentage of the world\'s wetlands have been lost since 1700?', options: ['25%', '45%', '65%', '85%'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-150', prompt: 'How many tons of carbon are stored in the world\'s soils (billions)?', options: ['1,000', '2,500', '4,000', '5,500'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-151', prompt: 'What is the deepest recorded earthquake (km)?', options: ['300', '500', '735', '1000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-152', prompt: 'How many people are exposed to floods globally (millions)?', options: ['250', '500', '850', '1,470'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-153', prompt: 'What percentage of plastic ever produced has been recycled?', options: ['5%', '9%', '15%', '25%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-154', prompt: 'How many tons of aluminum are produced globally per year (millions)?', options: ['20', '45', '65', '100'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-155', prompt: 'What is the average wind speed in Antarctica (km/h)?', options: ['15', '30', '50', '75'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-156', prompt: 'How many million tons of bananas are produced globally each year?', options: ['50', '80', '115', '150'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-157', prompt: 'What percentage of Earth\'s surface is covered by clouds at any given time?', options: ['35%', '50%', '67%', '80%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-158', prompt: 'How many days does it take for a drop of water to travel the global conveyor belt?', options: ['10,000', '100,000', '365,000', '1,000,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-159', prompt: 'What is the average thickness of the oceanic crust (km)?', options: ['2', '7', '15', '25'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-160', prompt: 'How many people depend on forests for their livelihoods (billions)?', options: ['0.5', '1.0', '1.6', '2.5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-161', prompt: 'What percentage of the world\'s fresh water is in the Great Lakes of Africa?', options: ['5%', '15%', '25%', '35%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-162', prompt: 'How many cubic kilometers of water does the Amazon River discharge daily?', options: ['5', '17', '35', '50'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-163', prompt: 'What is the highest recorded tsunami wave (meters)?', options: ['30', '150', '300', '524'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-164', prompt: 'How many million tons of meat are produced globally each year?', options: ['150', '250', '350', '500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-165', prompt: 'What percentage of global coral reefs are located in the Coral Triangle?', options: ['25%', '45%', '76%', '90%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-166', prompt: 'How many people are employed in the global fishing industry (millions)?', options: ['20', '60', '100', '150'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-167', prompt: 'What is the average lifespan of a hurricane (days)?', options: ['3', '9', '15', '25'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-168', prompt: 'How many million hectares of land burn globally in wildfires each year?', options: ['150', '350', '500', '750'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-169', prompt: 'What percentage of Earth\'s history has seen the presence of life?', options: ['25%', '50%', '80%', '95%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-170', prompt: 'How many people breathe polluted air daily (billions)?', options: ['1.5', '3.5', '5.5', '7.0'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-171', prompt: 'What is the highest elevation a bird has been recorded flying (meters)?', options: ['6,500', '8,848', '11,277', '15,000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-172', prompt: 'How many million tons of paper are produced globally each year?', options: ['100', '250', '400', '600'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-173', prompt: 'What percentage of the world\'s fresh water is in the polar ice caps?', options: ['45%', '55%', '68%', '85%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-174', prompt: 'How many km of tectonic plate boundaries exist on Earth?', options: ['30,000', '65,000', '100,000', '150,000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-175', prompt: 'What is the maximum recorded lifespan of a bowhead whale (years)?', options: ['100', '150', '211', '350'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-176', prompt: 'How many million tons of apples are produced globally each year?', options: ['50', '90', '150', '200'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-177', prompt: 'What percentage of global energy is consumed by the United States?', options: ['10%', '16%', '25%', '35%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-178', prompt: 'How many days a year on average does it rain in the Amazon rainforest?', options: ['100', '150', '200', '250'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-179', prompt: 'What is the largest recorded snowflake diameter (inches)?', options: ['5', '8', '15', '20'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-180', prompt: 'How many trees are in the Amazon rainforest (billions)?', options: ['100', '250', '390', '500'], correctIndex: 2 }

];

export const pl: DropPackCard[] = [

    { id: 'drop-our-changing-planet-001', prompt: 'Ile drzew rośnie obecnie na Ziemi (w przybliżeniu)?', options: ['300 miliardów', '1 bilion', '3 biliony', '7 bilionów'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-002', prompt: 'Ilu ludzi mogłoby wyżywić zasoby Ziemi, gdyby każdy żył jak Amerykanin?', options: ['1,5 miliarda', '2,5 miliarda', '4 miliardy', '7 miliardów'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-003', prompt: 'Jaka jest średnia głębokość oceanów na świecie (metry)?', options: ['1 200', '3 682', '5 400', '8 200'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-004', prompt: 'Jaki procent powierzchni Ziemi pokrywa woda?', options: ['55%', '61%', '71%', '82%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-005', prompt: 'Jaki procent wody na świecie zmagazynowany jest w oceanach?', options: ['85,2%', '91,4%', '96,5%', '99,1%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-006', prompt: 'Ile lat zajmuje rozkład plastikowej butelki w oceanie?', options: ['50', '150', '450', '1 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-007', prompt: 'Jaki procent lądów na Ziemi pokrywają lasy?', options: ['21%', '31%', '41%', '51%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-008', prompt: 'Ile milionów ton plastiku trafia do oceanów każdego roku?', options: ['2', '8', '15', '30'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-009', prompt: 'Jakie jest obecne stężenie CO2 w atmosferze (ppm)?', options: ['320', '380', '421', '495'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-010', prompt: 'O ile metrów podniósł się poziom mórz na świecie od 1880 roku?', options: ['0,05', '0,12', '0,23', '0,45'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-011', prompt: 'Jaki procent światowych emisji gazów cieplarnianych pochodzi z rolnictwa?', options: ['8%', '18%', '28%', '38%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-012', prompt: 'Ile gatunków zwierząt i roślin wymiera szacunkowo każdego roku?', options: ['2 000', '10 000', '50 000', '100 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-013', prompt: 'O ile stopni Celsjusza wzrosła średnia globalna temperatura od 1880 roku?', options: ['0,5', '1,1', '1,8', '2,5'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-014', prompt: 'Jaki procent słodkiej wody na Ziemi znajduje się w lodowcach i lądolodach?', options: ['45%', '58%', '69%', '82%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-015', prompt: 'Ilu ludzi nie ma obecnie dostępu do bezpiecznie zarządzanej wody pitnej (miliardy)?', options: ['0,8', '1,4', '2,2', '3,5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-016', prompt: 'Jaki procent energii na świecie pochodzi ze źródeł odnawialnych?', options: ['12%', '19%', '29%', '42%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-017', prompt: 'Ile kilometrów kwadratowych lasów deszczowych znika w każdej minucie?', options: ['15', '27', '35', '50'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-018', prompt: 'Jaki procent oceanów pozostaje niezbadany?', options: ['50%', '65%', '80%', '95%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-019', prompt: 'Ile aktywnych wulkanów znajduje się na Ziemi?', options: ['500', '1 350', '2 500', '4 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-020', prompt: 'Jaka jest maksymalna głębokość Rowu Mariańskiego (metry)?', options: ['8 848', '10 935', '12 500', '14 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-021', prompt: 'Ile uderzeń piorunów występuje na Ziemi w ciągu jednej doby?', options: ['1 milion', '3 miliony', '8 milionów', '15 milionów'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-022', prompt: 'Jakie jest średnie zasolenie oceanów (gramy na litr)?', options: ['25', '35', '45', '55'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-023', prompt: 'Ile lat temu zakończyła się ostatnia epoka lodowcowa?', options: ['8 000', '11 500', '15 000', '25 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-024', prompt: 'Jaki procent lądów na Ziemi klasyfikuje się jako pustynie?', options: ['15%', '25%', '33%', '45%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-025', prompt: 'Ile milionów ton elektrośmieci generuje świat każdego roku?', options: ['25', '40', '62', '85'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-026', prompt: 'Jaka jest średnia grubość warstwy ozonowej (jednostki Dobsona)?', options: ['150', '300', '450', '600'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-027', prompt: 'Ile kilometrów sześciennych wody znajduje się w atmosferze?', options: ['8 500', '12 900', '15 000', '20 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-028', prompt: 'Jaki procent lasów deszczowych Amazonii zniknął w ciągu ostatnich 50 lat?', options: ['10%', '17%', '25%', '35%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-029', prompt: 'Ile megaton metanu rocznie emitują zwierzęta hodowlane?', options: ['50', '80', '115', '150'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-030', prompt: 'Jaki procent światowej energii elektrycznej zużywa internet?', options: ['2%', '5%', '10%', '15%'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-031', prompt: 'Ile kilogramów śmieci produkuje dziennie przeciętny człowiek?', options: ['1', '2', '3,5', '5'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-032', prompt: 'Jaki procent raf koralowych na świecie uległ już zniszczeniu?', options: ['25%', '50%', '75%', '90%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-033', prompt: 'Ile kilometrów kwadratowych zajmuje Wielka Pacyficzna Plama Śmieci?', options: ['500 000', '1 000 000', '1 600 000', '2 500 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-034', prompt: 'Jaki jest średni wiek drzewa w dzikim lesie (lat)?', options: ['50', '100', '150', '200'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-035', prompt: 'Ilu ludzi może zostać uchodźcami klimatycznymi do 2050 roku (miliony)?', options: ['50', '140', '216', '500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-036', prompt: 'Jaki procent produkowanej na świecie żywności marnuje się?', options: ['15%', '33%', '50%', '65%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-037', prompt: 'Ile dzikich tygrysów żyje obecnie na wolności na całym świecie?', options: ['2 500', '4 500', '5 574', '10 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-038', prompt: 'Jaki procent światowej populacji żyje na obszarach przybrzeżnych?', options: ['25%', '40%', '55%', '70%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-039', prompt: 'Ile milionów baryłek ropy naftowej zużywa świat każdego dnia?', options: ['50', '75', '102', '130'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-040', prompt: 'Jaka jest średnica Ziemi na równiku (km)?', options: ['6 371', '10 500', '12 756', '15 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-041', prompt: 'Ile minut zajmuje Ziemi jeden pełny obrót wokół własnej osi (doba gwiazdowa)?', options: ['1 400', '1 436', '1 440', '1452'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-042', prompt: 'Jaka jest masa ziemskiej atmosfery (miliardy megaton)?', options: ['1,5', '5,1', '10,2', '25,5'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-043', prompt: 'Jaki procent ziemskiej biomasy stanowią ludzie?', options: ['0,01%', '0,1%', '1%', '5%'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-044', prompt: 'Ile trzęsień ziemi o różnej sile występuje szacunkowo każdego dnia?', options: ['50', '100', '150', '200'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-045', prompt: 'Jaka jest średnia prędkość orbitalna Ziemi wokół Słońca (km/h)?', options: ['50 000', '85 000', '107 000', '150 000'], correctIndex: 2 }
,

    { id: 'drop-our-changing-planet-046', prompt: 'Jaki procent zasobów słodkiej wody na Ziemi wykorzystuje rolnictwo?', options: ['40%', '55%', '70%', '85%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-047', prompt: 'Ile ton lodu traci Antarktyda każdego roku (miliardy)?', options: ['50', '150', '250', '350'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-048', prompt: 'Jaka jest najwyższa zarejestrowana prędkość wiatru w tornadzie (km/h)?', options: ['350', '484', '550', '620'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-049', prompt: 'Ilu ludzi na świecie traktuje ryby z oceanów jako główne źródło białka (miliardy)?', options: ['1', '2', '3', '4'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-050', prompt: 'Jaki procent światowych gazów cieplarnianych pochodzi z transportu?', options: ['10%', '15%', '24%', '35%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-051', prompt: 'Ile megamiast (ponad 10 mln mieszkańców) istnieje obecnie na świecie?', options: ['15', '25', '33', '45'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-052', prompt: 'Jaki procent powierzchni Ziemi jest trwale pokryty lodem?', options: ['5%', '10%', '15%', '20%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-053', prompt: 'Ile litrów wody potrzeba, by wyprodukować jeden kilogram wołowiny?', options: ['2 500', '5 000', '10 000', '15 400'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-054', prompt: 'Jaka była najniższa temperatura kiedykolwiek odnotowana na Ziemi (°C)?', options: ['-75,2', '-89,2', '-98,6', '-105,4'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-055', prompt: 'Ile ton pyłu meteorytowego spada na Ziemię każdego dnia?', options: ['10', '60', '150', '300'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-056', prompt: 'Jaki procent światowej populacji zamieszkuje półkulę północną?', options: ['60%', '75%', '90%', '98%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-057', prompt: 'Ile miliardów galonów wody zużywa ludzkość każdego dnia?', options: ['500', '1 000', '2 500', '4 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-058', prompt: 'Jaka jest średnia grubość pokrywy lodowej na Antarktydzie (metry)?', options: ['1 000', '1 500', '2 160', '3 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-059', prompt: 'Ile dni kropla wody spędza w oceanie zanim odparuje?', options: ['100', '500', '1 500', '3 000'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-060', prompt: 'Jaki procent światowych raf koralowych znajduje się w Wielkiej Rafie Koralowej?', options: ['5%', '10%', '15%', '25%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-061', prompt: 'Ile ton metrycznych CO2 emituje rocznie przeciętny człowiek?', options: ['2,5', '4,7', '7,2', '10,5'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-062', prompt: 'Jaka jest całkowita masa plastiku w oceanach (miliony ton)?', options: ['25', '75', '150', '300'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-063', prompt: 'Ile milionów ludzi przedwcześnie umiera co roku z powodu zanieczyszczenia powietrza?', options: ['2', '4', '7', '10'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-064', prompt: 'Jaki procent światowych lasów został zniszczony od początku cywilizacji?', options: ['25%', '35%', '46%', '60%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-065', prompt: 'Ile gatunków roślin szacunkowo istnieje na Ziemi?', options: ['150 000', '300 000', '400 000', '600 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-066', prompt: 'Jaka jest średnia grubość skorupy ziemskiej (km)?', options: ['15', '30', '50', '75'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-067', prompt: 'Ile razy w roku piorun uderza w Empire State Building?', options: ['5', '10', '25', '50'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-068', prompt: 'Jaki procent aktywności wulkanicznej Ziemi ma miejsce w oceanach?', options: ['50%', '65%', '80%', '95%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-069', prompt: 'O ile milimetrów Księżyc oddala się od Ziemi każdego roku?', options: ['15', '25', '38', '50'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-070', prompt: 'Jaka jest całkowita objętość wody na Ziemi (miliony km³)?', options: ['500', '1 000', '1 386', '2 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-071', prompt: 'Na ile dni przeciętne duże miasto posiada zapasy żywności?', options: ['3', '7', '14', '30'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-072', prompt: 'Jaki procent ziemi rolnej na świecie jest używany na potrzeby inwentarza żywego?', options: ['45%', '55%', '65%', '77%'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-073', prompt: 'Ile ton złota jest rozpuszczonych w oceanach na całym świecie?', options: ['1 000', '5 000', '10 000', '20 000'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-074', prompt: 'Jaka była najwyższa zarejestrowana fala na której surfowano (metry)?', options: ['18', '24', '31', '40'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-075', prompt: 'Ile kilometrów naczyń krwionośnych znajduje się w ludzkim ciele?', options: ['50 000', '80 000', '100 000', '150 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-076', prompt: 'Jaki procent energii na świecie pochodzi z energii jądrowej?', options: ['5%', '10%', '15%', '20%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-077', prompt: 'Ile litrów wody potrzeba do wyprodukowania jednego bawełnianego t-shirtu?', options: ['500', '1 200', '2 700', '5 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-078', prompt: 'Jaka jest średnia żywotność nowoczesnego panelu słonecznego (lata)?', options: ['15', '25', '35', '50'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-079', prompt: 'Ile milionów ludzi na świecie nie ma dostępu do elektryczności?', options: ['250', '500', '770', '1 200'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-080', prompt: 'Jaki procent tlenu na świecie produkuje las amazoński?', options: ['10%', '20%', '30%', '40%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-081', prompt: 'Ile aktywnych satelitów krąży obecnie wokół Ziemi?', options: ['2 500', '5 000', '7 500', '10 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-082', prompt: 'Do jakiej maksymalnej głębokości dotarł człowiek w oceanie (metry)?', options: ['8 500', '9 800', '10 928', '11 500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-083', prompt: 'Ile ton jedzenia na świecie marnuje się w każdej sekundzie?', options: ['20', '40', '65', '100'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-084', prompt: 'Jaki procent ludności świata żyje w skrajnym ubóstwie?', options: ['5%', '9%', '15%', '22%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-085', prompt: 'Ile litrów powietrza wdycha człowiek w ciągu jednego dnia?', options: ['5 000', '8 000', '11 000', '15 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-086', prompt: 'Z jaką prędkością porusza się najszybsze zwierzę na Ziemi (km/h)?', options: ['150', '250', '320', '389'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-087', prompt: 'Ile gatunków mrówek żyje na Ziemi?', options: ['5 000', '10 000', '14 000', '20 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-088', prompt: 'Jaki procent ciał ludzi zbudowany jest z gwiezdnego pyłu?', options: ['50%', '75%', '97%', '100%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-089', prompt: 'Ile tysięcy mil wybrzeża ma Ziemia?', options: ['200', '350', '500', '750'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-090', prompt: 'Jaka jest długość największego żyjącego organizmu na Ziemi (km)?', options: ['1 000', '2 300', '3 500', '5 000'], correctIndex: 1 }
,

    { id: 'drop-our-changing-planet-091', prompt: 'Jaki procent światowych zasobów słodkiej wody znajduje się w Jeziorze Bajkał?', options: ['5%', '10%', '20%', '30%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-092', prompt: 'Ile razy Ziemia zmieściłaby się w Słońcu?', options: ['10 000', '100 000', '1 000 000', '1 300 000'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-093', prompt: 'Jaka jest średnia długość życia na świecie (lata)?', options: ['65', '68', '73', '78'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-094', prompt: 'Ile ton wody przynosi ze sobą duży huragan (miliardy)?', options: ['1', '5', '10', '20'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-095', prompt: 'Jaki procent powierzchni Ziemi jest wykorzystywany pod rolnictwo?', options: ['15%', '25%', '38%', '50%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-096', prompt: 'Ile aktywnych wulkanów znajduje się w Pacyficznym Pierścieniu Ognia?', options: ['250', '452', '600', '800'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-097', prompt: 'Jaka była najwyższa temperatura zmierzona w oceanie (°C)?', options: ['150', '250', '350', '464'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-098', prompt: 'Ile milionów ton ryb wyławia się rocznie na świecie?', options: ['50', '90', '130', '200'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-099', prompt: 'Jaki procent globalnych odpadów jest obecnie poddawany recyklingowi?', options: ['9%', '19%', '29%', '39%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-100', prompt: 'Ile nowych gatunków odkrywa się każdego roku?', options: ['1 000', '5 000', '18 000', '50 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-101', prompt: 'Jaka jest średnia grubość pokrywy lodowej Antarktydy (metry)?', options: ['1 000', '2 100', '3 500', '4 800'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-102', prompt: 'Ilu ludzi żyje bez dostępu do podstawowych urządzeń sanitarnych (miliardy)?', options: ['1,5', '2,5', '3,6', '5,0'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-103', prompt: 'Jaki procent gatunków na Ziemi żyje w oceanach?', options: ['30%', '50%', '70%', '90%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-104', prompt: 'Ile milionów kilometrów dróg istnieje na świecie?', options: ['25', '45', '64', '85'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-105', prompt: 'Jaki procent populacji świata mieszka w miastach?', options: ['40%', '56%', '65%', '75%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-106', prompt: 'Ile miliardów drzew wycina się każdego roku na świecie?', options: ['5', '10', '15', '25'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-107', prompt: 'Jaka jest maksymalna prędkość wiatru zmierzona wewnątrz huraganu (km/h)?', options: ['250', '305', '345', '400'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-108', prompt: 'Ile miliardów funtów plastiku produkuje się rocznie na świecie?', options: ['200', '500', '850', '1 200'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-109', prompt: 'Jaki procent Amazonii został do tej pory wylesiony?', options: ['10%', '17%', '25%', '35%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-110', prompt: 'Ile dni zajęłoby obejście Ziemi wzdłuż równika piechotą?', options: ['500', '850', '1 050', '1 500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-111', prompt: 'Jaki procent energii elektrycznej na świecie pochodzi z węgla?', options: ['20%', '36%', '45%', '55%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-112', prompt: 'Ile milionów ton ubrań wyrzuca się co roku na świecie?', options: ['20', '45', '92', '150'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-113', prompt: 'Jaka jest średnia głębokość Morza Śródziemnego (metry)?', options: ['500', '1 000', '1 500', '2 500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-114', prompt: 'Ile milionów ton metrycznych stali produkuje się rocznie na świecie?', options: ['500', '1 000', '1 800', '2 500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-115', prompt: 'Jaki procent masy atmosfery Ziemi znajduje się w troposferze?', options: ['50%', '65%', '80%', '95%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-116', prompt: 'Ile osób na świecie umiera rocznie z powodu fal upałów?', options: ['100 000', '250 000', '489 000', '1 000 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-117', prompt: 'Jaki procent światowej wody słodkiej znajduje się w Wielkich Jeziorach Ameryki Północnej?', options: ['5%', '10%', '21%', '35%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-118', prompt: 'Ile ton jedzenia zjada człowiek w ciągu całego życia?', options: ['15', '25', '35', '50'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-119', prompt: 'Jaki jest rekord największych opadów deszczu w ciągu 24 godzin (metry)?', options: ['0,8', '1,2', '1,8', '2,5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-120', prompt: 'Ile milionów ton betonu produkuje się rocznie?', options: ['1 000', '2 000', '4 100', '6 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-121', prompt: 'Jaki procent gatunków na Ziemi wymarł w trakcie jej historii?', options: ['80%', '90%', '95%', '99%'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-122', prompt: 'Ile komercyjnych lotów startuje każdego dnia na świecie?', options: ['50 000', '100 000', '150 000', '200 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-123', prompt: 'Jaka jest średnia żywotność jednorazowego kubka do kawy (minuty)?', options: ['5', '10', '15', '30'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-124', prompt: 'Ile miliardów ton piasku zużywa się rocznie na świecie?', options: ['10', '25', '50', '80'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-125', prompt: 'Jaki procent światowej wody słodkiej płynie w dorzeczu Amazonki?', options: ['5%', '10%', '20%', '30%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-126', prompt: 'Przez ile dni w roku słońce nie zachodzi na biegunie północnym?', options: ['90', '120', '150', '186'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-127', prompt: 'Jaka jest najniższa zarejestrowana temperatura wody w oceanie (°C)?', options: ['-1', '-2', '-5', '-10'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-128', prompt: 'Ile gigaton lodu traci Grenlandia każdego roku?', options: ['50', '150', '280', '500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-129', prompt: 'Jaki procent powierzchni lądów na Ziemi zajmują miasta?', options: ['1%', '3%', '5%', '10%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-130', prompt: 'Ile milionów ton nawozów zużywa się rocznie na świecie?', options: ['50', '100', '200', '350'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-131', prompt: 'Jaki procent gatunków ptaków na świecie jest zagrożony wyginięciem?', options: ['5%', '13%', '25%', '40%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-132', prompt: 'Ile litrów wody potrzeba, by wyprodukować jednego smartfona?', options: ['1 000', '5 000', '12 000', '25 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-133', prompt: 'Jaka jest średnia grubość strefy oceanu, do której dociera słońce (metry)?', options: ['50', '100', '200', '500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-134', prompt: 'Ile milionów baryłek ropy wycieka co roku do oceanów?', options: ['0,5', '1,3', '2,5', '5,0'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-135', prompt: 'Przez jaki procent historii Ziemi planeta posiadała pokrywy lodowe?', options: ['10%', '20%', '30%', '50%'], correctIndex: 1 }
,

    { id: 'drop-our-changing-planet-136', prompt: 'Ile drobin mikroplastiku pływa szacunkowo w oceanach (biliony)?', options: ['5', '15', '51', '100'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-137', prompt: 'Jaka jest średnia globalna temperatura powierzchni oceanów (°C)?', options: ['12,5', '16,1', '20,1', '25,0'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-138', prompt: 'Ile ton miedzi jest szacunkowo rozpuszczonych w oceanach?', options: ['1 milion', '10 milionów', '50 milionów', '100 milionów'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-139', prompt: 'Jaki procent światowego tlenu pochodzi z Amazonii?', options: ['6%', '12%', '20%', '35%'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-140', prompt: 'O ile stopni ociepliła się Arktyka od 1979 roku (°C)?', options: ['1,0', '2,0', '3,0', '4,5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-141', prompt: 'Jaki procent upraw na świecie jest zależny od zapylania przez zwierzęta?', options: ['35%', '50%', '75%', '90%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-142', prompt: 'Ile milionów ton szkła produkuje się rocznie na świecie?', options: ['50', '130', '250', '400'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-143', prompt: 'Jaka jest długość najdłuższego łańcucha górskiego na Ziemi (km)?', options: ['7 000', '15 000', '40 000', '65 000'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-144', prompt: 'Ilu ludzi żyje na obszarach dotkniętych niedoborem wody (miliardy)?', options: ['1,0', '2,0', '3,2', '4,5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-145', prompt: 'Jaki procent globalnych emisji jest spowodowany wylesianiem?', options: ['5%', '11%', '20%', '30%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-146', prompt: 'Ile gatunków ssaków żyje obecnie na Ziemi (w przybliżeniu)?', options: ['3 000', '6 400', '10 000', '15 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-147', prompt: 'Jakie było najwyższe zanotowane ciśnienie atmosferyczne na Ziemi (hPa)?', options: ['1030', '1054', '1084', '1100'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-148', prompt: 'Ile razy średnio piorun uderza w samolot komercyjny w ciągu roku?', options: ['1', '5', '10', '20'], correctIndex: 0 },
    { id: 'drop-our-changing-planet-149', prompt: 'Jaki procent mokradeł na świecie został zniszczony od 1700 roku?', options: ['25%', '45%', '65%', '85%'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-150', prompt: 'Ile miliardów ton węgla zmagazynowanych jest w glebach na Ziemi?', options: ['1 000', '2 500', '4 000', '5 500'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-151', prompt: 'Na jakiej największej głębokości odnotowano trzęsienie ziemi (km)?', options: ['300', '500', '735', '1000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-152', prompt: 'Ilu ludzi na świecie jest narażonych na powodzie (miliony)?', options: ['250', '500', '850', '1 470'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-153', prompt: 'Jaki procent wyprodukowanego dotąd plastiku poddano recyklingowi?', options: ['5%', '9%', '15%', '25%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-154', prompt: 'Ile milionów ton aluminium produkuje się rocznie na świecie?', options: ['20', '45', '65', '100'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-155', prompt: 'Jaka jest średnia prędkość wiatru na Antarktydzie (km/h)?', options: ['15', '30', '50', '75'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-156', prompt: 'Ile milionów ton bananów produkuje się rocznie na świecie?', options: ['50', '80', '115', '150'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-157', prompt: 'Jaki procent powierzchni Ziemi jest średnio w danej chwili przykryty chmurami?', options: ['35%', '50%', '67%', '80%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-158', prompt: 'Ile dni zajmuje kropli wody pokonanie globalnego pasa transmisyjnego w oceanach?', options: ['10 000', '100 000', '365 000', '1 000 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-159', prompt: 'Jaka jest średnia grubość skorupy oceanicznej (km)?', options: ['2', '7', '15', '25'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-160', prompt: 'Ilu ludzi jest zależnych od lasów jako źródła utrzymania (miliardy)?', options: ['0,5', '1,0', '1,6', '2,5'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-161', prompt: 'Jaki procent słodkiej wody na Ziemi znajduje się w afrykańskich Wielkich Jeziorach?', options: ['5%', '15%', '25%', '35%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-162', prompt: 'Ile kilometrów sześciennych wody wylewa Amazonka do oceanu każdego dnia?', options: ['5', '17', '35', '50'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-163', prompt: 'Jak wysoka była najwyższa odnotowana fala tsunami (metry)?', options: ['30', '150', '300', '524'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-164', prompt: 'Ile milionów ton mięsa produkuje się rocznie na świecie?', options: ['150', '250', '350', '500'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-165', prompt: 'Jaki procent globalnych raf koralowych leży w Trójkącie Koralowym?', options: ['25%', '45%', '76%', '90%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-166', prompt: 'Ilu ludzi zatrudnia globalny przemysł rybny (miliony)?', options: ['20', '60', '100', '150'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-167', prompt: 'Jaki jest średni czas życia huraganu (dni)?', options: ['3', '9', '15', '25'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-168', prompt: 'Ile milionów hektarów ziemi płonie rocznie na świecie w pożarach?', options: ['150', '350', '500', '750'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-169', prompt: 'Przez jaki procent swojej historii Ziemia posiadała jakiekolwiek formy życia?', options: ['25%', '50%', '80%', '95%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-170', prompt: 'Ilu ludzi każdego dnia oddycha zanieczyszczonym powietrzem (miliardy)?', options: ['1,5', '3,5', '5,5', '7,0'], correctIndex: 3 },
    { id: 'drop-our-changing-planet-171', prompt: 'Na jakiej najwyższej wysokości odnotowano lot ptaka (metry)?', options: ['6 500', '8 848', '11 277', '15 000'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-172', prompt: 'Ile milionów ton papieru produkuje się rocznie na świecie?', options: ['100', '250', '400', '600'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-173', prompt: 'Jaki procent światowej słodkiej wody znajduje się w czapach polarnych?', options: ['45%', '55%', '68%', '85%'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-174', prompt: 'Ile kilometrów granic płyt tektonicznych znajduje się na Ziemi?', options: ['30 000', '65 000', '100 000', '150 000'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-175', prompt: 'Jaka była największa odnotowana długość życia wieloryba grenlandzkiego (lata)?', options: ['100', '150', '211', '350'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-176', prompt: 'Ile milionów ton jabłek produkuje się rocznie na świecie?', options: ['50', '90', '150', '200'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-177', prompt: 'Jaki procent światowej energii zużywają Stany Zjednoczone?', options: ['10%', '16%', '25%', '35%'], correctIndex: 1 },
    { id: 'drop-our-changing-planet-178', prompt: 'Przez ile dni w roku średnio pada deszcz w lesie amazońskim?', options: ['100', '150', '200', '250'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-179', prompt: 'Jaką średnicę miał największy zanotowany płatek śniegu (cale)?', options: ['5', '8', '15', '20'], correctIndex: 2 },
    { id: 'drop-our-changing-planet-180', prompt: 'Ile drzew znajduje się w lesie amazońskim (miliardy)?', options: ['100', '250', '390', '500'], correctIndex: 2 }

];
