// Premium pack: World Geography — The Drop.
// 180 original bilingual (EN/PL) questions. Each offers four real-world figures;
// exactly one is true, distractors are plausible near-values. Units live in the
// prompt so options stay clean numbers. Derived monolingual arrays feed
// PackDefinition.content; the store bridge zips en/pl by index at runtime.

import type { DropPackCard } from '../content';
import { getDropQuestionDifficulty } from '../difficulty';

interface BiCard {
    id: string;
    prompt: { en: string; pl: string };
    options: { en: string; pl: string }[];
    correctIndex: number;
}

const cards: BiCard[] = [
    // --- Rivers (length, km) ---
    { id: 'drop-world-geography-001', prompt: { en: 'How many sovereign countries share the island of Hispaniola?', pl: 'Ile suwerennych państw leży na wyspie Haiti (Hispanioli)?' }, options: [{ en: '1', pl: '1' }, { en: '2', pl: '2' }, { en: '3', pl: '3' }, { en: '4', pl: '4' }], correctIndex: 1 },
    { id: 'drop-world-geography-002', prompt: { en: 'Through how many countries does the main stem of the Amazon River flow?', pl: 'Przez ile państw przepływa główny nurt Amazonki?' }, options: [{ en: '1', pl: '1' }, { en: '3', pl: '3' }, { en: '5', pl: '5' }, { en: '7', pl: '7' }], correctIndex: 1 },
    { id: 'drop-world-geography-003', prompt: { en: 'Approximately how long is the Yangtze River (km)?', pl: 'Jaką przybliżoną długość ma Jangcy (km)?' }, options: [{ en: '4,800', pl: '4 800' }, { en: '5,500', pl: '5 500' }, { en: '6,300', pl: '6 300' }, { en: '7,100', pl: '7 100' }], correctIndex: 2 },
    { id: 'drop-world-geography-004', prompt: { en: 'Approximately how long is the Mississippi River itself (km)?', pl: 'Jaką przybliżoną długość ma sama Missisipi, bez jej dopływów (km)?' }, options: [{ en: '2,900', pl: '2 900' }, { en: '3,770', pl: '3 770' }, { en: '4,500', pl: '4 500' }, { en: '5,200', pl: '5 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-005', prompt: { en: 'Approximately how long is the Yellow River, Huang He (km)?', pl: 'Jaką przybliżoną długość ma Huang He, czyli Żółta Rzeka (km)?' }, options: [{ en: '4,000', pl: '4 000' }, { en: '4,800', pl: '4 800' }, { en: '5,464', pl: '5 464' }, { en: '6,300', pl: '6 300' }], correctIndex: 2 },
    { id: 'drop-world-geography-006', prompt: { en: 'Approximately how long is the Danube River (km)?', pl: 'Jaką przybliżoną długość ma Dunaj (km)?' }, options: [{ en: '1,900', pl: '1 900' }, { en: '2,850', pl: '2 850' }, { en: '3,600', pl: '3 600' }, { en: '4,200', pl: '4 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-007', prompt: { en: 'Approximately how long is the Volga River (km)?', pl: 'Jaką przybliżoną długość ma Wołga (km)?' }, options: [{ en: '2,400', pl: '2 400' }, { en: '3,530', pl: '3 530' }, { en: '4,200', pl: '4 200' }, { en: '5,000', pl: '5 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-008', prompt: { en: 'Approximately how long is the Congo River (km)?', pl: 'Jaką przybliżoną długość ma Kongo (km)?' }, options: [{ en: '3,500', pl: '3 500' }, { en: '4,700', pl: '4 700' }, { en: '5,600', pl: '5 600' }, { en: '6,400', pl: '6 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-009', prompt: { en: 'According to the Mekong River Commission, approximately how long is the Mekong River (km)?', pl: 'Jaką przybliżoną długość ma Mekong według Komisji Rzeki Mekong (km)?' }, options: [{ en: '3,200', pl: '3 200' }, { en: '4,900', pl: '4 900' }, { en: '5,600', pl: '5 600' }, { en: '6,400', pl: '6 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-010', prompt: { en: 'Approximately how long is the Rhine River (km)?', pl: 'Jaką przybliżoną długość ma Ren (km)?' }, options: [{ en: '800', pl: '800' }, { en: '1,233', pl: '1 233' }, { en: '1,700', pl: '1 700' }, { en: '2,200', pl: '2 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-011', prompt: { en: 'Approximately how long is the Ganges River itself (km)?', pl: 'Jaką przybliżoną długość ma sam Ganges, bez Brahmaputry (km)?' }, options: [{ en: '1,800', pl: '1 800' }, { en: '2,510', pl: '2 510' }, { en: '3,200', pl: '3 200' }, { en: '4,000', pl: '4 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-012', prompt: { en: 'Approximately how long is the Vistula River (km)?', pl: 'Jaką przybliżoną długość ma Wisła (km)?' }, options: [{ en: '760', pl: '760' }, { en: '1,047', pl: '1 047' }, { en: '1,350', pl: '1 350' }, { en: '1,600', pl: '1 600' }], correctIndex: 1 },
    { id: 'drop-world-geography-013', prompt: { en: 'Approximately how long is the Seine River (km)?', pl: 'Jaką przybliżoną długość ma Sekwana (km)?' }, options: [{ en: '480', pl: '480' }, { en: '777', pl: '777' }, { en: '1,100', pl: '1 100' }, { en: '1,400', pl: '1 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-014', prompt: { en: 'Approximately how long is the Thames River (km)?', pl: 'Jaką przybliżoną długość ma Tamiza (km)?' }, options: [{ en: '215', pl: '215' }, { en: '346', pl: '346' }, { en: '480', pl: '480' }, { en: '620', pl: '620' }], correctIndex: 1 },
    { id: 'drop-world-geography-015', prompt: { en: 'Approximately how long is the Niger River (km)?', pl: 'Jaką przybliżoną długość ma Niger (km)?' }, options: [{ en: '3,000', pl: '3 000' }, { en: '4,180', pl: '4 180' }, { en: '5,200', pl: '5 200' }, { en: '6,300', pl: '6 300' }], correctIndex: 1 },
    { id: 'drop-world-geography-016', prompt: { en: 'Approximately how long is the Zambezi River (km)?', pl: 'Jaką przybliżoną długość ma Zambezi (km)?' }, options: [{ en: '1,800', pl: '1 800' }, { en: '2,574', pl: '2 574' }, { en: '3,300', pl: '3 300' }, { en: '4,100', pl: '4 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-017', prompt: { en: 'Approximately how long is the Murray River in Australia (km)?', pl: 'Jaką przybliżoną długość ma rzeka Murray w Australii (km)?' }, options: [{ en: '1,700', pl: '1 700' }, { en: '2,508', pl: '2 508' }, { en: '3,300', pl: '3 300' }, { en: '4,000', pl: '4 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-018', prompt: { en: 'Approximately how long is the Colorado River (km)?', pl: 'Jaką przybliżoną długość ma Kolorado (km)?' }, options: [{ en: '1,600', pl: '1 600' }, { en: '2,330', pl: '2 330' }, { en: '3,100', pl: '3 100' }, { en: '3,900', pl: '3 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-019', prompt: { en: 'Approximately how long is the Rio Grande (km)?', pl: 'Jaką przybliżoną długość ma Rio Grande (km)?' }, options: [{ en: '2,200', pl: '2 200' }, { en: '3,051', pl: '3 051' }, { en: '3,900', pl: '3 900' }, { en: '4,700', pl: '4 700' }], correctIndex: 1 },
    { id: 'drop-world-geography-020', prompt: { en: 'Approximately how long is the Elbe River (km)?', pl: 'Jaką przybliżoną długość ma Łaba (km)?' }, options: [{ en: '720', pl: '720' }, { en: '1,094', pl: '1 094' }, { en: '1,500', pl: '1 500' }, { en: '1,900', pl: '1 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-021', prompt: { en: 'Approximately how long is the Loire River (km)?', pl: 'Jaką przybliżoną długość ma Loara (km)?' }, options: [{ en: '680', pl: '680' }, { en: '1,012', pl: '1 012' }, { en: '1,400', pl: '1 400' }, { en: '1,800', pl: '1 800' }], correctIndex: 1 },
    { id: 'drop-world-geography-022', prompt: { en: 'Approximately how long is the Po River in Italy (km)?', pl: 'Jaką przybliżoną długość ma Pad we Włoszech (km)?' }, options: [{ en: '420', pl: '420' }, { en: '652', pl: '652' }, { en: '880', pl: '880' }, { en: '1,100', pl: '1 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-023', prompt: { en: 'Approximately how long is the Indus River (km)?', pl: 'Jaką przybliżoną długość ma Indus (km)?' }, options: [{ en: '2,300', pl: '2 300' }, { en: '3,180', pl: '3 180' }, { en: '4,100', pl: '4 100' }, { en: '5,000', pl: '5 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-024', prompt: { en: 'Approximately how long is the Brahmaputra River (km)?', pl: 'Jaką przybliżoną długość ma Brahmaputra (km)?' }, options: [{ en: '2,100', pl: '2 100' }, { en: '2,900', pl: '2 900' }, { en: '3,700', pl: '3 700' }, { en: '4,500', pl: '4 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-025', prompt: { en: 'Approximately how long is the Lena River (km)?', pl: 'Jaką przybliżoną długość ma Lena (km)?' }, options: [{ en: '3,200', pl: '3 200' }, { en: '4,400', pl: '4 400' }, { en: '5,300', pl: '5 300' }, { en: '6,200', pl: '6 200' }], correctIndex: 1 },

    // --- Country area (million sq km) ---
    { id: 'drop-world-geography-026', prompt: { en: 'What is the approximate total area of Russia (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Rosji (mln km²)?' }, options: [{ en: '11.0', pl: '11,0' }, { en: '14.5', pl: '14,5' }, { en: '17.1', pl: '17,1' }, { en: '21.3', pl: '21,3' }], correctIndex: 2 },
    { id: 'drop-world-geography-027', prompt: { en: 'What is the approximate total area of Canada (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Kanady (mln km²)?' }, options: [{ en: '7.7', pl: '7,7' }, { en: '10.0', pl: '10,0' }, { en: '12.5', pl: '12,5' }, { en: '15.1', pl: '15,1' }], correctIndex: 1 },
    { id: 'drop-world-geography-028', prompt: { en: 'What is the approximate total area of China (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Chin (mln km²)?' }, options: [{ en: '6.4', pl: '6,4' }, { en: '8.1', pl: '8,1' }, { en: '9.6', pl: '9,6' }, { en: '11.2', pl: '11,2' }], correctIndex: 2 },
    { id: 'drop-world-geography-029', prompt: { en: 'What is the approximate total area of the USA (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Stanów Zjednoczonych (mln km²)?' }, options: [{ en: '8.4', pl: '8,4' }, { en: '9.8', pl: '9,8' }, { en: '11.5', pl: '11,5' }, { en: '13.0', pl: '13,0' }], correctIndex: 1 },
    { id: 'drop-world-geography-030', prompt: { en: 'What is the approximate total area of Brazil (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Brazylii (mln km²)?' }, options: [{ en: '6.2', pl: '6,2' }, { en: '7.3', pl: '7,3' }, { en: '8.5', pl: '8,5' }, { en: '9.9', pl: '9,9' }], correctIndex: 2 },
    { id: 'drop-world-geography-031', prompt: { en: 'What is the approximate total area of Australia (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Australii (mln km²)?' }, options: [{ en: '5.9', pl: '5,9' }, { en: '7.7', pl: '7,7' }, { en: '9.2', pl: '9,2' }, { en: '10.8', pl: '10,8' }], correctIndex: 1 },
    { id: 'drop-world-geography-032', prompt: { en: 'What is the approximate total area of India (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Indii (mln km²)?' }, options: [{ en: '2.1', pl: '2,1' }, { en: '3.3', pl: '3,3' }, { en: '4.6', pl: '4,6' }, { en: '5.8', pl: '5,8' }], correctIndex: 1 },
    { id: 'drop-world-geography-033', prompt: { en: 'What is the approximate total area of Argentina (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Argentyny (mln km²)?' }, options: [{ en: '1.9', pl: '1,9' }, { en: '2.8', pl: '2,8' }, { en: '3.7', pl: '3,7' }, { en: '4.5', pl: '4,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-034', prompt: { en: 'What is the approximate total area of Kazakhstan (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Kazachstanu (mln km²)?' }, options: [{ en: '1.8', pl: '1,8' }, { en: '2.7', pl: '2,7' }, { en: '3.5', pl: '3,5' }, { en: '4.2', pl: '4,2' }], correctIndex: 1 },
    { id: 'drop-world-geography-035', prompt: { en: 'What is the approximate total area of Algeria, Africa’s largest country (million sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Algierii, największego państwa Afryki (mln km²)?' }, options: [{ en: '1.6', pl: '1,6' }, { en: '2.4', pl: '2,4' }, { en: '3.1', pl: '3,1' }, { en: '3.9', pl: '3,9' }], correctIndex: 1 },

    // --- Country area (thousand sq km) ---
    { id: 'drop-world-geography-036', prompt: { en: 'What is the approximate area of metropolitan France, including Corsica (thousand km²)?', pl: 'Jaka jest przybliżona powierzchnia Francji metropolitalnej wraz z Korsyką (tys. km²)?' }, options: [{ en: '430', pl: '430' }, { en: '552', pl: '552' }, { en: '690', pl: '690' }, { en: '820', pl: '820' }], correctIndex: 1 },
    { id: 'drop-world-geography-037', prompt: { en: 'What is the approximate total area of Poland (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Polski (tys. km²)?' }, options: [{ en: '240', pl: '240' }, { en: '312', pl: '312' }, { en: '390', pl: '390' }, { en: '460', pl: '460' }], correctIndex: 1 },
    { id: 'drop-world-geography-038', prompt: { en: 'What is the approximate total area of Germany (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Niemiec (tys. km²)?' }, options: [{ en: '270', pl: '270' }, { en: '357', pl: '357' }, { en: '440', pl: '440' }, { en: '520', pl: '520' }], correctIndex: 1 },
    { id: 'drop-world-geography-039', prompt: { en: 'What is the approximate total area of Japan (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Japonii (tys. km²)?' }, options: [{ en: '290', pl: '290' }, { en: '378', pl: '378' }, { en: '460', pl: '460' }, { en: '540', pl: '540' }], correctIndex: 1 },
    { id: 'drop-world-geography-040', prompt: { en: 'What is the approximate area of the United Kingdom (thousand km²)?', pl: 'Jaka jest przybliżona powierzchnia Zjednoczonego Królestwa (tys. km²)?' }, options: [{ en: '180', pl: '180' }, { en: '243', pl: '243' }, { en: '310', pl: '310' }, { en: '380', pl: '380' }], correctIndex: 1 },
    { id: 'drop-world-geography-041', prompt: { en: 'What is the approximate total area of Italy (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Włoch (tys. km²)?' }, options: [{ en: '230', pl: '230' }, { en: '301', pl: '301' }, { en: '380', pl: '380' }, { en: '450', pl: '450' }], correctIndex: 1 },
    { id: 'drop-world-geography-042', prompt: { en: 'What is the approximate total area of Spain (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Hiszpanii (tys. km²)?' }, options: [{ en: '390', pl: '390' }, { en: '506', pl: '506' }, { en: '620', pl: '620' }, { en: '740', pl: '740' }], correctIndex: 1 },
    { id: 'drop-world-geography-043', prompt: { en: 'What is the approximate total area of Greece (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Grecji (tys. km²)?' }, options: [{ en: '95', pl: '95' }, { en: '132', pl: '132' }, { en: '175', pl: '175' }, { en: '210', pl: '210' }], correctIndex: 1 },
    { id: 'drop-world-geography-044', prompt: { en: 'What is the approximate total area of Iceland (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Islandii (tys. km²)?' }, options: [{ en: '70', pl: '70' }, { en: '103', pl: '103' }, { en: '140', pl: '140' }, { en: '180', pl: '180' }], correctIndex: 1 },
    { id: 'drop-world-geography-045', prompt: { en: 'What is the approximate total area of New Zealand (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia Nowej Zelandii (tys. km²)?' }, options: [{ en: '200', pl: '200' }, { en: '268', pl: '268' }, { en: '330', pl: '330' }, { en: '400', pl: '400' }], correctIndex: 1 },

    // --- Continent area (million sq km) ---
    { id: 'drop-world-geography-046', prompt: { en: 'What is the approximate area of Asia (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Azji (mln km²)?' }, options: [{ en: '33', pl: '33' }, { en: '44.6', pl: '44,6' }, { en: '56', pl: '56' }, { en: '68', pl: '68' }], correctIndex: 1 },
    { id: 'drop-world-geography-047', prompt: { en: 'What is the approximate area of Africa (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Afryki (mln km²)?' }, options: [{ en: '22', pl: '22' }, { en: '30.3', pl: '30,3' }, { en: '39', pl: '39' }, { en: '47', pl: '47' }], correctIndex: 1 },
    { id: 'drop-world-geography-048', prompt: { en: 'What is the approximate area of North America (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Ameryki Północnej (mln km²)?' }, options: [{ en: '18', pl: '18' }, { en: '24.7', pl: '24,7' }, { en: '31', pl: '31' }, { en: '38', pl: '38' }], correctIndex: 1 },
    { id: 'drop-world-geography-049', prompt: { en: 'What is the approximate area of South America (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Ameryki Południowej (mln km²)?' }, options: [{ en: '13', pl: '13' }, { en: '17.8', pl: '17,8' }, { en: '23', pl: '23' }, { en: '28', pl: '28' }], correctIndex: 1 },
    { id: 'drop-world-geography-050', prompt: { en: 'What is the approximate area of Antarctica (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Antarktydy (mln km²)?' }, options: [{ en: '10', pl: '10' }, { en: '14', pl: '14' }, { en: '18', pl: '18' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-051', prompt: { en: 'What is the approximate area of Europe (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Europy (mln km²)?' }, options: [{ en: '7.5', pl: '7,5' }, { en: '10.2', pl: '10,2' }, { en: '13.0', pl: '13,0' }, { en: '16.0', pl: '16,0' }], correctIndex: 1 },

    // --- Mountain heights (m) ---
    { id: 'drop-world-geography-052', prompt: { en: 'What is K2’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt K2 (m)?' }, options: [{ en: '7,900', pl: '7 900' }, { en: '8,200', pl: '8 200' }, { en: '8,611', pl: '8 611' }, { en: '9,000', pl: '9 000' }], correctIndex: 2 },
    { id: 'drop-world-geography-053', prompt: { en: 'What is Kilimanjaro’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Kilimandżaro (m)?' }, options: [{ en: '4,800', pl: '4 800' }, { en: '5,895', pl: '5 895' }, { en: '6,400', pl: '6 400' }, { en: '7,100', pl: '7 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-054', prompt: { en: 'What height was measured for Mont Blanc in September 2023, rounded to the nearest meter?', pl: 'Jaką wysokość Mont Blanc zmierzono we wrześniu 2023 roku, po zaokrągleniu do pełnego metra?' }, options: [{ en: '3,806 m', pl: '3 806 m' }, { en: '4,806 m', pl: '4 806 m' }, { en: '5,806 m', pl: '5 806 m' }, { en: '6,806 m', pl: '6 806 m' }], correctIndex: 1 },
    { id: 'drop-world-geography-055', prompt: { en: 'What is Denali’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Denali (m)?' }, options: [{ en: '5,200', pl: '5 200' }, { en: '6,190', pl: '6 190' }, { en: '7,000', pl: '7 000' }, { en: '7,800', pl: '7 800' }], correctIndex: 1 },
    { id: 'drop-world-geography-056', prompt: { en: 'What is Aconcagua’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Aconcagui (m)?' }, options: [{ en: '5,900', pl: '5 900' }, { en: '6,961', pl: '6 961' }, { en: '7,800', pl: '7 800' }, { en: '8,400', pl: '8 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-057', prompt: { en: 'What is Mount Elbrus’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Elbrusu (m)?' }, options: [{ en: '4,700', pl: '4 700' }, { en: '5,642', pl: '5 642' }, { en: '6,300', pl: '6 300' }, { en: '7,100', pl: '7 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-058', prompt: { en: 'What is Mount Fuji’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Fudżi (m)?' }, options: [{ en: '2,900', pl: '2 900' }, { en: '3,776', pl: '3 776' }, { en: '4,500', pl: '4 500' }, { en: '5,200', pl: '5 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-059', prompt: { en: 'What is the Matterhorn’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Matterhornu (m)?' }, options: [{ en: '3,600', pl: '3 600' }, { en: '4,478', pl: '4 478' }, { en: '5,200', pl: '5 200' }, { en: '5,900', pl: '5 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-060', prompt: { en: 'What is Mount Kosciuszko’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Góry Kościuszki (m)?' }, options: [{ en: '1,600', pl: '1 600' }, { en: '2,228', pl: '2 228' }, { en: '2,900', pl: '2 900' }, { en: '3,500', pl: '3 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-061', prompt: { en: 'What is Vinson Massif’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Masywu Vinsona (m)?' }, options: [{ en: '3,800', pl: '3 800' }, { en: '4,892', pl: '4 892' }, { en: '5,600', pl: '5 600' }, { en: '6,400', pl: '6 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-062', prompt: { en: 'What is Ben Nevis’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Ben Nevis (m)?' }, options: [{ en: '900', pl: '900' }, { en: '1,345', pl: '1 345' }, { en: '1,800', pl: '1 800' }, { en: '2,300', pl: '2 300' }], correctIndex: 1 },
    { id: 'drop-world-geography-063', prompt: { en: 'What is the elevation of Mytikas, Mount Olympus’s highest summit (m)?', pl: 'Na jakiej wysokości leży Mytikas, najwyższy szczyt Olimpu (m)?' }, options: [{ en: '2,100', pl: '2 100' }, { en: '2,917', pl: '2 917' }, { en: '3,600', pl: '3 600' }, { en: '4,200', pl: '4 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-064', prompt: { en: 'How high above sea level is Mauna Kea (m)?', pl: 'Na jaką wysokość nad poziom morza wznosi się Mauna Kea (m)?' }, options: [{ en: '3,400', pl: '3 400' }, { en: '4,207', pl: '4 207' }, { en: '5,100', pl: '5 100' }, { en: '5,900', pl: '5 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-065', prompt: { en: 'What is Mount Logan’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Góry Logana (m)?' }, options: [{ en: '4,900', pl: '4 900' }, { en: '5,959', pl: '5 959' }, { en: '6,800', pl: '6 800' }, { en: '7,500', pl: '7 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-066', prompt: { en: 'What is Mount Rainier’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Mount Rainier (m)?' }, options: [{ en: '3,500', pl: '3 500' }, { en: '4,392', pl: '4 392' }, { en: '5,200', pl: '5 200' }, { en: '6,000', pl: '6 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-067', prompt: { en: 'What is Cotopaxi’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Cotopaxi (m)?' }, options: [{ en: '4,900', pl: '4 900' }, { en: '5,897', pl: '5 897' }, { en: '6,700', pl: '6 700' }, { en: '7,500', pl: '7 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-068', prompt: { en: 'What is Mount Ararat’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Araratu (m)?' }, options: [{ en: '4,200', pl: '4 200' }, { en: '5,137', pl: '5 137' }, { en: '6,100', pl: '6 100' }, { en: '7,000', pl: '7 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-069', prompt: { en: 'Approximately what is Mount Vesuvius’s summit elevation above sea level (m)?', pl: 'Na jakiej przybliżonej wysokości nad poziomem morza leży szczyt Wezuwiusza (m)?' }, options: [{ en: '850', pl: '850' }, { en: '1,281', pl: '1 281' }, { en: '1,800', pl: '1 800' }, { en: '2,400', pl: '2 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-070', prompt: { en: 'What is the elevation of Maclear’s Beacon, Table Mountain’s highest point (m)?', pl: 'Na jakiej wysokości leży Maclear’s Beacon, najwyższy punkt Góry Stołowej (m)?' }, options: [{ en: '720', pl: '720' }, { en: '1,085', pl: '1 085' }, { en: '1,500', pl: '1 500' }, { en: '1,950', pl: '1 950' }], correctIndex: 1 },
    { id: 'drop-world-geography-071', prompt: { en: 'What is the summit elevation of Aoraki / Mount Cook above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Aoraki / Mount Cook (m)?' }, options: [{ en: '2,900', pl: '2 900' }, { en: '3,724', pl: '3 724' }, { en: '4,500', pl: '4 500' }, { en: '5,300', pl: '5 300' }], correctIndex: 1 },
    { id: 'drop-world-geography-072', prompt: { en: 'What is Mount Whitney’s summit elevation above sea level (m)?', pl: 'Na jakiej wysokości nad poziomem morza leży szczyt Mount Whitney (m)?' }, options: [{ en: '3,600', pl: '3 600' }, { en: '4,421', pl: '4 421' }, { en: '5,200', pl: '5 200' }, { en: '6,000', pl: '6 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-073', prompt: { en: 'According to the USGS, approximately how tall is Mauna Kea from its base on the ocean floor (m)?', pl: 'Jaką przybliżoną wysokość ma Mauna Kea od podstawy na dnie oceanu według USGS (m)?' }, options: [{ en: '8,400', pl: '8 400' }, { en: '10,210', pl: '10 210' }, { en: '12,000', pl: '12 000' }, { en: '14,000', pl: '14 000' }], correctIndex: 1 },

    // --- Lakes ---
    { id: 'drop-world-geography-074', prompt: { en: 'What is the maximum depth of Lake Baikal (m)?', pl: 'Jaka jest maksymalna głębokość jeziora Bajkał (m)?' }, options: [{ en: '900', pl: '900' }, { en: '1,300', pl: '1 300' }, { en: '1,642', pl: '1 642' }, { en: '2,100', pl: '2 100' }], correctIndex: 2 },
    { id: 'drop-world-geography-075', prompt: { en: 'What is the approximate surface area of the Caspian Sea (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Morza Kaspijskiego (tys. km²)?' }, options: [{ en: '210', pl: '210' }, { en: '371', pl: '371' }, { en: '520', pl: '520' }, { en: '680', pl: '680' }], correctIndex: 1 },
    { id: 'drop-world-geography-076', prompt: { en: 'What is the approximate surface area of Lake Superior (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Jeziora Górnego (tys. km²)?' }, options: [{ en: '58', pl: '58' }, { en: '82', pl: '82' }, { en: '110', pl: '110' }, { en: '140', pl: '140' }], correctIndex: 1 },
    { id: 'drop-world-geography-077', prompt: { en: 'What is the approximate surface area of Lake Victoria (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Jeziora Wiktorii (tys. km²)?' }, options: [{ en: '45', pl: '45' }, { en: '69', pl: '69' }, { en: '95', pl: '95' }, { en: '120', pl: '120' }], correctIndex: 1 },
    { id: 'drop-world-geography-078', prompt: { en: 'What is the maximum depth of Lake Tanganyika (m)?', pl: 'Jaka jest maksymalna głębokość jeziora Tanganika (m)?' }, options: [{ en: '950', pl: '950' }, { en: '1,470', pl: '1 470' }, { en: '1,900', pl: '1 900' }, { en: '2,400', pl: '2 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-079', prompt: { en: 'At approximately what elevation is Lake Titicaca’s surface (m)?', pl: 'Na jakiej przybliżonej wysokości leży lustro jeziora Titicaca (m)?' }, options: [{ en: '2,800', pl: '2 800' }, { en: '3,812', pl: '3 812' }, { en: '4,500', pl: '4 500' }, { en: '5,200', pl: '5 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-080', prompt: { en: 'Which range best describes the elevation of the Dead Sea shore below sea level?', pl: 'Który zakres najlepiej opisuje położenie brzegu Morza Martwego poniżej poziomu morza?' }, options: [{ en: 'Less than 100 m', pl: 'Mniej niż 100 m' }, { en: '100–250 m', pl: '100–250 m' }, { en: '400–500 m', pl: '400–500 m' }, { en: 'More than 800 m', pl: 'Ponad 800 m' }], correctIndex: 2 },
    { id: 'drop-world-geography-081', prompt: { en: 'What is the approximate surface area of Lake Geneva (sq km)?', pl: 'Jaka jest przybliżona powierzchnia Jeziora Genewskiego (km²)?' }, options: [{ en: '340', pl: '340' }, { en: '580', pl: '580' }, { en: '820', pl: '820' }, { en: '1,100', pl: '1 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-082', prompt: { en: 'What is the maximum depth of Loch Ness (m)?', pl: 'Jaka jest maksymalna głębokość Loch Ness (m)?' }, options: [{ en: '130', pl: '130' }, { en: '230', pl: '230' }, { en: '330', pl: '330' }, { en: '450', pl: '450' }], correctIndex: 1 },
    { id: 'drop-world-geography-083', prompt: { en: 'What is the approximate surface area of Lake Balaton (sq km)?', pl: 'Jaka jest przybliżona powierzchnia jeziora Balaton (km²)?' }, options: [{ en: '380', pl: '380' }, { en: '592', pl: '592' }, { en: '780', pl: '780' }, { en: '1,000', pl: '1 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-084', prompt: { en: 'What is the approximate surface area of Lake Michigan (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia jeziora Michigan (tys. km²)?' }, options: [{ en: '42', pl: '42' }, { en: '58', pl: '58' }, { en: '76', pl: '76' }, { en: '95', pl: '95' }], correctIndex: 1 },
    { id: 'drop-world-geography-085', prompt: { en: 'What is the approximate surface area of Lake Ontario (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia jeziora Ontario (tys. km²)?' }, options: [{ en: '13', pl: '13' }, { en: '19', pl: '19' }, { en: '27', pl: '27' }, { en: '36', pl: '36' }], correctIndex: 1 },
    { id: 'drop-world-geography-086', prompt: { en: 'What is the approximate surface area of Lake Erie (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia jeziora Erie (tys. km²)?' }, options: [{ en: '18', pl: '18' }, { en: '25.7', pl: '25,7' }, { en: '34', pl: '34' }, { en: '43', pl: '43' }], correctIndex: 1 },
    { id: 'drop-world-geography-087', prompt: { en: 'What is the maximum depth of the Caspian Sea (m)?', pl: 'Jaka jest maksymalna głębokość Morza Kaspijskiego (m)?' }, options: [{ en: '600', pl: '600' }, { en: '1,025', pl: '1 025' }, { en: '1,500', pl: '1 500' }, { en: '2,000', pl: '2 000' }], correctIndex: 1 },

    // --- Deserts and islands ---
    { id: 'drop-world-geography-088', prompt: { en: 'What is the approximate area of the Sahara (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Sahary (mln km²)?' }, options: [{ en: '6.1', pl: '6,1' }, { en: '7.7', pl: '7,7' }, { en: '9.2', pl: '9,2' }, { en: '11.0', pl: '11,0' }], correctIndex: 2 },
    { id: 'drop-world-geography-089', prompt: { en: 'What is the approximate area of the Gobi Desert (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia pustyni Gobi (mln km²)?' }, options: [{ en: '0.8', pl: '0,8' }, { en: '1.3', pl: '1,3' }, { en: '1.9', pl: '1,9' }, { en: '2.5', pl: '2,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-090', prompt: { en: 'What is the approximate area of the Arabian Desert (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Pustyni Arabskiej (mln km²)?' }, options: [{ en: '1.5', pl: '1,5' }, { en: '2.3', pl: '2,3' }, { en: '3.1', pl: '3,1' }, { en: '3.9', pl: '3,9' }], correctIndex: 1 },
    { id: 'drop-world-geography-091', prompt: { en: 'What is the approximate area of the Kalahari Desert (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia pustyni Kalahari (tys. km²)?' }, options: [{ en: '620', pl: '620' }, { en: '900', pl: '900' }, { en: '1,200', pl: '1 200' }, { en: '1,500', pl: '1 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-092', prompt: { en: 'What is the approximate area of Greenland, the world’s largest non-continental island (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Grenlandii, największej wyspy niebędącej kontynentem (mln km²)?' }, options: [{ en: '1.5', pl: '1,5' }, { en: '2.2', pl: '2,2' }, { en: '2.9', pl: '2,9' }, { en: '3.6', pl: '3,6' }], correctIndex: 1 },
    { id: 'drop-world-geography-093', prompt: { en: 'What is the approximate area of the island of New Guinea (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia wyspy Nowej Gwinei (tys. km²)?' }, options: [{ en: '540', pl: '540' }, { en: '786', pl: '786' }, { en: '1,020', pl: '1 020' }, { en: '1,300', pl: '1 300' }], correctIndex: 1 },
    { id: 'drop-world-geography-094', prompt: { en: 'What is the approximate area of Borneo (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Borneo (tys. km²)?' }, options: [{ en: '520', pl: '520' }, { en: '743', pl: '743' }, { en: '960', pl: '960' }, { en: '1,200', pl: '1 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-095', prompt: { en: 'What is the approximate area of Madagascar (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Madagaskaru (tys. km²)?' }, options: [{ en: '410', pl: '410' }, { en: '587', pl: '587' }, { en: '760', pl: '760' }, { en: '940', pl: '940' }], correctIndex: 1 },
    { id: 'drop-world-geography-096', prompt: { en: 'What is the approximate area of the island of Great Britain (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia wyspy Wielkiej Brytanii (tys. km²)?' }, options: [{ en: '150', pl: '150' }, { en: '209', pl: '209' }, { en: '280', pl: '280' }, { en: '350', pl: '350' }], correctIndex: 1 },
    { id: 'drop-world-geography-097', prompt: { en: 'What is the approximate area of Honshu, the main island of Japan (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Honsiu, głównej wyspy Japonii (tys. km²)?' }, options: [{ en: '160', pl: '160' }, { en: '228', pl: '228' }, { en: '300', pl: '300' }, { en: '380', pl: '380' }], correctIndex: 1 },
    { id: 'drop-world-geography-098', prompt: { en: 'What is the approximate area of Sri Lanka (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Sri Lanki (tys. km²)?' }, options: [{ en: '45', pl: '45' }, { en: '66', pl: '66' }, { en: '90', pl: '90' }, { en: '120', pl: '120' }], correctIndex: 1 },
    { id: 'drop-world-geography-099', prompt: { en: 'What is Cuba’s approximate total area as a country (thousand sq km)?', pl: 'Jaka jest przybliżona całkowita powierzchnia terytorium Kuby (tys. km²)?' }, options: [{ en: '78', pl: '78' }, { en: '110', pl: '110' }, { en: '145', pl: '145' }, { en: '185', pl: '185' }], correctIndex: 1 },
    { id: 'drop-world-geography-100', prompt: { en: 'What is the approximate area of Sicily (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Sycylii (tys. km²)?' }, options: [{ en: '18', pl: '18' }, { en: '25.7', pl: '25,7' }, { en: '34', pl: '34' }, { en: '43', pl: '43' }], correctIndex: 1 },
    { id: 'drop-world-geography-101', prompt: { en: 'What is the approximate area of Jamaica (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Jamajki (tys. km²)?' }, options: [{ en: '7', pl: '7' }, { en: '11', pl: '11' }, { en: '16', pl: '16' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-102', prompt: { en: 'According to the Philippine mapping agency NAMRIA, how many islands make up the Philippines?', pl: 'Ile wysp liczą Filipiny według filipińskiej agencji kartograficznej NAMRIA?' }, options: [{ en: '2,500', pl: '2 500' }, { en: '5,000', pl: '5 000' }, { en: '7,641', pl: '7 641' }, { en: '10,000', pl: '10 000' }], correctIndex: 2 },

    // --- Seas, oceans and trenches ---
    { id: 'drop-world-geography-103', prompt: { en: 'How many countries border Lake Chad?', pl: 'Ile państw leży nad jeziorem Czad?' }, options: [{ en: '2', pl: '2' }, { en: '3', pl: '3' }, { en: '4', pl: '4' }, { en: '5', pl: '5' }], correctIndex: 2 },
    { id: 'drop-world-geography-104', prompt: { en: 'What is the approximate surface area of the Pacific Ocean (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Oceanu Spokojnego (mln km²)?' }, options: [{ en: '120', pl: '120' }, { en: '165', pl: '165' }, { en: '200', pl: '200' }, { en: '240', pl: '240' }], correctIndex: 1 },
    { id: 'drop-world-geography-105', prompt: { en: 'What is the approximate surface area of the Atlantic Ocean including its marginal seas (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Oceanu Atlantyckiego wraz z morzami przyległymi (mln km²)?' }, options: [{ en: '76', pl: '76' }, { en: '106', pl: '106' }, { en: '140', pl: '140' }, { en: '175', pl: '175' }], correctIndex: 1 },
    { id: 'drop-world-geography-106', prompt: { en: 'What is the approximate surface area of the Indian Ocean (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Oceanu Indyjskiego (mln km²)?' }, options: [{ en: '50', pl: '50' }, { en: '70', pl: '70' }, { en: '92', pl: '92' }, { en: '115', pl: '115' }], correctIndex: 1 },
    { id: 'drop-world-geography-107', prompt: { en: 'What is the approximate surface area of the Mediterranean Sea (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Morza Śródziemnego (mln km²)?' }, options: [{ en: '1.6', pl: '1,6' }, { en: '2.5', pl: '2,5' }, { en: '3.4', pl: '3,4' }, { en: '4.3', pl: '4,3' }], correctIndex: 1 },
    { id: 'drop-world-geography-108', prompt: { en: 'What is the approximate surface area of the Caribbean Sea (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Morza Karaibskiego (mln km²)?' }, options: [{ en: '1.8', pl: '1,8' }, { en: '2.8', pl: '2,8' }, { en: '3.7', pl: '3,7' }, { en: '4.6', pl: '4,6' }], correctIndex: 1 },
    { id: 'drop-world-geography-109', prompt: { en: 'What is the approximate surface area of the South China Sea (million sq km)?', pl: 'Jaka jest przybliżona powierzchnia Morza Południowochińskiego (mln km²)?' }, options: [{ en: '2.4', pl: '2,4' }, { en: '3.5', pl: '3,5' }, { en: '4.6', pl: '4,6' }, { en: '5.7', pl: '5,7' }], correctIndex: 1 },
    { id: 'drop-world-geography-110', prompt: { en: 'What is the maximum depth of the Baltic Sea (m)?', pl: 'Jaka jest maksymalna głębokość Morza Bałtyckiego (m)?' }, options: [{ en: '280', pl: '280' }, { en: '459', pl: '459' }, { en: '640', pl: '640' }, { en: '820', pl: '820' }], correctIndex: 1 },
    { id: 'drop-world-geography-111', prompt: { en: 'According to a 2025 study combining seafloor mapping and dive data, what is the nominal depth of the Mediterranean’s deepest point (m)?', pl: 'Jaka jest nominalna głębokość najgłębszego punktu Morza Śródziemnego według badania z 2025 roku, łączącego mapowanie dna z danymi z nurkowania (m)?' }, options: [{ en: '4,200', pl: '4 200' }, { en: '5,122', pl: '5 122' }, { en: '6,300', pl: '6 300' }, { en: '7,400', pl: '7 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-112', prompt: { en: 'What is the approximate surface area of the Black Sea (thousand sq km)?', pl: 'Jaka jest przybliżona powierzchnia Morza Czarnego (tys. km²)?' }, options: [{ en: '300', pl: '300' }, { en: '436', pl: '436' }, { en: '580', pl: '580' }, { en: '740', pl: '740' }], correctIndex: 1 },
    { id: 'drop-world-geography-113', prompt: { en: 'What is the maximum depth of the Black Sea (m)?', pl: 'Jaka jest maksymalna głębokość Morza Czarnego (m)?' }, options: [{ en: '1,500', pl: '1 500' }, { en: '2,210', pl: '2 210' }, { en: '2,900', pl: '2 900' }, { en: '3,600', pl: '3 600' }], correctIndex: 1 },

    // --- Cities (population in millions / elevation) ---
    { id: 'drop-world-geography-114', prompt: { en: 'Through or along how many countries does the Danube flow?', pl: 'Przez terytorium lub wzdłuż granic ilu państw przepływa Dunaj?' }, options: [{ en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }, { en: '12', pl: '12' }], correctIndex: 2 },
    { id: 'drop-world-geography-115', prompt: { en: 'Through or along how many countries does the Rhine flow?', pl: 'Przez terytorium lub wzdłuż granic ilu państw przepływa Ren?' }, options: [{ en: '4', pl: '4' }, { en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }], correctIndex: 1 },
    { id: 'drop-world-geography-116', prompt: { en: 'How many countries share Lake Victoria?', pl: 'Na terytorium ilu państw leży Jezioro Wiktorii?' }, options: [{ en: '2', pl: '2' }, { en: '3', pl: '3' }, { en: '4', pl: '4' }, { en: '5', pl: '5' }], correctIndex: 1 },
    { id: 'drop-world-geography-117', prompt: { en: 'How many inhabited islands are in Spain’s Canary Islands?', pl: 'Ile zamieszkanych wysp liczy hiszpański archipelag Wysp Kanaryjskich?' }, options: [{ en: '6', pl: '6' }, { en: '7', pl: '7' }, { en: '8', pl: '8' }, { en: '9', pl: '9' }], correctIndex: 2 },
    { id: 'drop-world-geography-118', prompt: { en: 'How many boroughs make up New York City?', pl: 'Z ilu dzielnic administracyjnych składa się miasto Nowy Jork?' }, options: [{ en: '4', pl: '4' }, { en: '5', pl: '5' }, { en: '6', pl: '6' }, { en: '7', pl: '7' }], correctIndex: 1 },
    { id: 'drop-world-geography-119', prompt: { en: 'How many provinces does Ecuador have?', pl: 'Ile prowincji ma Ekwador?' }, options: [{ en: '18', pl: '18' }, { en: '21', pl: '21' }, { en: '24', pl: '24' }, { en: '27', pl: '27' }], correctIndex: 2 },
    { id: 'drop-world-geography-120', prompt: { en: 'How many territories does Canada have?', pl: 'Ile terytoriów ma Kanada?' }, options: [{ en: '2', pl: '2' }, { en: '3', pl: '3' }, { en: '4', pl: '4' }, { en: '5', pl: '5' }], correctIndex: 1 },
    { id: 'drop-world-geography-121', prompt: { en: 'How many emirates make up the United Arab Emirates?', pl: 'Z ilu emiratów składają się Zjednoczone Emiraty Arabskie?' }, options: [{ en: '5', pl: '5' }, { en: '6', pl: '6' }, { en: '7', pl: '7' }, { en: '8', pl: '8' }], correctIndex: 2 },
    { id: 'drop-world-geography-122', prompt: { en: 'How many cantons does Switzerland have?', pl: 'Ile kantonów ma Szwajcaria?' }, options: [{ en: '20', pl: '20' }, { en: '23', pl: '23' }, { en: '26', pl: '26' }, { en: '29', pl: '29' }], correctIndex: 2 },
    { id: 'drop-world-geography-123', prompt: { en: 'How many administrative districts does Belize have?', pl: 'Ile dystryktów administracyjnych ma Belize?' }, options: [{ en: '4', pl: '4' }, { en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }], correctIndex: 1 },
    { id: 'drop-world-geography-124', prompt: { en: 'At approximately what elevation is central Mexico City (m)?', pl: 'Na jakiej przybliżonej wysokości leży centrum miasta Meksyk (m)?' }, options: [{ en: '1,400', pl: '1 400' }, { en: '2,240', pl: '2 240' }, { en: '3,100', pl: '3 100' }, { en: '3,900', pl: '3 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-125', prompt: { en: 'At approximately what elevation is central La Paz, Bolivia (m)?', pl: 'Na jakiej przybliżonej wysokości leży centrum La Paz w Boliwii (m)?' }, options: [{ en: '2,500', pl: '2 500' }, { en: '3,640', pl: '3 640' }, { en: '4,800', pl: '4 800' }, { en: '5,900', pl: '5 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-126', prompt: { en: 'How many states does Australia have?', pl: 'Ile stanów ma Australia?' }, options: [{ en: '5', pl: '5' }, { en: '6', pl: '6' }, { en: '7', pl: '7' }, { en: '8', pl: '8' }], correctIndex: 1 },

    // --- Country populations ---
    { id: 'drop-world-geography-127', prompt: { en: 'How many countries share Lake Titicaca?', pl: 'Na terytorium ilu państw leży jezioro Titicaca?' }, options: [{ en: '1', pl: '1' }, { en: '2', pl: '2' }, { en: '3', pl: '3' }, { en: '4', pl: '4' }], correctIndex: 1 },
    { id: 'drop-world-geography-128', prompt: { en: 'How many sovereign countries share the island of Borneo?', pl: 'Na terytorium ilu suwerennych państw leży wyspa Borneo?' }, options: [{ en: '2', pl: '2' }, { en: '3', pl: '3' }, { en: '4', pl: '4' }, { en: '5', pl: '5' }], correctIndex: 1 },
    { id: 'drop-world-geography-129', prompt: { en: 'Through how many countries does the Mekong River flow?', pl: 'Przez ile państw przepływa Mekong?' }, options: [{ en: '4', pl: '4' }, { en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }], correctIndex: 1 },
    { id: 'drop-world-geography-130', prompt: { en: 'According to the Alpine Convention, how many countries do the Alps span?', pl: 'Przez ile państw rozciągają się Alpy według Konwencji Alpejskiej?' }, options: [{ en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }, { en: '12', pl: '12' }], correctIndex: 1 },
    { id: 'drop-world-geography-131', prompt: { en: 'Through how many countries do the Andes extend?', pl: 'Przez ile państw ciągną się Andy?' }, options: [{ en: '5', pl: '5' }, { en: '6', pl: '6' }, { en: '7', pl: '7' }, { en: '8', pl: '8' }], correctIndex: 2 },
    { id: 'drop-world-geography-132', prompt: { en: 'How many of Ireland’s 32 traditional counties are in the Republic of Ireland?', pl: 'Ile z 32 tradycyjnych hrabstw Irlandii leży w Republice Irlandii?' }, options: [{ en: '20', pl: '20' }, { en: '26', pl: '26' }, { en: '32', pl: '32' }, { en: '36', pl: '36' }], correctIndex: 1 },
    { id: 'drop-world-geography-133', prompt: { en: 'How many main islands make up Portugal’s Azores archipelago?', pl: 'Z ilu głównych wysp składa się portugalski archipelag Azorów?' }, options: [{ en: '7', pl: '7' }, { en: '8', pl: '8' }, { en: '9', pl: '9' }, { en: '10', pl: '10' }], correctIndex: 2 },
    { id: 'drop-world-geography-134', prompt: { en: 'How many provinces does the Netherlands have?', pl: 'Ile prowincji mają Niderlandy?' }, options: [{ en: '10', pl: '10' }, { en: '12', pl: '12' }, { en: '14', pl: '14' }, { en: '16', pl: '16' }], correctIndex: 1 },
    { id: 'drop-world-geography-135', prompt: { en: 'How many administrative regions does Greece have?', pl: 'Ile regionów administracyjnych ma Grecja?' }, options: [{ en: '9', pl: '9' }, { en: '11', pl: '11' }, { en: '13', pl: '13' }, { en: '15', pl: '15' }], correctIndex: 2 },
    { id: 'drop-world-geography-136', prompt: { en: 'How many counties does Liberia have?', pl: 'Ile hrabstw ma Liberia?' }, options: [{ en: '10', pl: '10' }, { en: '12', pl: '12' }, { en: '15', pl: '15' }, { en: '18', pl: '18' }], correctIndex: 2 },
    { id: 'drop-world-geography-137', prompt: { en: 'How many autonomous communities does Spain have?', pl: 'Ile wspólnot autonomicznych ma Hiszpania?' }, options: [{ en: '15', pl: '15' }, { en: '17', pl: '17' }, { en: '19', pl: '19' }, { en: '21', pl: '21' }], correctIndex: 1 },
    { id: 'drop-world-geography-138', prompt: { en: 'How many provinces does South Africa have?', pl: 'Ile prowincji ma Republika Południowej Afryki?' }, options: [{ en: '7', pl: '7' }, { en: '9', pl: '9' }, { en: '11', pl: '11' }, { en: '13', pl: '13' }], correctIndex: 1 },
    { id: 'drop-world-geography-139', prompt: { en: 'How many regions does Italy have?', pl: 'Ile regionów mają Włochy?' }, options: [{ en: '16', pl: '16' }, { en: '18', pl: '18' }, { en: '20', pl: '20' }, { en: '22', pl: '22' }], correctIndex: 2 },
    { id: 'drop-world-geography-140', prompt: { en: 'How many departments does Uruguay have?', pl: 'Ile departamentów ma Urugwaj?' }, options: [{ en: '15', pl: '15' }, { en: '17', pl: '17' }, { en: '19', pl: '19' }, { en: '21', pl: '21' }], correctIndex: 2 },
    { id: 'drop-world-geography-141', prompt: { en: 'How many provinces does Belgium have?', pl: 'Ile prowincji ma Belgia?' }, options: [{ en: '8', pl: '8' }, { en: '10', pl: '10' }, { en: '12', pl: '12' }, { en: '14', pl: '14' }], correctIndex: 1 },

    // --- Landmarks, canals, straits, ranges, lines ---
    { id: 'drop-world-geography-142', prompt: { en: 'What is the total height of Angel Falls (m)?', pl: 'Jaka jest całkowita wysokość wodospadu Salto Ángel (m)?' }, options: [{ en: '620', pl: '620' }, { en: '810', pl: '810' }, { en: '979', pl: '979' }, { en: '1,200', pl: '1 200' }], correctIndex: 2 },
    { id: 'drop-world-geography-143', prompt: { en: 'Approximately how long is the Suez Canal (km)?', pl: 'Jaką przybliżoną długość ma Kanał Sueski (km)?' }, options: [{ en: '120', pl: '120' }, { en: '193', pl: '193' }, { en: '270', pl: '270' }, { en: '350', pl: '350' }], correctIndex: 1 },
    { id: 'drop-world-geography-144', prompt: { en: 'Approximately how long is the Panama Canal (km)?', pl: 'Jaką przybliżoną długość ma Kanał Panamski (km)?' }, options: [{ en: '50', pl: '50' }, { en: '82', pl: '82' }, { en: '120', pl: '120' }, { en: '160', pl: '160' }], correctIndex: 1 },
    { id: 'drop-world-geography-145', prompt: { en: 'According to Niagara Parks, what is the average drop of the Canadian Horseshoe Falls (m)?', pl: 'Ile metrów wynosi średnia wysokość spadku kanadyjskiego Wodospadu Podkowy (Horseshoe Falls) według danych Niagara Parks?' }, options: [{ en: '34', pl: '34' }, { en: '57', pl: '57' }, { en: '72', pl: '72' }, { en: '95', pl: '95' }], correctIndex: 1 },
    { id: 'drop-world-geography-146', prompt: { en: 'What is the maximum drop at Victoria Falls (m)?', pl: 'Ile wynosi maksymalna wysokość spadku Wodospadów Wiktorii (m)?' }, options: [{ en: '70', pl: '70' }, { en: '108', pl: '108' }, { en: '150', pl: '150' }, { en: '200', pl: '200' }], correctIndex: 1 },
    { id: 'drop-world-geography-147', prompt: { en: 'Approximately how wide is the Strait of Gibraltar at its narrowest (km)?', pl: 'Jaką przybliżoną szerokość ma Cieśnina Gibraltarska w najwęższym miejscu (km)?' }, options: [{ en: '8', pl: '8' }, { en: '13', pl: '13' }, { en: '21', pl: '21' }, { en: '30', pl: '30' }], correctIndex: 1 },
    { id: 'drop-world-geography-148', prompt: { en: 'Approximately how long is the Channel Tunnel (km)?', pl: 'Jaką przybliżoną długość ma Eurotunel pod kanałem La Manche (km)?' }, options: [{ en: '32', pl: '32' }, { en: '50', pl: '50' }, { en: '68', pl: '68' }, { en: '85', pl: '85' }], correctIndex: 1 },
    { id: 'drop-world-geography-149', prompt: { en: 'How many mountains are traditionally recognised as exceeding 8,000 m above sea level?', pl: 'Ile szczytów tradycyjnie zalicza się do ośmiotysięczników, czyli gór przekraczających 8 000 m n.p.m.?' }, options: [{ en: '10', pl: '10' }, { en: '14', pl: '14' }, { en: '18', pl: '18' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-150', prompt: { en: 'Approximately how long is the Himalayan mountain range (km)?', pl: 'Jaką przybliżoną długość ma łańcuch Himalajów (km)?' }, options: [{ en: '1,600', pl: '1 600' }, { en: '2,400', pl: '2 400' }, { en: '3,200', pl: '3 200' }, { en: '4,000', pl: '4 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-151', prompt: { en: 'Approximately how long is the Great Barrier Reef (km)?', pl: 'Jaką przybliżoną długość ma Wielka Rafa Koralowa (km)?' }, options: [{ en: '1,400', pl: '1 400' }, { en: '2,300', pl: '2 300' }, { en: '3,200', pl: '3 200' }, { en: '4,100', pl: '4 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-152', prompt: { en: 'How tall is the Eiffel Tower including its antenna (m)?', pl: 'Jaką wysokość ma Wieża Eiffla wraz z anteną (m)?' }, options: [{ en: '210', pl: '210' }, { en: '330', pl: '330' }, { en: '450', pl: '450' }, { en: '580', pl: '580' }], correctIndex: 1 },
    { id: 'drop-world-geography-153', prompt: { en: 'How many sovereign countries share the island of New Guinea?', pl: 'Na terytorium ilu suwerennych państw leży wyspa Nowa Gwinea?' }, options: [{ en: '1', pl: '1' }, { en: '2', pl: '2' }, { en: '3', pl: '3' }, { en: '4', pl: '4' }], correctIndex: 1 },
    { id: 'drop-world-geography-154', prompt: { en: 'Approximately how long is the Rocky Mountains range (km)?', pl: 'Jaką przybliżoną długość mają Góry Skaliste (km)?' }, options: [{ en: '3,200', pl: '3 200' }, { en: '4,800', pl: '4 800' }, { en: '6,400', pl: '6 400' }, { en: '8,000', pl: '8 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-155', prompt: { en: 'Approximately how wide is the Bering Strait at its narrowest (km)?', pl: 'Jaką przybliżoną szerokość ma Cieśnina Beringa w najwęższym miejscu (km)?' }, options: [{ en: '50', pl: '50' }, { en: '82', pl: '82' }, { en: '120', pl: '120' }, { en: '160', pl: '160' }], correctIndex: 1 },
    { id: 'drop-world-geography-156', prompt: { en: 'How many countries border the Caspian Sea?', pl: 'Ile państw leży nad Morzem Kaspijskim?' }, options: [{ en: '3', pl: '3' }, { en: '5', pl: '5' }, { en: '7', pl: '7' }, { en: '9', pl: '9' }], correctIndex: 1 },
    { id: 'drop-world-geography-157', prompt: { en: 'Approximately how wide is the Strait of Dover at its narrowest (km)?', pl: 'Jaką przybliżoną szerokość ma Cieśnina Kaletańska w najwęższym miejscu (km)?' }, options: [{ en: '20', pl: '20' }, { en: '33', pl: '33' }, { en: '48', pl: '48' }, { en: '64', pl: '64' }], correctIndex: 1 },
    { id: 'drop-world-geography-158', prompt: { en: 'Approximately how long is the Kiel Canal (km)?', pl: 'Jaką przybliżoną długość ma Kanał Kiloński (km)?' }, options: [{ en: '60', pl: '60' }, { en: '98', pl: '98' }, { en: '140', pl: '140' }, { en: '185', pl: '185' }], correctIndex: 1 },
    { id: 'drop-world-geography-159', prompt: { en: 'How tall is the CN Tower to the tip of its antenna (m)?', pl: 'Jaką wysokość ma CN Tower do czubka anteny (m)?' }, options: [{ en: '420', pl: '420' }, { en: '553', pl: '553' }, { en: '690', pl: '690' }, { en: '820', pl: '820' }], correctIndex: 1 },
    { id: 'drop-world-geography-160', prompt: { en: 'What is Earth’s equatorial circumference, rounded to the nearest kilometer?', pl: 'Ile wynosi obwód Ziemi na równiku po zaokrągleniu do pełnego kilometra?' }, options: [{ en: '32,000 km', pl: '32 000 km' }, { en: '40,075 km', pl: '40 075 km' }, { en: '48,000 km', pl: '48 000 km' }, { en: '56,000 km', pl: '56 000 km' }], correctIndex: 1 },
    { id: 'drop-world-geography-161', prompt: { en: 'At approximately what latitude does the Tropic of Cancer lie (degrees N)?', pl: 'Na jakiej przybliżonej szerokości geograficznej leży Zwrotnik Raka (stopnie N)?' }, options: [{ en: '18.5', pl: '18,5' }, { en: '23.5', pl: '23,5' }, { en: '28.5', pl: '28,5' }, { en: '33.5', pl: '33,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-162', prompt: { en: 'At approximately what latitude does the Arctic Circle lie (degrees N)?', pl: 'Na jakiej przybliżonej szerokości geograficznej leży koło podbiegunowe północne (stopnie N)?' }, options: [{ en: '60.5', pl: '60,5' }, { en: '66.5', pl: '66,5' }, { en: '72.5', pl: '72,5' }, { en: '78.5', pl: '78,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-163', prompt: { en: 'How many time zones does Russia span?', pl: 'Ile stref czasowych obejmuje Rosja?' }, options: [{ en: '7', pl: '7' }, { en: '9', pl: '9' }, { en: '11', pl: '11' }, { en: '13', pl: '13' }], correctIndex: 2 },

    // --- Borders, neighbours and country counts ---
    { id: 'drop-world-geography-164', prompt: { en: 'How many countries border China?', pl: 'Z iloma państwami graniczą Chiny?' }, options: [{ en: '11', pl: '11' }, { en: '14', pl: '14' }, { en: '17', pl: '17' }, { en: '20', pl: '20' }], correctIndex: 1 },
    { id: 'drop-world-geography-165', prompt: { en: 'How many sovereign states border Brazil, counting France via French Guiana?', pl: 'Z iloma suwerennymi państwami graniczy Brazylia, jeśli wliczyć Francję przez Gujanę Francuską?' }, options: [{ en: '7', pl: '7' }, { en: '10', pl: '10' }, { en: '13', pl: '13' }, { en: '16', pl: '16' }], correctIndex: 1 },
    { id: 'drop-world-geography-166', prompt: { en: 'How many countries border mainland France?', pl: 'Z iloma państwami graniczy kontynentalna Francja?' }, options: [{ en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }, { en: '12', pl: '12' }], correctIndex: 1 },
    { id: 'drop-world-geography-167', prompt: { en: 'How many countries border Austria?', pl: 'Z iloma państwami graniczy Austria?' }, options: [{ en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }, { en: '12', pl: '12' }], correctIndex: 1 },
    { id: 'drop-world-geography-168', prompt: { en: 'How many countries border Switzerland?', pl: 'Z iloma państwami graniczy Szwajcaria?' }, options: [{ en: '3', pl: '3' }, { en: '5', pl: '5' }, { en: '7', pl: '7' }, { en: '9', pl: '9' }], correctIndex: 1 },
    { id: 'drop-world-geography-169', prompt: { en: 'How many UN member states does Russia border by land?', pl: 'Z iloma państwami członkowskimi ONZ Rosja graniczy lądowo?' }, options: [{ en: '10', pl: '10' }, { en: '14', pl: '14' }, { en: '18', pl: '18' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-170', prompt: { en: 'How many countries border Hungary?', pl: 'Z iloma państwami graniczą Węgry?' }, options: [{ en: '5', pl: '5' }, { en: '7', pl: '7' }, { en: '9', pl: '9' }, { en: '11', pl: '11' }], correctIndex: 1 },
    { id: 'drop-world-geography-171', prompt: { en: 'How many landlocked countries are in South America?', pl: 'Ile państw śródlądowych znajduje się w Ameryce Południowej?' }, options: [{ en: '0', pl: '0' }, { en: '2', pl: '2' }, { en: '4', pl: '4' }, { en: '6', pl: '6' }], correctIndex: 1 },
    { id: 'drop-world-geography-172', prompt: { en: 'How many countries are in Central America?', pl: 'Ile państw znajduje się w Ameryce Środkowej?' }, options: [{ en: '5', pl: '5' }, { en: '7', pl: '7' }, { en: '9', pl: '9' }, { en: '11', pl: '11' }], correctIndex: 1 },
    { id: 'drop-world-geography-173', prompt: { en: 'How many countries are in South America?', pl: 'Ile państw znajduje się w Ameryce Południowej?' }, options: [{ en: '10', pl: '10' }, { en: '12', pl: '12' }, { en: '14', pl: '14' }, { en: '16', pl: '16' }], correctIndex: 1 },
    { id: 'drop-world-geography-174', prompt: { en: 'How many UN member states are in Oceania?', pl: 'Ile państw członkowskich ONZ znajduje się w Oceanii?' }, options: [{ en: '10', pl: '10' }, { en: '14', pl: '14' }, { en: '18', pl: '18' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-175', prompt: { en: 'How many countries border the Black Sea?', pl: 'Ile państw leży nad Morzem Czarnym?' }, options: [{ en: '4', pl: '4' }, { en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }], correctIndex: 1 },
    { id: 'drop-world-geography-176', prompt: { en: 'How many Great Lakes are there in North America?', pl: 'Ile Wielkich Jezior znajduje się w Ameryce Północnej?' }, options: [{ en: '3', pl: '3' }, { en: '4', pl: '4' }, { en: '5', pl: '5' }, { en: '6', pl: '6' }], correctIndex: 2 },
    { id: 'drop-world-geography-177', prompt: { en: 'How many member states are in the European Union (2024)?', pl: 'Ile państw członkowskich liczy Unia Europejska (2024)?' }, options: [{ en: '24', pl: '24' }, { en: '27', pl: '27' }, { en: '30', pl: '30' }, { en: '33', pl: '33' }], correctIndex: 1 },
    { id: 'drop-world-geography-178', prompt: { en: 'Using Geoscience Australia’s 1:100,000 dataset and including islands, what is Australia’s coastline length (thousand km)?', pl: 'Ile wynosi długość linii brzegowej Australii wraz z wyspami według bazy Geoscience Australia w skali 1:100 000 (tys. km)?' }, options: [{ en: '25.8', pl: '25,8' }, { en: '35.8', pl: '35,8' }, { en: '47.1', pl: '47,1' }, { en: '59.7', pl: '59,7' }], correctIndex: 3 },
    { id: 'drop-world-geography-179', prompt: { en: 'How many countries border Lake Geneva?', pl: 'Ile państw leży nad Jeziorem Genewskim?' }, options: [{ en: '1', pl: '1' }, { en: '2', pl: '2' }, { en: '3', pl: '3' }, { en: '4', pl: '4' }], correctIndex: 1 },
    { id: 'drop-world-geography-180', prompt: { en: 'How many Spanish autonomous cities are on the North African coast?', pl: 'Ile hiszpańskich miast autonomicznych leży na wybrzeżu Afryki Północnej?' }, options: [{ en: '0', pl: '0' }, { en: '2', pl: '2' }, { en: '4', pl: '4' }, { en: '6', pl: '6' }], correctIndex: 1 },
];

const toLocale = (lang: 'en' | 'pl') => (c: BiCard): DropPackCard => ({
    id: c.id,
    prompt: c.prompt[lang],
    options: c.options.map((o) => o[lang]),
    correctIndex: c.correctIndex,
    difficulty: getDropQuestionDifficulty(c.id),
});

export const worldGeographyEn: DropPackCard[] = cards.map(toLocale('en'));
export const worldGeographyPl: DropPackCard[] = cards.map(toLocale('pl'));
