// Premium pack: World Geography — The Drop.
// 180 original bilingual (EN/PL) questions. Each offers four real-world figures;
// exactly one is true, distractors are plausible near-values. Units live in the
// prompt so options stay clean numbers. Derived monolingual arrays feed
// PackDefinition.content; the store bridge zips en/pl by index at runtime.

import type { DropPackCard } from '../content';

interface BiCard {
    id: string;
    prompt: { en: string; pl: string };
    options: { en: string; pl: string }[];
    correctIndex: number;
}

const cards: BiCard[] = [
    // --- Rivers (length, km) ---
    { id: 'drop-world-geography-001', prompt: { en: 'How long is the Nile River (km)?', pl: 'Jaką długość ma rzeka Nil (km)?' }, options: [{ en: '4,200', pl: '4 200' }, { en: '5,500', pl: '5 500' }, { en: '6,650', pl: '6 650' }, { en: '7,800', pl: '7 800' }], correctIndex: 2 },
    { id: 'drop-world-geography-002', prompt: { en: 'How long is the Amazon River (km)?', pl: 'Jaką długość ma rzeka Amazonka (km)?' }, options: [{ en: '5,500', pl: '5 500' }, { en: '6,400', pl: '6 400' }, { en: '7,200', pl: '7 200' }, { en: '8,000', pl: '8 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-003', prompt: { en: 'How long is the Yangtze River (km)?', pl: 'Jaką długość ma rzeka Jangcy (km)?' }, options: [{ en: '4,800', pl: '4 800' }, { en: '5,500', pl: '5 500' }, { en: '6,300', pl: '6 300' }, { en: '7,100', pl: '7 100' }], correctIndex: 2 },
    { id: 'drop-world-geography-004', prompt: { en: 'How long is the Mississippi River (km)?', pl: 'Jaką długość ma rzeka Missisipi (km)?' }, options: [{ en: '2,900', pl: '2 900' }, { en: '3,770', pl: '3 770' }, { en: '4,500', pl: '4 500' }, { en: '5,200', pl: '5 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-005', prompt: { en: 'How long is the Yellow River, Huang He (km)?', pl: 'Jaką długość ma rzeka Huang He (km)?' }, options: [{ en: '4,000', pl: '4 000' }, { en: '4,800', pl: '4 800' }, { en: '5,464', pl: '5 464' }, { en: '6,300', pl: '6 300' }], correctIndex: 2 },
    { id: 'drop-world-geography-006', prompt: { en: 'How long is the Danube River (km)?', pl: 'Jaką długość ma rzeka Dunaj (km)?' }, options: [{ en: '1,900', pl: '1 900' }, { en: '2,850', pl: '2 850' }, { en: '3,600', pl: '3 600' }, { en: '4,200', pl: '4 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-007', prompt: { en: 'How long is the Volga River (km)?', pl: 'Jaką długość ma rzeka Wołga (km)?' }, options: [{ en: '2,400', pl: '2 400' }, { en: '3,530', pl: '3 530' }, { en: '4,200', pl: '4 200' }, { en: '5,000', pl: '5 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-008', prompt: { en: 'How long is the Congo River (km)?', pl: 'Jaką długość ma rzeka Kongo (km)?' }, options: [{ en: '3,500', pl: '3 500' }, { en: '4,700', pl: '4 700' }, { en: '5,600', pl: '5 600' }, { en: '6,400', pl: '6 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-009', prompt: { en: 'How long is the Mekong River (km)?', pl: 'Jaką długość ma rzeka Mekong (km)?' }, options: [{ en: '3,200', pl: '3 200' }, { en: '4,350', pl: '4 350' }, { en: '5,100', pl: '5 100' }, { en: '6,000', pl: '6 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-010', prompt: { en: 'How long is the Rhine River (km)?', pl: 'Jaką długość ma rzeka Ren (km)?' }, options: [{ en: '800', pl: '800' }, { en: '1,233', pl: '1 233' }, { en: '1,700', pl: '1 700' }, { en: '2,200', pl: '2 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-011', prompt: { en: 'How long is the Ganges River (km)?', pl: 'Jaką długość ma rzeka Ganges (km)?' }, options: [{ en: '1,800', pl: '1 800' }, { en: '2,510', pl: '2 510' }, { en: '3,200', pl: '3 200' }, { en: '4,000', pl: '4 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-012', prompt: { en: 'How long is the Vistula River (km)?', pl: 'Jaką długość ma rzeka Wisła (km)?' }, options: [{ en: '760', pl: '760' }, { en: '1,047', pl: '1 047' }, { en: '1,350', pl: '1 350' }, { en: '1,600', pl: '1 600' }], correctIndex: 1 },
    { id: 'drop-world-geography-013', prompt: { en: 'How long is the Seine River (km)?', pl: 'Jaką długość ma rzeka Sekwana (km)?' }, options: [{ en: '480', pl: '480' }, { en: '777', pl: '777' }, { en: '1,100', pl: '1 100' }, { en: '1,400', pl: '1 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-014', prompt: { en: 'How long is the Thames River (km)?', pl: 'Jaką długość ma rzeka Tamiza (km)?' }, options: [{ en: '215', pl: '215' }, { en: '346', pl: '346' }, { en: '480', pl: '480' }, { en: '620', pl: '620' }], correctIndex: 1 },
    { id: 'drop-world-geography-015', prompt: { en: 'How long is the Niger River (km)?', pl: 'Jaką długość ma rzeka Niger (km)?' }, options: [{ en: '3,000', pl: '3 000' }, { en: '4,180', pl: '4 180' }, { en: '5,200', pl: '5 200' }, { en: '6,300', pl: '6 300' }], correctIndex: 1 },
    { id: 'drop-world-geography-016', prompt: { en: 'How long is the Zambezi River (km)?', pl: 'Jaką długość ma rzeka Zambezi (km)?' }, options: [{ en: '1,800', pl: '1 800' }, { en: '2,574', pl: '2 574' }, { en: '3,300', pl: '3 300' }, { en: '4,100', pl: '4 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-017', prompt: { en: 'How long is the Murray River in Australia (km)?', pl: 'Jaką długość ma rzeka Murray w Australii (km)?' }, options: [{ en: '1,700', pl: '1 700' }, { en: '2,508', pl: '2 508' }, { en: '3,300', pl: '3 300' }, { en: '4,000', pl: '4 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-018', prompt: { en: 'How long is the Colorado River (km)?', pl: 'Jaką długość ma rzeka Kolorado (km)?' }, options: [{ en: '1,600', pl: '1 600' }, { en: '2,330', pl: '2 330' }, { en: '3,100', pl: '3 100' }, { en: '3,900', pl: '3 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-019', prompt: { en: 'How long is the Rio Grande (km)?', pl: 'Jaką długość ma rzeka Rio Grande (km)?' }, options: [{ en: '2,200', pl: '2 200' }, { en: '3,051', pl: '3 051' }, { en: '3,900', pl: '3 900' }, { en: '4,700', pl: '4 700' }], correctIndex: 1 },
    { id: 'drop-world-geography-020', prompt: { en: 'How long is the Elbe River (km)?', pl: 'Jaką długość ma rzeka Łaba (km)?' }, options: [{ en: '720', pl: '720' }, { en: '1,094', pl: '1 094' }, { en: '1,500', pl: '1 500' }, { en: '1,900', pl: '1 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-021', prompt: { en: 'How long is the Loire River (km)?', pl: 'Jaką długość ma rzeka Loara (km)?' }, options: [{ en: '680', pl: '680' }, { en: '1,012', pl: '1 012' }, { en: '1,400', pl: '1 400' }, { en: '1,800', pl: '1 800' }], correctIndex: 1 },
    { id: 'drop-world-geography-022', prompt: { en: 'How long is the Po River in Italy (km)?', pl: 'Jaką długość ma rzeka Pad we Włoszech (km)?' }, options: [{ en: '420', pl: '420' }, { en: '652', pl: '652' }, { en: '880', pl: '880' }, { en: '1,100', pl: '1 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-023', prompt: { en: 'How long is the Indus River (km)?', pl: 'Jaką długość ma rzeka Indus (km)?' }, options: [{ en: '2,300', pl: '2 300' }, { en: '3,180', pl: '3 180' }, { en: '4,100', pl: '4 100' }, { en: '5,000', pl: '5 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-024', prompt: { en: 'How long is the Brahmaputra River (km)?', pl: 'Jaką długość ma rzeka Brahmaputra (km)?' }, options: [{ en: '2,100', pl: '2 100' }, { en: '2,900', pl: '2 900' }, { en: '3,700', pl: '3 700' }, { en: '4,500', pl: '4 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-025', prompt: { en: 'How long is the Lena River (km)?', pl: 'Jaką długość ma rzeka Lena (km)?' }, options: [{ en: '3,200', pl: '3 200' }, { en: '4,400', pl: '4 400' }, { en: '5,300', pl: '5 300' }, { en: '6,200', pl: '6 200' }], correctIndex: 1 },

    // --- Country area (million sq km) ---
    { id: 'drop-world-geography-026', prompt: { en: 'What is the area of Russia (million sq km)?', pl: 'Jaką powierzchnię ma Rosja (mln km2)?' }, options: [{ en: '11.0', pl: '11,0' }, { en: '14.5', pl: '14,5' }, { en: '17.1', pl: '17,1' }, { en: '21.3', pl: '21,3' }], correctIndex: 2 },
    { id: 'drop-world-geography-027', prompt: { en: 'What is the area of Canada (million sq km)?', pl: 'Jaką powierzchnię ma Kanada (mln km2)?' }, options: [{ en: '7.7', pl: '7,7' }, { en: '10.0', pl: '10,0' }, { en: '12.5', pl: '12,5' }, { en: '15.1', pl: '15,1' }], correctIndex: 1 },
    { id: 'drop-world-geography-028', prompt: { en: 'What is the area of China (million sq km)?', pl: 'Jaką powierzchnię mają Chiny (mln km2)?' }, options: [{ en: '6.4', pl: '6,4' }, { en: '8.1', pl: '8,1' }, { en: '9.6', pl: '9,6' }, { en: '11.2', pl: '11,2' }], correctIndex: 2 },
    { id: 'drop-world-geography-029', prompt: { en: 'What is the area of the USA (million sq km)?', pl: 'Jaką powierzchnię mają Stany Zjednoczone (mln km2)?' }, options: [{ en: '8.4', pl: '8,4' }, { en: '9.8', pl: '9,8' }, { en: '11.5', pl: '11,5' }, { en: '13.0', pl: '13,0' }], correctIndex: 1 },
    { id: 'drop-world-geography-030', prompt: { en: 'What is the area of Brazil (million sq km)?', pl: 'Jaką powierzchnię ma Brazylia (mln km2)?' }, options: [{ en: '6.2', pl: '6,2' }, { en: '7.3', pl: '7,3' }, { en: '8.5', pl: '8,5' }, { en: '9.9', pl: '9,9' }], correctIndex: 2 },
    { id: 'drop-world-geography-031', prompt: { en: 'What is the area of Australia (million sq km)?', pl: 'Jaką powierzchnię ma Australia (mln km2)?' }, options: [{ en: '5.9', pl: '5,9' }, { en: '7.7', pl: '7,7' }, { en: '9.2', pl: '9,2' }, { en: '10.8', pl: '10,8' }], correctIndex: 1 },
    { id: 'drop-world-geography-032', prompt: { en: 'What is the area of India (million sq km)?', pl: 'Jaką powierzchnię mają Indie (mln km2)?' }, options: [{ en: '2.1', pl: '2,1' }, { en: '3.3', pl: '3,3' }, { en: '4.6', pl: '4,6' }, { en: '5.8', pl: '5,8' }], correctIndex: 1 },
    { id: 'drop-world-geography-033', prompt: { en: 'What is the area of Argentina (million sq km)?', pl: 'Jaką powierzchnię ma Argentyna (mln km2)?' }, options: [{ en: '1.9', pl: '1,9' }, { en: '2.8', pl: '2,8' }, { en: '3.7', pl: '3,7' }, { en: '4.5', pl: '4,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-034', prompt: { en: 'What is the area of Kazakhstan (million sq km)?', pl: 'Jaką powierzchnię ma Kazachstan (mln km2)?' }, options: [{ en: '1.8', pl: '1,8' }, { en: '2.7', pl: '2,7' }, { en: '3.5', pl: '3,5' }, { en: '4.2', pl: '4,2' }], correctIndex: 1 },
    { id: 'drop-world-geography-035', prompt: { en: 'What is the area of Algeria, the largest country in Africa (million sq km)?', pl: 'Jaką powierzchnię ma Algieria, największy kraj Afryki (mln km2)?' }, options: [{ en: '1.6', pl: '1,6' }, { en: '2.4', pl: '2,4' }, { en: '3.1', pl: '3,1' }, { en: '3.9', pl: '3,9' }], correctIndex: 1 },

    // --- Country area (thousand sq km) ---
    { id: 'drop-world-geography-036', prompt: { en: 'What is the area of France, mainland (thousand sq km)?', pl: 'Jaką powierzchnię ma Francja kontynentalna (tys. km2)?' }, options: [{ en: '430', pl: '430' }, { en: '551', pl: '551' }, { en: '690', pl: '690' }, { en: '820', pl: '820' }], correctIndex: 1 },
    { id: 'drop-world-geography-037', prompt: { en: 'What is the area of Poland (thousand sq km)?', pl: 'Jaką powierzchnię ma Polska (tys. km2)?' }, options: [{ en: '240', pl: '240' }, { en: '312', pl: '312' }, { en: '390', pl: '390' }, { en: '460', pl: '460' }], correctIndex: 1 },
    { id: 'drop-world-geography-038', prompt: { en: 'What is the area of Germany (thousand sq km)?', pl: 'Jaką powierzchnię mają Niemcy (tys. km2)?' }, options: [{ en: '270', pl: '270' }, { en: '357', pl: '357' }, { en: '440', pl: '440' }, { en: '520', pl: '520' }], correctIndex: 1 },
    { id: 'drop-world-geography-039', prompt: { en: 'What is the area of Japan (thousand sq km)?', pl: 'Jaką powierzchnię ma Japonia (tys. km2)?' }, options: [{ en: '290', pl: '290' }, { en: '378', pl: '378' }, { en: '460', pl: '460' }, { en: '540', pl: '540' }], correctIndex: 1 },
    { id: 'drop-world-geography-040', prompt: { en: 'What is the area of the United Kingdom (thousand sq km)?', pl: 'Jaką powierzchnię ma Wielka Brytania (tys. km2)?' }, options: [{ en: '180', pl: '180' }, { en: '243', pl: '243' }, { en: '310', pl: '310' }, { en: '380', pl: '380' }], correctIndex: 1 },
    { id: 'drop-world-geography-041', prompt: { en: 'What is the area of Italy (thousand sq km)?', pl: 'Jaką powierzchnię mają Włochy (tys. km2)?' }, options: [{ en: '230', pl: '230' }, { en: '301', pl: '301' }, { en: '380', pl: '380' }, { en: '450', pl: '450' }], correctIndex: 1 },
    { id: 'drop-world-geography-042', prompt: { en: 'What is the area of Spain (thousand sq km)?', pl: 'Jaką powierzchnię ma Hiszpania (tys. km2)?' }, options: [{ en: '390', pl: '390' }, { en: '506', pl: '506' }, { en: '620', pl: '620' }, { en: '740', pl: '740' }], correctIndex: 1 },
    { id: 'drop-world-geography-043', prompt: { en: 'What is the area of Greece (thousand sq km)?', pl: 'Jaką powierzchnię ma Grecja (tys. km2)?' }, options: [{ en: '95', pl: '95' }, { en: '132', pl: '132' }, { en: '175', pl: '175' }, { en: '210', pl: '210' }], correctIndex: 1 },
    { id: 'drop-world-geography-044', prompt: { en: 'What is the area of Iceland (thousand sq km)?', pl: 'Jaką powierzchnię ma Islandia (tys. km2)?' }, options: [{ en: '70', pl: '70' }, { en: '103', pl: '103' }, { en: '140', pl: '140' }, { en: '180', pl: '180' }], correctIndex: 1 },
    { id: 'drop-world-geography-045', prompt: { en: 'What is the area of New Zealand (thousand sq km)?', pl: 'Jaką powierzchnię ma Nowa Zelandia (tys. km2)?' }, options: [{ en: '200', pl: '200' }, { en: '268', pl: '268' }, { en: '330', pl: '330' }, { en: '400', pl: '400' }], correctIndex: 1 },

    // --- Continent area (million sq km) ---
    { id: 'drop-world-geography-046', prompt: { en: 'What is the area of Asia (million sq km)?', pl: 'Jaką powierzchnię ma Azja (mln km2)?' }, options: [{ en: '33', pl: '33' }, { en: '44.6', pl: '44,6' }, { en: '56', pl: '56' }, { en: '68', pl: '68' }], correctIndex: 1 },
    { id: 'drop-world-geography-047', prompt: { en: 'What is the area of Africa (million sq km)?', pl: 'Jaką powierzchnię ma Afryka (mln km2)?' }, options: [{ en: '22', pl: '22' }, { en: '30.3', pl: '30,3' }, { en: '39', pl: '39' }, { en: '47', pl: '47' }], correctIndex: 1 },
    { id: 'drop-world-geography-048', prompt: { en: 'What is the area of North America (million sq km)?', pl: 'Jaką powierzchnię ma Ameryka Północna (mln km2)?' }, options: [{ en: '18', pl: '18' }, { en: '24.7', pl: '24,7' }, { en: '31', pl: '31' }, { en: '38', pl: '38' }], correctIndex: 1 },
    { id: 'drop-world-geography-049', prompt: { en: 'What is the area of South America (million sq km)?', pl: 'Jaką powierzchnię ma Ameryka Południowa (mln km2)?' }, options: [{ en: '13', pl: '13' }, { en: '17.8', pl: '17,8' }, { en: '23', pl: '23' }, { en: '28', pl: '28' }], correctIndex: 1 },
    { id: 'drop-world-geography-050', prompt: { en: 'What is the area of Antarctica (million sq km)?', pl: 'Jaką powierzchnię ma Antarktyda (mln km2)?' }, options: [{ en: '10', pl: '10' }, { en: '14', pl: '14' }, { en: '18', pl: '18' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-051', prompt: { en: 'What is the area of Europe (million sq km)?', pl: 'Jaką powierzchnię ma Europa (mln km2)?' }, options: [{ en: '7.5', pl: '7,5' }, { en: '10.2', pl: '10,2' }, { en: '13.0', pl: '13,0' }, { en: '16.0', pl: '16,0' }], correctIndex: 1 },

    // --- Mountain heights (m) ---
    { id: 'drop-world-geography-052', prompt: { en: 'How high is K2 (m)?', pl: 'Jaką wysokość ma K2 (m)?' }, options: [{ en: '7,900', pl: '7 900' }, { en: '8,200', pl: '8 200' }, { en: '8,611', pl: '8 611' }, { en: '9,000', pl: '9 000' }], correctIndex: 2 },
    { id: 'drop-world-geography-053', prompt: { en: 'How high is Kilimanjaro (m)?', pl: 'Jaką wysokość ma Kilimandżaro (m)?' }, options: [{ en: '4,800', pl: '4 800' }, { en: '5,895', pl: '5 895' }, { en: '6,400', pl: '6 400' }, { en: '7,100', pl: '7 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-054', prompt: { en: 'How high is Mont Blanc (m)?', pl: 'Jaką wysokość ma Mont Blanc (m)?' }, options: [{ en: '3,800', pl: '3 800' }, { en: '4,809', pl: '4 809' }, { en: '5,500', pl: '5 500' }, { en: '6,200', pl: '6 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-055', prompt: { en: 'How high is Denali, the highest peak in North America (m)?', pl: 'Jaką wysokość ma Denali, najwyższy szczyt Ameryki Północnej (m)?' }, options: [{ en: '5,200', pl: '5 200' }, { en: '6,190', pl: '6 190' }, { en: '7,000', pl: '7 000' }, { en: '7,800', pl: '7 800' }], correctIndex: 1 },
    { id: 'drop-world-geography-056', prompt: { en: 'How high is Aconcagua, the highest peak in South America (m)?', pl: 'Jaką wysokość ma Aconcagua, najwyższy szczyt Ameryki Południowej (m)?' }, options: [{ en: '5,900', pl: '5 900' }, { en: '6,961', pl: '6 961' }, { en: '7,800', pl: '7 800' }, { en: '8,400', pl: '8 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-057', prompt: { en: 'How high is Mount Elbrus, the highest peak in Europe (m)?', pl: 'Jaką wysokość ma Elbrus, najwyższy szczyt Europy (m)?' }, options: [{ en: '4,700', pl: '4 700' }, { en: '5,642', pl: '5 642' }, { en: '6,300', pl: '6 300' }, { en: '7,100', pl: '7 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-058', prompt: { en: 'How high is Mount Fuji (m)?', pl: 'Jaką wysokość ma Fudżi (m)?' }, options: [{ en: '2,900', pl: '2 900' }, { en: '3,776', pl: '3 776' }, { en: '4,500', pl: '4 500' }, { en: '5,200', pl: '5 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-059', prompt: { en: 'How high is the Matterhorn (m)?', pl: 'Jaką wysokość ma Matterhorn (m)?' }, options: [{ en: '3,600', pl: '3 600' }, { en: '4,478', pl: '4 478' }, { en: '5,200', pl: '5 200' }, { en: '5,900', pl: '5 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-060', prompt: { en: 'How high is Mount Kosciuszko, the highest peak in mainland Australia (m)?', pl: 'Jaką wysokość ma Góra Kościuszki, najwyższy szczyt kontynentalnej Australii (m)?' }, options: [{ en: '1,600', pl: '1 600' }, { en: '2,228', pl: '2 228' }, { en: '2,900', pl: '2 900' }, { en: '3,500', pl: '3 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-061', prompt: { en: 'How high is Vinson Massif, the highest peak in Antarctica (m)?', pl: 'Jaką wysokość ma Masyw Vinsona, najwyższy szczyt Antarktydy (m)?' }, options: [{ en: '3,800', pl: '3 800' }, { en: '4,892', pl: '4 892' }, { en: '5,600', pl: '5 600' }, { en: '6,400', pl: '6 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-062', prompt: { en: 'How high is Ben Nevis, the highest peak in the British Isles (m)?', pl: 'Jaką wysokość ma Ben Nevis, najwyższy szczyt Wysp Brytyjskich (m)?' }, options: [{ en: '900', pl: '900' }, { en: '1,345', pl: '1 345' }, { en: '1,800', pl: '1 800' }, { en: '2,300', pl: '2 300' }], correctIndex: 1 },
    { id: 'drop-world-geography-063', prompt: { en: 'How high is Mount Olympus in Greece (m)?', pl: 'Jaką wysokość ma Olimp w Grecji (m)?' }, options: [{ en: '2,100', pl: '2 100' }, { en: '2,917', pl: '2 917' }, { en: '3,600', pl: '3 600' }, { en: '4,200', pl: '4 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-064', prompt: { en: 'How high above sea level is Mauna Kea (m)?', pl: 'Na jaką wysokość nad poziom morza wznosi się Mauna Kea (m)?' }, options: [{ en: '3,400', pl: '3 400' }, { en: '4,207', pl: '4 207' }, { en: '5,100', pl: '5 100' }, { en: '5,900', pl: '5 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-065', prompt: { en: 'How high is Mount Logan, the highest peak in Canada (m)?', pl: 'Jaką wysokość ma Mount Logan, najwyższy szczyt Kanady (m)?' }, options: [{ en: '4,900', pl: '4 900' }, { en: '5,959', pl: '5 959' }, { en: '6,800', pl: '6 800' }, { en: '7,500', pl: '7 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-066', prompt: { en: 'How high is Mount Rainier (m)?', pl: 'Jaką wysokość ma Mount Rainier (m)?' }, options: [{ en: '3,500', pl: '3 500' }, { en: '4,392', pl: '4 392' }, { en: '5,200', pl: '5 200' }, { en: '6,000', pl: '6 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-067', prompt: { en: 'How high is Cotopaxi in Ecuador (m)?', pl: 'Jaką wysokość ma Cotopaxi w Ekwadorze (m)?' }, options: [{ en: '4,900', pl: '4 900' }, { en: '5,897', pl: '5 897' }, { en: '6,700', pl: '6 700' }, { en: '7,500', pl: '7 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-068', prompt: { en: 'How high is Mount Ararat in Turkey (m)?', pl: 'Jaką wysokość ma Ararat w Turcji (m)?' }, options: [{ en: '4,200', pl: '4 200' }, { en: '5,137', pl: '5 137' }, { en: '6,100', pl: '6 100' }, { en: '7,000', pl: '7 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-069', prompt: { en: 'How high is Mount Vesuvius (m)?', pl: 'Jaką wysokość ma Wezuwiusz (m)?' }, options: [{ en: '850', pl: '850' }, { en: '1,281', pl: '1 281' }, { en: '1,800', pl: '1 800' }, { en: '2,400', pl: '2 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-070', prompt: { en: 'How high is Table Mountain in South Africa (m)?', pl: 'Jaką wysokość ma Góra Stołowa w RPA (m)?' }, options: [{ en: '720', pl: '720' }, { en: '1,085', pl: '1 085' }, { en: '1,500', pl: '1 500' }, { en: '1,950', pl: '1 950' }], correctIndex: 1 },
    { id: 'drop-world-geography-071', prompt: { en: 'How high is Aoraki, Mount Cook, in New Zealand (m)?', pl: 'Jaką wysokość ma Aoraki, Mount Cook, w Nowej Zelandii (m)?' }, options: [{ en: '2,900', pl: '2 900' }, { en: '3,724', pl: '3 724' }, { en: '4,500', pl: '4 500' }, { en: '5,300', pl: '5 300' }], correctIndex: 1 },
    { id: 'drop-world-geography-072', prompt: { en: 'How high is Mount Whitney in the USA (m)?', pl: 'Jaką wysokość ma Mount Whitney w USA (m)?' }, options: [{ en: '3,600', pl: '3 600' }, { en: '4,421', pl: '4 421' }, { en: '5,200', pl: '5 200' }, { en: '6,000', pl: '6 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-073', prompt: { en: 'How tall is Mauna Kea measured from its base on the ocean floor (m)?', pl: 'Jaką wysokość ma Mauna Kea mierzona od podstawy na dnie oceanu (m)?' }, options: [{ en: '8,400', pl: '8 400' }, { en: '10,210', pl: '10 210' }, { en: '12,000', pl: '12 000' }, { en: '14,000', pl: '14 000' }], correctIndex: 1 },

    // --- Lakes ---
    { id: 'drop-world-geography-074', prompt: { en: 'What is the maximum depth of Lake Baikal (m)?', pl: 'Jaka jest maksymalna głębokość jeziora Bajkał (m)?' }, options: [{ en: '900', pl: '900' }, { en: '1,300', pl: '1 300' }, { en: '1,642', pl: '1 642' }, { en: '2,100', pl: '2 100' }], correctIndex: 2 },
    { id: 'drop-world-geography-075', prompt: { en: 'What is the area of the Caspian Sea (thousand sq km)?', pl: 'Jaką powierzchnię ma Morze Kaspijskie (tys. km2)?' }, options: [{ en: '210', pl: '210' }, { en: '371', pl: '371' }, { en: '520', pl: '520' }, { en: '680', pl: '680' }], correctIndex: 1 },
    { id: 'drop-world-geography-076', prompt: { en: 'What is the area of Lake Superior (thousand sq km)?', pl: 'Jaką powierzchnię ma Jezioro Górne (tys. km2)?' }, options: [{ en: '58', pl: '58' }, { en: '82', pl: '82' }, { en: '110', pl: '110' }, { en: '140', pl: '140' }], correctIndex: 1 },
    { id: 'drop-world-geography-077', prompt: { en: 'What is the area of Lake Victoria (thousand sq km)?', pl: 'Jaką powierzchnię ma Jezioro Wiktorii (tys. km2)?' }, options: [{ en: '45', pl: '45' }, { en: '69', pl: '69' }, { en: '95', pl: '95' }, { en: '120', pl: '120' }], correctIndex: 1 },
    { id: 'drop-world-geography-078', prompt: { en: 'What is the maximum depth of Lake Tanganyika (m)?', pl: 'Jaka jest maksymalna głębokość jeziora Tanganika (m)?' }, options: [{ en: '950', pl: '950' }, { en: '1,470', pl: '1 470' }, { en: '1,900', pl: '1 900' }, { en: '2,400', pl: '2 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-079', prompt: { en: 'At what elevation does Lake Titicaca sit (m)?', pl: 'Na jakiej wysokości leży jezioro Titicaca (m)?' }, options: [{ en: '2,800', pl: '2 800' }, { en: '3,812', pl: '3 812' }, { en: '4,500', pl: '4 500' }, { en: '5,200', pl: '5 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-080', prompt: { en: 'How many meters below sea level is the shore of the Dead Sea?', pl: 'Ile metrów poniżej poziomu morza leży brzeg Morza Martwego?' }, options: [{ en: '210', pl: '210' }, { en: '310', pl: '310' }, { en: '430', pl: '430' }, { en: '560', pl: '560' }], correctIndex: 2 },
    { id: 'drop-world-geography-081', prompt: { en: 'What is the area of Lake Geneva (sq km)?', pl: 'Jaką powierzchnię ma Jezioro Genewskie (km2)?' }, options: [{ en: '340', pl: '340' }, { en: '580', pl: '580' }, { en: '820', pl: '820' }, { en: '1,100', pl: '1 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-082', prompt: { en: 'What is the maximum depth of Loch Ness (m)?', pl: 'Jaka jest maksymalna głębokość Loch Ness (m)?' }, options: [{ en: '130', pl: '130' }, { en: '230', pl: '230' }, { en: '330', pl: '330' }, { en: '450', pl: '450' }], correctIndex: 1 },
    { id: 'drop-world-geography-083', prompt: { en: 'What is the area of Lake Balaton (sq km)?', pl: 'Jaką powierzchnię ma jezioro Balaton (km2)?' }, options: [{ en: '380', pl: '380' }, { en: '592', pl: '592' }, { en: '780', pl: '780' }, { en: '1,000', pl: '1 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-084', prompt: { en: 'What is the area of Lake Michigan (thousand sq km)?', pl: 'Jaką powierzchnię ma jezioro Michigan (tys. km2)?' }, options: [{ en: '42', pl: '42' }, { en: '58', pl: '58' }, { en: '76', pl: '76' }, { en: '95', pl: '95' }], correctIndex: 1 },
    { id: 'drop-world-geography-085', prompt: { en: 'What is the area of Lake Ontario (thousand sq km)?', pl: 'Jaką powierzchnię ma jezioro Ontario (tys. km2)?' }, options: [{ en: '13', pl: '13' }, { en: '19', pl: '19' }, { en: '27', pl: '27' }, { en: '36', pl: '36' }], correctIndex: 1 },
    { id: 'drop-world-geography-086', prompt: { en: 'What is the area of Lake Erie (thousand sq km)?', pl: 'Jaką powierzchnię ma jezioro Erie (tys. km2)?' }, options: [{ en: '18', pl: '18' }, { en: '25.7', pl: '25,7' }, { en: '34', pl: '34' }, { en: '43', pl: '43' }], correctIndex: 1 },
    { id: 'drop-world-geography-087', prompt: { en: 'What is the maximum depth of the Caspian Sea (m)?', pl: 'Jaka jest maksymalna głębokość Morza Kaspijskiego (m)?' }, options: [{ en: '600', pl: '600' }, { en: '1,025', pl: '1 025' }, { en: '1,500', pl: '1 500' }, { en: '2,000', pl: '2 000' }], correctIndex: 1 },

    // --- Deserts and islands ---
    { id: 'drop-world-geography-088', prompt: { en: 'What is the area of the Sahara (million sq km)?', pl: 'Jaką powierzchnię ma Sahara (mln km2)?' }, options: [{ en: '6.1', pl: '6,1' }, { en: '7.7', pl: '7,7' }, { en: '9.2', pl: '9,2' }, { en: '11.0', pl: '11,0' }], correctIndex: 2 },
    { id: 'drop-world-geography-089', prompt: { en: 'What is the area of the Gobi Desert (million sq km)?', pl: 'Jaką powierzchnię ma pustynia Gobi (mln km2)?' }, options: [{ en: '0.8', pl: '0,8' }, { en: '1.3', pl: '1,3' }, { en: '1.9', pl: '1,9' }, { en: '2.5', pl: '2,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-090', prompt: { en: 'What is the area of the Arabian Desert (million sq km)?', pl: 'Jaką powierzchnię ma Pustynia Arabska (mln km2)?' }, options: [{ en: '1.5', pl: '1,5' }, { en: '2.3', pl: '2,3' }, { en: '3.1', pl: '3,1' }, { en: '3.9', pl: '3,9' }], correctIndex: 1 },
    { id: 'drop-world-geography-091', prompt: { en: 'What is the area of the Kalahari Desert (thousand sq km)?', pl: 'Jaką powierzchnię ma pustynia Kalahari (tys. km2)?' }, options: [{ en: '620', pl: '620' }, { en: '900', pl: '900' }, { en: '1,200', pl: '1 200' }, { en: '1,500', pl: '1 500' }], correctIndex: 1 },
    { id: 'drop-world-geography-092', prompt: { en: 'What is the area of Greenland, the largest island (million sq km)?', pl: 'Jaką powierzchnię ma Grenlandia, największa wyspa (mln km2)?' }, options: [{ en: '1.5', pl: '1,5' }, { en: '2.2', pl: '2,2' }, { en: '2.9', pl: '2,9' }, { en: '3.6', pl: '3,6' }], correctIndex: 1 },
    { id: 'drop-world-geography-093', prompt: { en: 'What is the area of the island of New Guinea (thousand sq km)?', pl: 'Jaką powierzchnię ma wyspa Nowa Gwinea (tys. km2)?' }, options: [{ en: '540', pl: '540' }, { en: '786', pl: '786' }, { en: '1,020', pl: '1 020' }, { en: '1,300', pl: '1 300' }], correctIndex: 1 },
    { id: 'drop-world-geography-094', prompt: { en: 'What is the area of the island of Borneo (thousand sq km)?', pl: 'Jaką powierzchnię ma wyspa Borneo (tys. km2)?' }, options: [{ en: '520', pl: '520' }, { en: '743', pl: '743' }, { en: '960', pl: '960' }, { en: '1,200', pl: '1 200' }], correctIndex: 1 },
    { id: 'drop-world-geography-095', prompt: { en: 'What is the area of Madagascar (thousand sq km)?', pl: 'Jaką powierzchnię ma Madagaskar (tys. km2)?' }, options: [{ en: '410', pl: '410' }, { en: '587', pl: '587' }, { en: '760', pl: '760' }, { en: '940', pl: '940' }], correctIndex: 1 },
    { id: 'drop-world-geography-096', prompt: { en: 'What is the area of the island of Great Britain (thousand sq km)?', pl: 'Jaką powierzchnię ma wyspa Wielka Brytania (tys. km2)?' }, options: [{ en: '150', pl: '150' }, { en: '209', pl: '209' }, { en: '280', pl: '280' }, { en: '350', pl: '350' }], correctIndex: 1 },
    { id: 'drop-world-geography-097', prompt: { en: 'What is the area of Honshu, the main island of Japan (thousand sq km)?', pl: 'Jaką powierzchnię ma Honsiu, główna wyspa Japonii (tys. km2)?' }, options: [{ en: '160', pl: '160' }, { en: '228', pl: '228' }, { en: '300', pl: '300' }, { en: '380', pl: '380' }], correctIndex: 1 },
    { id: 'drop-world-geography-098', prompt: { en: 'What is the area of Sri Lanka (thousand sq km)?', pl: 'Jaką powierzchnię ma Sri Lanka (tys. km2)?' }, options: [{ en: '45', pl: '45' }, { en: '66', pl: '66' }, { en: '90', pl: '90' }, { en: '120', pl: '120' }], correctIndex: 1 },
    { id: 'drop-world-geography-099', prompt: { en: 'What is the area of Cuba (thousand sq km)?', pl: 'Jaką powierzchnię ma Kuba (tys. km2)?' }, options: [{ en: '78', pl: '78' }, { en: '110', pl: '110' }, { en: '145', pl: '145' }, { en: '185', pl: '185' }], correctIndex: 1 },
    { id: 'drop-world-geography-100', prompt: { en: 'What is the area of Sicily (thousand sq km)?', pl: 'Jaką powierzchnię ma Sycylia (tys. km2)?' }, options: [{ en: '18', pl: '18' }, { en: '25.7', pl: '25,7' }, { en: '34', pl: '34' }, { en: '43', pl: '43' }], correctIndex: 1 },
    { id: 'drop-world-geography-101', prompt: { en: 'What is the area of Jamaica (thousand sq km)?', pl: 'Jaką powierzchnię ma Jamajka (tys. km2)?' }, options: [{ en: '7', pl: '7' }, { en: '11', pl: '11' }, { en: '16', pl: '16' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-102', prompt: { en: 'How many islands make up the Philippines?', pl: 'Z ilu wysp składają się Filipiny?' }, options: [{ en: '2,500', pl: '2 500' }, { en: '5,000', pl: '5 000' }, { en: '7,641', pl: '7 641' }, { en: '10,000', pl: '10 000' }], correctIndex: 2 },

    // --- Seas, oceans and trenches ---
    { id: 'drop-world-geography-103', prompt: { en: 'What is the depth of the Mariana Trench at its deepest (m)?', pl: 'Jaką głębokość ma Rów Mariański w najgłębszym miejscu (m)?' }, options: [{ en: '8,500', pl: '8 500' }, { en: '9,700', pl: '9 700' }, { en: '10,994', pl: '10 994' }, { en: '12,300', pl: '12 300' }], correctIndex: 2 },
    { id: 'drop-world-geography-104', prompt: { en: 'What is the area of the Pacific Ocean (million sq km)?', pl: 'Jaką powierzchnię ma Ocean Spokojny (mln km2)?' }, options: [{ en: '120', pl: '120' }, { en: '165', pl: '165' }, { en: '200', pl: '200' }, { en: '240', pl: '240' }], correctIndex: 1 },
    { id: 'drop-world-geography-105', prompt: { en: 'What is the area of the Atlantic Ocean (million sq km)?', pl: 'Jaką powierzchnię ma Ocean Atlantycki (mln km2)?' }, options: [{ en: '76', pl: '76' }, { en: '106', pl: '106' }, { en: '140', pl: '140' }, { en: '175', pl: '175' }], correctIndex: 1 },
    { id: 'drop-world-geography-106', prompt: { en: 'What is the area of the Indian Ocean (million sq km)?', pl: 'Jaką powierzchnię ma Ocean Indyjski (mln km2)?' }, options: [{ en: '50', pl: '50' }, { en: '70', pl: '70' }, { en: '92', pl: '92' }, { en: '115', pl: '115' }], correctIndex: 1 },
    { id: 'drop-world-geography-107', prompt: { en: 'What is the area of the Mediterranean Sea (million sq km)?', pl: 'Jaką powierzchnię ma Morze Śródziemne (mln km2)?' }, options: [{ en: '1.6', pl: '1,6' }, { en: '2.5', pl: '2,5' }, { en: '3.4', pl: '3,4' }, { en: '4.3', pl: '4,3' }], correctIndex: 1 },
    { id: 'drop-world-geography-108', prompt: { en: 'What is the area of the Caribbean Sea (million sq km)?', pl: 'Jaką powierzchnię ma Morze Karaibskie (mln km2)?' }, options: [{ en: '1.8', pl: '1,8' }, { en: '2.8', pl: '2,8' }, { en: '3.7', pl: '3,7' }, { en: '4.6', pl: '4,6' }], correctIndex: 1 },
    { id: 'drop-world-geography-109', prompt: { en: 'What is the area of the South China Sea (million sq km)?', pl: 'Jaką powierzchnię ma Morze Południowochińskie (mln km2)?' }, options: [{ en: '2.4', pl: '2,4' }, { en: '3.5', pl: '3,5' }, { en: '4.6', pl: '4,6' }, { en: '5.7', pl: '5,7' }], correctIndex: 1 },
    { id: 'drop-world-geography-110', prompt: { en: 'What is the maximum depth of the Baltic Sea (m)?', pl: 'Jaka jest maksymalna głębokość Morza Bałtyckiego (m)?' }, options: [{ en: '280', pl: '280' }, { en: '459', pl: '459' }, { en: '640', pl: '640' }, { en: '820', pl: '820' }], correctIndex: 1 },
    { id: 'drop-world-geography-111', prompt: { en: 'What is the maximum depth of the Mediterranean Sea (m)?', pl: 'Jaka jest maksymalna głębokość Morza Śródziemnego (m)?' }, options: [{ en: '4,200', pl: '4 200' }, { en: '5,267', pl: '5 267' }, { en: '6,300', pl: '6 300' }, { en: '7,400', pl: '7 400' }], correctIndex: 1 },
    { id: 'drop-world-geography-112', prompt: { en: 'What is the area of the Black Sea (thousand sq km)?', pl: 'Jaką powierzchnię ma Morze Czarne (tys. km2)?' }, options: [{ en: '300', pl: '300' }, { en: '436', pl: '436' }, { en: '580', pl: '580' }, { en: '740', pl: '740' }], correctIndex: 1 },
    { id: 'drop-world-geography-113', prompt: { en: 'What is the maximum depth of the Black Sea (m)?', pl: 'Jaka jest maksymalna głębokość Morza Czarnego (m)?' }, options: [{ en: '1,500', pl: '1 500' }, { en: '2,210', pl: '2 210' }, { en: '2,900', pl: '2 900' }, { en: '3,600', pl: '3 600' }], correctIndex: 1 },

    // --- Cities (population in millions / elevation) ---
    { id: 'drop-world-geography-114', prompt: { en: 'What is the population of the Tokyo metro area (million)?', pl: 'Ilu mieszkańców liczy aglomeracja Tokio (mln)?' }, options: [{ en: '21', pl: '21' }, { en: '29', pl: '29' }, { en: '37', pl: '37' }, { en: '45', pl: '45' }], correctIndex: 2 },
    { id: 'drop-world-geography-115', prompt: { en: 'What is the population of the Delhi metro area (million)?', pl: 'Ilu mieszkańców liczy aglomeracja Delhi (mln)?' }, options: [{ en: '18', pl: '18' }, { en: '25', pl: '25' }, { en: '32', pl: '32' }, { en: '40', pl: '40' }], correctIndex: 2 },
    { id: 'drop-world-geography-116', prompt: { en: 'What is the population of the Cairo metro area (million)?', pl: 'Ilu mieszkańców liczy aglomeracja Kair (mln)?' }, options: [{ en: '14', pl: '14' }, { en: '22', pl: '22' }, { en: '30', pl: '30' }, { en: '38', pl: '38' }], correctIndex: 1 },
    { id: 'drop-world-geography-117', prompt: { en: 'What is the population of Greater London (million)?', pl: 'Ilu mieszkańców liczy Wielki Londyn (mln)?' }, options: [{ en: '6', pl: '6' }, { en: '9', pl: '9' }, { en: '12', pl: '12' }, { en: '15', pl: '15' }], correctIndex: 1 },
    { id: 'drop-world-geography-118', prompt: { en: 'What is the population of the city of Moscow (million)?', pl: 'Ilu mieszkańców liczy miasto Moskwa (mln)?' }, options: [{ en: '8', pl: '8' }, { en: '12.5', pl: '12,5' }, { en: '17', pl: '17' }, { en: '21', pl: '21' }], correctIndex: 1 },
    { id: 'drop-world-geography-119', prompt: { en: 'What is the population of the city of Beijing (million)?', pl: 'Ilu mieszkańców liczy miasto Pekin (mln)?' }, options: [{ en: '14', pl: '14' }, { en: '21', pl: '21' }, { en: '28', pl: '28' }, { en: '35', pl: '35' }], correctIndex: 1 },
    { id: 'drop-world-geography-120', prompt: { en: 'What is the population of the Paris metro area (million)?', pl: 'Ilu mieszkańców liczy aglomeracja Paryż (mln)?' }, options: [{ en: '7', pl: '7' }, { en: '11', pl: '11' }, { en: '15', pl: '15' }, { en: '19', pl: '19' }], correctIndex: 1 },
    { id: 'drop-world-geography-121', prompt: { en: 'What is the population of the Mumbai metro area (million)?', pl: 'Ilu mieszkańców liczy aglomeracja Mumbaj (mln)?' }, options: [{ en: '15', pl: '15' }, { en: '21', pl: '21' }, { en: '27', pl: '27' }, { en: '34', pl: '34' }], correctIndex: 1 },
    { id: 'drop-world-geography-122', prompt: { en: 'What is the population of the Istanbul metro area (million)?', pl: 'Ilu mieszkańców liczy aglomeracja Stambuł (mln)?' }, options: [{ en: '11', pl: '11' }, { en: '15.5', pl: '15,5' }, { en: '20', pl: '20' }, { en: '25', pl: '25' }], correctIndex: 1 },
    { id: 'drop-world-geography-123', prompt: { en: 'What is the population of the Toronto metro area (million)?', pl: 'Ilu mieszkańców liczy aglomeracja Toronto (mln)?' }, options: [{ en: '4.2', pl: '4,2' }, { en: '6.4', pl: '6,4' }, { en: '8.5', pl: '8,5' }, { en: '10.6', pl: '10,6' }], correctIndex: 1 },
    { id: 'drop-world-geography-124', prompt: { en: 'At what elevation does Mexico City sit (m)?', pl: 'Na jakiej wysokości leży miasto Meksyk (m)?' }, options: [{ en: '1,400', pl: '1 400' }, { en: '2,240', pl: '2 240' }, { en: '3,100', pl: '3 100' }, { en: '3,900', pl: '3 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-125', prompt: { en: 'At what elevation does La Paz, Bolivia sit (m)?', pl: 'Na jakiej wysokości leży La Paz w Boliwii (m)?' }, options: [{ en: '2,500', pl: '2 500' }, { en: '3,640', pl: '3 640' }, { en: '4,800', pl: '4 800' }, { en: '5,900', pl: '5 900' }], correctIndex: 1 },
    { id: 'drop-world-geography-126', prompt: { en: 'What is the population of the Los Angeles metro area (million)?', pl: 'Ilu mieszkańców liczy aglomeracja Los Angeles (mln)?' }, options: [{ en: '9', pl: '9' }, { en: '12.5', pl: '12,5' }, { en: '16', pl: '16' }, { en: '20', pl: '20' }], correctIndex: 1 },

    // --- Country populations ---
    { id: 'drop-world-geography-127', prompt: { en: 'What is the population of India (billion)?', pl: 'Jaka jest liczba ludności Indii (mld)?' }, options: [{ en: '1.0', pl: '1,0' }, { en: '1.2', pl: '1,2' }, { en: '1.4', pl: '1,4' }, { en: '1.6', pl: '1,6' }], correctIndex: 2 },
    { id: 'drop-world-geography-128', prompt: { en: 'What is the population of China (billion)?', pl: 'Jaka jest liczba ludności Chin (mld)?' }, options: [{ en: '1.1', pl: '1,1' }, { en: '1.4', pl: '1,4' }, { en: '1.7', pl: '1,7' }, { en: '2.0', pl: '2,0' }], correctIndex: 1 },
    { id: 'drop-world-geography-129', prompt: { en: 'What is the population of the USA (million)?', pl: 'Jaka jest liczba ludności Stanów Zjednoczonych (mln)?' }, options: [{ en: '270', pl: '270' }, { en: '335', pl: '335' }, { en: '410', pl: '410' }, { en: '480', pl: '480' }], correctIndex: 1 },
    { id: 'drop-world-geography-130', prompt: { en: 'What is the population of Indonesia (million)?', pl: 'Jaka jest liczba ludności Indonezji (mln)?' }, options: [{ en: '210', pl: '210' }, { en: '280', pl: '280' }, { en: '350', pl: '350' }, { en: '420', pl: '420' }], correctIndex: 1 },
    { id: 'drop-world-geography-131', prompt: { en: 'What is the population of Brazil (million)?', pl: 'Jaka jest liczba ludności Brazylii (mln)?' }, options: [{ en: '160', pl: '160' }, { en: '216', pl: '216' }, { en: '280', pl: '280' }, { en: '340', pl: '340' }], correctIndex: 1 },
    { id: 'drop-world-geography-132', prompt: { en: 'What is the population of Nigeria (million)?', pl: 'Jaka jest liczba ludności Nigerii (mln)?' }, options: [{ en: '150', pl: '150' }, { en: '223', pl: '223' }, { en: '300', pl: '300' }, { en: '380', pl: '380' }], correctIndex: 1 },
    { id: 'drop-world-geography-133', prompt: { en: 'What is the population of Japan (million)?', pl: 'Jaka jest liczba ludności Japonii (mln)?' }, options: [{ en: '95', pl: '95' }, { en: '124', pl: '124' }, { en: '160', pl: '160' }, { en: '195', pl: '195' }], correctIndex: 1 },
    { id: 'drop-world-geography-134', prompt: { en: 'What is the population of Germany (million)?', pl: 'Jaka jest liczba ludności Niemiec (mln)?' }, options: [{ en: '64', pl: '64' }, { en: '84', pl: '84' }, { en: '105', pl: '105' }, { en: '125', pl: '125' }], correctIndex: 1 },
    { id: 'drop-world-geography-135', prompt: { en: 'What is the population of Poland (million)?', pl: 'Jaka jest liczba ludności Polski (mln)?' }, options: [{ en: '28', pl: '28' }, { en: '38', pl: '38' }, { en: '48', pl: '48' }, { en: '58', pl: '58' }], correctIndex: 1 },
    { id: 'drop-world-geography-136', prompt: { en: 'What is the population of France (million)?', pl: 'Jaka jest liczba ludności Francji (mln)?' }, options: [{ en: '52', pl: '52' }, { en: '68', pl: '68' }, { en: '85', pl: '85' }, { en: '100', pl: '100' }], correctIndex: 1 },
    { id: 'drop-world-geography-137', prompt: { en: 'What is the population of Russia (million)?', pl: 'Jaka jest liczba ludności Rosji (mln)?' }, options: [{ en: '110', pl: '110' }, { en: '144', pl: '144' }, { en: '180', pl: '180' }, { en: '215', pl: '215' }], correctIndex: 1 },
    { id: 'drop-world-geography-138', prompt: { en: 'What is the population of Mexico (million)?', pl: 'Jaka jest liczba ludności Meksyku (mln)?' }, options: [{ en: '98', pl: '98' }, { en: '128', pl: '128' }, { en: '160', pl: '160' }, { en: '195', pl: '195' }], correctIndex: 1 },
    { id: 'drop-world-geography-139', prompt: { en: 'What is the population of Canada (million)?', pl: 'Jaka jest liczba ludności Kanady (mln)?' }, options: [{ en: '28', pl: '28' }, { en: '40', pl: '40' }, { en: '55', pl: '55' }, { en: '70', pl: '70' }], correctIndex: 1 },
    { id: 'drop-world-geography-140', prompt: { en: 'What is the population of Australia (million)?', pl: 'Jaka jest liczba ludności Australii (mln)?' }, options: [{ en: '18', pl: '18' }, { en: '26', pl: '26' }, { en: '35', pl: '35' }, { en: '45', pl: '45' }], correctIndex: 1 },
    { id: 'drop-world-geography-141', prompt: { en: 'What is the population of Egypt (million)?', pl: 'Jaka jest liczba ludności Egiptu (mln)?' }, options: [{ en: '82', pl: '82' }, { en: '112', pl: '112' }, { en: '145', pl: '145' }, { en: '180', pl: '180' }], correctIndex: 1 },

    // --- Landmarks, canals, straits, ranges, lines ---
    { id: 'drop-world-geography-142', prompt: { en: 'How high is Angel Falls, the tallest waterfall (m)?', pl: 'Jaką wysokość ma wodospad Salto Angel, najwyższy wodospad (m)?' }, options: [{ en: '620', pl: '620' }, { en: '810', pl: '810' }, { en: '979', pl: '979' }, { en: '1,200', pl: '1 200' }], correctIndex: 2 },
    { id: 'drop-world-geography-143', prompt: { en: 'How long is the Suez Canal (km)?', pl: 'Jaką długość ma Kanał Sueski (km)?' }, options: [{ en: '120', pl: '120' }, { en: '193', pl: '193' }, { en: '270', pl: '270' }, { en: '350', pl: '350' }], correctIndex: 1 },
    { id: 'drop-world-geography-144', prompt: { en: 'How long is the Panama Canal (km)?', pl: 'Jaką długość ma Kanał Panamski (km)?' }, options: [{ en: '50', pl: '50' }, { en: '82', pl: '82' }, { en: '120', pl: '120' }, { en: '160', pl: '160' }], correctIndex: 1 },
    { id: 'drop-world-geography-145', prompt: { en: 'How high is the drop at Niagara Falls (m)?', pl: 'Jaką wysokość ma spadek wodospadu Niagara (m)?' }, options: [{ en: '34', pl: '34' }, { en: '51', pl: '51' }, { en: '72', pl: '72' }, { en: '95', pl: '95' }], correctIndex: 1 },
    { id: 'drop-world-geography-146', prompt: { en: 'How high is the drop at Victoria Falls (m)?', pl: 'Jaką wysokość ma spadek Wodospadów Wiktorii (m)?' }, options: [{ en: '70', pl: '70' }, { en: '108', pl: '108' }, { en: '150', pl: '150' }, { en: '200', pl: '200' }], correctIndex: 1 },
    { id: 'drop-world-geography-147', prompt: { en: 'How wide is the Strait of Gibraltar at its narrowest (km)?', pl: 'Jaka jest szerokość Cieśniny Gibraltarskiej w najwęższym miejscu (km)?' }, options: [{ en: '8', pl: '8' }, { en: '13', pl: '13' }, { en: '21', pl: '21' }, { en: '30', pl: '30' }], correctIndex: 1 },
    { id: 'drop-world-geography-148', prompt: { en: 'How long is the Channel Tunnel (km)?', pl: 'Jaką długość ma Tunel pod kanałem La Manche (km)?' }, options: [{ en: '32', pl: '32' }, { en: '50', pl: '50' }, { en: '68', pl: '68' }, { en: '85', pl: '85' }], correctIndex: 1 },
    { id: 'drop-world-geography-149', prompt: { en: 'How long is the Andes mountain range (km)?', pl: 'Jaką długość ma łańcuch Andów (km)?' }, options: [{ en: '5,000', pl: '5 000' }, { en: '7,000', pl: '7 000' }, { en: '9,000', pl: '9 000' }, { en: '11,000', pl: '11 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-150', prompt: { en: 'How long is the Himalayan mountain range (km)?', pl: 'Jaką długość ma łańcuch Himalajów (km)?' }, options: [{ en: '1,600', pl: '1 600' }, { en: '2,400', pl: '2 400' }, { en: '3,200', pl: '3 200' }, { en: '4,000', pl: '4 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-151', prompt: { en: 'How long is the Great Barrier Reef (km)?', pl: 'Jaką długość ma Wielka Rafa Koralowa (km)?' }, options: [{ en: '1,400', pl: '1 400' }, { en: '2,300', pl: '2 300' }, { en: '3,200', pl: '3 200' }, { en: '4,100', pl: '4 100' }], correctIndex: 1 },
    { id: 'drop-world-geography-152', prompt: { en: 'How tall is the Eiffel Tower to the tip (m)?', pl: 'Jaką wysokość ma Wieża Eiffla do szczytu (m)?' }, options: [{ en: '210', pl: '210' }, { en: '330', pl: '330' }, { en: '450', pl: '450' }, { en: '580', pl: '580' }], correctIndex: 1 },
    { id: 'drop-world-geography-153', prompt: { en: 'How long is the Trans-Siberian Railway (km)?', pl: 'Jaką długość ma Kolej Transsyberyjska (km)?' }, options: [{ en: '6,500', pl: '6 500' }, { en: '9,289', pl: '9 289' }, { en: '12,000', pl: '12 000' }, { en: '15,000', pl: '15 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-154', prompt: { en: 'How long is the Rocky Mountains range (km)?', pl: 'Jaką długość mają Góry Skaliste (km)?' }, options: [{ en: '3,200', pl: '3 200' }, { en: '4,800', pl: '4 800' }, { en: '6,400', pl: '6 400' }, { en: '8,000', pl: '8 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-155', prompt: { en: 'How wide is the Bering Strait at its narrowest (km)?', pl: 'Jaka jest szerokość Cieśniny Beringa w najwęższym miejscu (km)?' }, options: [{ en: '50', pl: '50' }, { en: '82', pl: '82' }, { en: '120', pl: '120' }, { en: '160', pl: '160' }], correctIndex: 1 },
    { id: 'drop-world-geography-156', prompt: { en: 'What is the area of the Amazon rainforest (million sq km)?', pl: 'Jaką powierzchnię ma Puszcza Amazońska (mln km2)?' }, options: [{ en: '4.0', pl: '4,0' }, { en: '5.5', pl: '5,5' }, { en: '7.0', pl: '7,0' }, { en: '8.5', pl: '8,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-157', prompt: { en: 'How wide is the Strait of Dover at its narrowest (km)?', pl: 'Jaka jest szerokość Cieśniny Kaletańskiej w najwęższym miejscu (km)?' }, options: [{ en: '20', pl: '20' }, { en: '33', pl: '33' }, { en: '48', pl: '48' }, { en: '64', pl: '64' }], correctIndex: 1 },
    { id: 'drop-world-geography-158', prompt: { en: 'How long is the Kiel Canal (km)?', pl: 'Jaką długość ma Kanał Kiloński (km)?' }, options: [{ en: '60', pl: '60' }, { en: '98', pl: '98' }, { en: '140', pl: '140' }, { en: '185', pl: '185' }], correctIndex: 1 },
    { id: 'drop-world-geography-159', prompt: { en: 'How tall is the CN Tower in Toronto (m)?', pl: 'Jaką wysokość ma Wieża CN w Toronto (m)?' }, options: [{ en: '420', pl: '420' }, { en: '553', pl: '553' }, { en: '690', pl: '690' }, { en: '820', pl: '820' }], correctIndex: 1 },
    { id: 'drop-world-geography-160', prompt: { en: 'How long is the Equator (km)?', pl: 'Jaką długość ma równik (km)?' }, options: [{ en: '32,000', pl: '32 000' }, { en: '40,075', pl: '40 075' }, { en: '48,000', pl: '48 000' }, { en: '56,000', pl: '56 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-161', prompt: { en: 'At what latitude does the Tropic of Cancer lie (degrees N)?', pl: 'Na jakiej szerokości geograficznej leży Zwrotnik Raka (stopnie N)?' }, options: [{ en: '18.5', pl: '18,5' }, { en: '23.5', pl: '23,5' }, { en: '28.5', pl: '28,5' }, { en: '33.5', pl: '33,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-162', prompt: { en: 'At what latitude does the Arctic Circle lie (degrees N)?', pl: 'Na jakiej szerokości geograficznej leży koło podbiegunowe północne (stopnie N)?' }, options: [{ en: '60.5', pl: '60,5' }, { en: '66.5', pl: '66,5' }, { en: '72.5', pl: '72,5' }, { en: '78.5', pl: '78,5' }], correctIndex: 1 },
    { id: 'drop-world-geography-163', prompt: { en: 'How many time zones does Russia span?', pl: 'Ile stref czasowych obejmuje Rosja?' }, options: [{ en: '7', pl: '7' }, { en: '9', pl: '9' }, { en: '11', pl: '11' }, { en: '13', pl: '13' }], correctIndex: 2 },

    // --- Borders, neighbours and country counts ---
    { id: 'drop-world-geography-164', prompt: { en: 'How many countries border China?', pl: 'Z iloma państwami graniczą Chiny?' }, options: [{ en: '11', pl: '11' }, { en: '14', pl: '14' }, { en: '17', pl: '17' }, { en: '20', pl: '20' }], correctIndex: 1 },
    { id: 'drop-world-geography-165', prompt: { en: 'How many countries border Brazil?', pl: 'Z iloma państwami graniczy Brazylia?' }, options: [{ en: '7', pl: '7' }, { en: '10', pl: '10' }, { en: '13', pl: '13' }, { en: '16', pl: '16' }], correctIndex: 1 },
    { id: 'drop-world-geography-166', prompt: { en: 'How many countries border mainland France?', pl: 'Z iloma państwami graniczy kontynentalna Francja?' }, options: [{ en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }, { en: '12', pl: '12' }], correctIndex: 1 },
    { id: 'drop-world-geography-167', prompt: { en: 'How many countries border Austria?', pl: 'Z iloma państwami graniczy Austria?' }, options: [{ en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }, { en: '12', pl: '12' }], correctIndex: 1 },
    { id: 'drop-world-geography-168', prompt: { en: 'How many countries border Switzerland?', pl: 'Z iloma państwami graniczy Szwajcaria?' }, options: [{ en: '3', pl: '3' }, { en: '5', pl: '5' }, { en: '7', pl: '7' }, { en: '9', pl: '9' }], correctIndex: 1 },
    { id: 'drop-world-geography-169', prompt: { en: 'How many countries does Russia border by land?', pl: 'Z iloma państwami Rosja graniczy lądowo?' }, options: [{ en: '10', pl: '10' }, { en: '14', pl: '14' }, { en: '18', pl: '18' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-170', prompt: { en: 'How many countries border Hungary?', pl: 'Z iloma państwami graniczą Węgry?' }, options: [{ en: '5', pl: '5' }, { en: '7', pl: '7' }, { en: '9', pl: '9' }, { en: '11', pl: '11' }], correctIndex: 1 },
    { id: 'drop-world-geography-171', prompt: { en: 'How many landlocked countries are in South America?', pl: 'Ile państw śródlądowych znajduje się w Ameryce Południowej?' }, options: [{ en: '0', pl: '0' }, { en: '2', pl: '2' }, { en: '4', pl: '4' }, { en: '6', pl: '6' }], correctIndex: 1 },
    { id: 'drop-world-geography-172', prompt: { en: 'How many countries are in Central America?', pl: 'Ile państw znajduje się w Ameryce Środkowej?' }, options: [{ en: '5', pl: '5' }, { en: '7', pl: '7' }, { en: '9', pl: '9' }, { en: '11', pl: '11' }], correctIndex: 1 },
    { id: 'drop-world-geography-173', prompt: { en: 'How many countries are in South America?', pl: 'Ile państw znajduje się w Ameryce Południowej?' }, options: [{ en: '10', pl: '10' }, { en: '12', pl: '12' }, { en: '14', pl: '14' }, { en: '16', pl: '16' }], correctIndex: 1 },
    { id: 'drop-world-geography-174', prompt: { en: 'How many sovereign countries are in Oceania?', pl: 'Ile suwerennych państw znajduje się w Oceanii?' }, options: [{ en: '10', pl: '10' }, { en: '14', pl: '14' }, { en: '18', pl: '18' }, { en: '22', pl: '22' }], correctIndex: 1 },
    { id: 'drop-world-geography-175', prompt: { en: 'How many countries border the Black Sea?', pl: 'Ile państw leży nad Morzem Czarnym?' }, options: [{ en: '4', pl: '4' }, { en: '6', pl: '6' }, { en: '8', pl: '8' }, { en: '10', pl: '10' }], correctIndex: 1 },
    { id: 'drop-world-geography-176', prompt: { en: 'How many Great Lakes are there in North America?', pl: 'Ile Wielkich Jezior znajduje się w Ameryce Północnej?' }, options: [{ en: '3', pl: '3' }, { en: '4', pl: '4' }, { en: '5', pl: '5' }, { en: '6', pl: '6' }], correctIndex: 2 },
    { id: 'drop-world-geography-177', prompt: { en: 'How many member states are in the European Union (2024)?', pl: 'Ile państw członkowskich liczy Unia Europejska (2024)?' }, options: [{ en: '24', pl: '24' }, { en: '27', pl: '27' }, { en: '30', pl: '30' }, { en: '33', pl: '33' }], correctIndex: 1 },
    { id: 'drop-world-geography-178', prompt: { en: 'How long is the coastline of Australia (thousand km)?', pl: 'Jaką długość ma linia brzegowa Australii (tys. km)?' }, options: [{ en: '16', pl: '16' }, { en: '26', pl: '26' }, { en: '36', pl: '36' }, { en: '48', pl: '48' }], correctIndex: 1 },
    { id: 'drop-world-geography-179', prompt: { en: 'How long is the border between the USA and Canada (km)?', pl: 'Jaką długość ma granica między USA a Kanadą (km)?' }, options: [{ en: '5,500', pl: '5 500' }, { en: '8,891', pl: '8 891' }, { en: '12,000', pl: '12 000' }, { en: '15,000', pl: '15 000' }], correctIndex: 1 },
    { id: 'drop-world-geography-180', prompt: { en: 'How long is the border between France and Spain (km)?', pl: 'Jaką długość ma granica między Francją a Hiszpanią (km)?' }, options: [{ en: '450', pl: '450' }, { en: '660', pl: '660' }, { en: '900', pl: '900' }, { en: '1,200', pl: '1 200' }], correctIndex: 1 },
];

const toLocale = (lang: 'en' | 'pl') => (c: BiCard): DropPackCard => ({
    id: c.id,
    prompt: c.prompt[lang],
    options: c.options.map((o) => o[lang]),
    correctIndex: c.correctIndex,
});

export const worldGeographyEn: DropPackCard[] = cards.map(toLocale('en'));
export const worldGeographyPl: DropPackCard[] = cards.map(toLocale('pl'));
